// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: common.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserProfile struct {
	state                            protoimpl.MessageState `protogen:"open.v1"`
	Username                         string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	ExpectedSalaryMin                string                 `protobuf:"bytes,2,opt,name=expected_salary_min,json=expectedSalaryMin,proto3" json:"expected_salary_min,omitempty"` // 单位：分，0 表示未填写
	ExpectedSalaryMax                string                 `protobuf:"bytes,3,opt,name=expected_salary_max,json=expectedSalaryMax,proto3" json:"expected_salary_max,omitempty"`
	WorkLocation                     string                 `protobuf:"bytes,4,opt,name=work_location,json=workLocation,proto3" json:"work_location,omitempty"`          // "Remote", "Beijing", ...
	ExperienceLevel                  string                 `protobuf:"bytes,5,opt,name=experience_level,json=experienceLevel,proto3" json:"experience_level,omitempty"` // ENTRY | JUNIOR | MID | SENIOR | EXPERT
	Bio                              string                 `protobuf:"bytes,6,opt,name=bio,proto3" json:"bio,omitempty"`
	AvatarUrl                        string                 `protobuf:"bytes,7,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	CompletionRate                   float64                `protobuf:"fixed64,8,opt,name=completion_rate,json=completionRate,proto3" json:"completion_rate,omitempty"`   // 0.0 ~ 1.0
	GoodReviewRate                   float64                `protobuf:"fixed64,9,opt,name=good_review_rate,json=goodReviewRate,proto3" json:"good_review_rate,omitempty"` // 0.0 ~ 1.0
	TotalBountiesPosted              int32                  `protobuf:"varint,10,opt,name=total_bounties_posted,json=totalBountiesPosted,proto3" json:"total_bounties_posted,omitempty"`
	TotalBountiesCompleted           int32                  `protobuf:"varint,11,opt,name=total_bounties_completed,json=totalBountiesCompleted,proto3" json:"total_bounties_completed,omitempty"`
	TotalBountiesCompletedAsEmployer int32                  `protobuf:"varint,17,opt,name=total_bounties_completed_as_employer,json=totalBountiesCompletedAsEmployer,proto3" json:"total_bounties_completed_as_employer,omitempty"` // 雇主视角的完成数
	TotalEarnings                    int64                  `protobuf:"varint,12,opt,name=total_earnings,json=totalEarnings,proto3" json:"total_earnings,omitempty"`                                                                // 单位：分
	Role                             string                 `protobuf:"bytes,16,opt,name=role,proto3" json:"role,omitempty"`                                                                                                        // HUNTER | EMPLOYER (默认 EMPLOYER)
	ReputationScore                  float64                `protobuf:"fixed64,15,opt,name=reputation_score,json=reputationScore,proto3" json:"reputation_score,omitempty"`                                                         // 信誉分，牛顿冷却衰减后的分数
	CreatedAt                        *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt                        *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	HunterFulfillmentIndex           int32                  `protobuf:"varint,18,opt,name=hunter_fulfillment_index,json=hunterFulfillmentIndex,proto3" json:"hunter_fulfillment_index,omitempty"`       // 猎人履约指数 [0,100]
	EmployerFulfillmentIndex         int32                  `protobuf:"varint,19,opt,name=employer_fulfillment_index,json=employerFulfillmentIndex,proto3" json:"employer_fulfillment_index,omitempty"` // 雇主履约指数 [0,100]
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *UserProfile) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserProfile) GetExpectedSalaryMin() string {
	if x != nil {
		return x.ExpectedSalaryMin
	}
	return ""
}

func (x *UserProfile) GetExpectedSalaryMax() string {
	if x != nil {
		return x.ExpectedSalaryMax
	}
	return ""
}

func (x *UserProfile) GetWorkLocation() string {
	if x != nil {
		return x.WorkLocation
	}
	return ""
}

func (x *UserProfile) GetExperienceLevel() string {
	if x != nil {
		return x.ExperienceLevel
	}
	return ""
}

func (x *UserProfile) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UserProfile) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *UserProfile) GetCompletionRate() float64 {
	if x != nil {
		return x.CompletionRate
	}
	return 0
}

func (x *UserProfile) GetGoodReviewRate() float64 {
	if x != nil {
		return x.GoodReviewRate
	}
	return 0
}

func (x *UserProfile) GetTotalBountiesPosted() int32 {
	if x != nil {
		return x.TotalBountiesPosted
	}
	return 0
}

func (x *UserProfile) GetTotalBountiesCompleted() int32 {
	if x != nil {
		return x.TotalBountiesCompleted
	}
	return 0
}

func (x *UserProfile) GetTotalBountiesCompletedAsEmployer() int32 {
	if x != nil {
		return x.TotalBountiesCompletedAsEmployer
	}
	return 0
}

func (x *UserProfile) GetTotalEarnings() int64 {
	if x != nil {
		return x.TotalEarnings
	}
	return 0
}

func (x *UserProfile) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UserProfile) GetReputationScore() float64 {
	if x != nil {
		return x.ReputationScore
	}
	return 0
}

func (x *UserProfile) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserProfile) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *UserProfile) GetHunterFulfillmentIndex() int32 {
	if x != nil {
		return x.HunterFulfillmentIndex
	}
	return 0
}

func (x *UserProfile) GetEmployerFulfillmentIndex() int32 {
	if x != nil {
		return x.EmployerFulfillmentIndex
	}
	return 0
}

type UserReview struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ReviewerUsername  string                 `protobuf:"bytes,2,opt,name=reviewer_username,json=reviewerUsername,proto3" json:"reviewer_username,omitempty"`
	ReviewedUsername  string                 `protobuf:"bytes,3,opt,name=reviewed_username,json=reviewedUsername,proto3" json:"reviewed_username,omitempty"`
	BountyId          int64                  `protobuf:"varint,4,opt,name=bounty_id,json=bountyId,proto3" json:"bounty_id,omitempty"`
	Rating            int32                  `protobuf:"varint,5,opt,name=rating,proto3" json:"rating,omitempty"` // 1 ~ 5
	Comment           string                 `protobuf:"bytes,6,opt,name=comment,proto3" json:"comment,omitempty"`
	ReviewType        string                 `protobuf:"bytes,7,opt,name=review_type,json=reviewType,proto3" json:"review_type,omitempty"` // EMPLOYER_TO_HUNTER | HUNTER_TO_EMPLOYER
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ReviewerAvatarUrl string                 `protobuf:"bytes,9,opt,name=reviewer_avatar_url,json=reviewerAvatarUrl,proto3" json:"reviewer_avatar_url,omitempty"` // 评论者头像
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UserReview) Reset() {
	*x = UserReview{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserReview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReview) ProtoMessage() {}

func (x *UserReview) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReview.ProtoReflect.Descriptor instead.
func (*UserReview) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *UserReview) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserReview) GetReviewerUsername() string {
	if x != nil {
		return x.ReviewerUsername
	}
	return ""
}

func (x *UserReview) GetReviewedUsername() string {
	if x != nil {
		return x.ReviewedUsername
	}
	return ""
}

func (x *UserReview) GetBountyId() int64 {
	if x != nil {
		return x.BountyId
	}
	return 0
}

func (x *UserReview) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *UserReview) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *UserReview) GetReviewType() string {
	if x != nil {
		return x.ReviewType
	}
	return ""
}

func (x *UserReview) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserReview) GetReviewerAvatarUrl() string {
	if x != nil {
		return x.ReviewerAvatarUrl
	}
	return ""
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\"\xef\x06\n" +
	"\vUserProfile\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12.\n" +
	"\x13expected_salary_min\x18\x02 \x01(\tR\x11expectedSalaryMin\x12.\n" +
	"\x13expected_salary_max\x18\x03 \x01(\tR\x11expectedSalaryMax\x12#\n" +
	"\rwork_location\x18\x04 \x01(\tR\fworkLocation\x12)\n" +
	"\x10experience_level\x18\x05 \x01(\tR\x0fexperienceLevel\x12\x10\n" +
	"\x03bio\x18\x06 \x01(\tR\x03bio\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\a \x01(\tR\tavatarUrl\x12'\n" +
	"\x0fcompletion_rate\x18\b \x01(\x01R\x0ecompletionRate\x12(\n" +
	"\x10good_review_rate\x18\t \x01(\x01R\x0egoodReviewRate\x122\n" +
	"\x15total_bounties_posted\x18\n" +
	" \x01(\x05R\x13totalBountiesPosted\x128\n" +
	"\x18total_bounties_completed\x18\v \x01(\x05R\x16totalBountiesCompleted\x12N\n" +
	"$total_bounties_completed_as_employer\x18\x11 \x01(\x05R totalBountiesCompletedAsEmployer\x12%\n" +
	"\x0etotal_earnings\x18\f \x01(\x03R\rtotalEarnings\x12\x12\n" +
	"\x04role\x18\x10 \x01(\tR\x04role\x12)\n" +
	"\x10reputation_score\x18\x0f \x01(\x01R\x0freputationScore\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x128\n" +
	"\x18hunter_fulfillment_index\x18\x12 \x01(\x05R\x16hunterFulfillmentIndex\x12<\n" +
	"\x1aemployer_fulfillment_index\x18\x13 \x01(\x05R\x18employerFulfillmentIndex\"\xd1\x02\n" +
	"\n" +
	"UserReview\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12+\n" +
	"\x11reviewer_username\x18\x02 \x01(\tR\x10reviewerUsername\x12+\n" +
	"\x11reviewed_username\x18\x03 \x01(\tR\x10reviewedUsername\x12\x1b\n" +
	"\tbounty_id\x18\x04 \x01(\x03R\bbountyId\x12\x16\n" +
	"\x06rating\x18\x05 \x01(\x05R\x06rating\x12\x18\n" +
	"\acomment\x18\x06 \x01(\tR\acomment\x12\x1f\n" +
	"\vreview_type\x18\a \x01(\tR\n" +
	"reviewType\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12.\n" +
	"\x13reviewer_avatar_url\x18\t \x01(\tR\x11reviewerAvatarUrlB2Z0github.com/grayfalcon666/user-profile-service/pbb\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_proto_goTypes = []any{
	(*UserProfile)(nil),           // 0: pb.UserProfile
	(*UserReview)(nil),            // 1: pb.UserReview
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_common_proto_depIdxs = []int32{
	2, // 0: pb.UserProfile.created_at:type_name -> google.protobuf.Timestamp
	2, // 1: pb.UserProfile.updated_at:type_name -> google.protobuf.Timestamp
	2, // 2: pb.UserReview.created_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
