// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: profile.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{0}
}

func (x *GetProfileRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *UserProfile           `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	mi := &file_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse.ProtoReflect.Descriptor instead.
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{1}
}

func (x *GetProfileResponse) GetProfile() *UserProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type CreateProfileRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ExpectedSalaryMin string                 `protobuf:"bytes,1,opt,name=expected_salary_min,json=expectedSalaryMin,proto3" json:"expected_salary_min,omitempty"`
	ExpectedSalaryMax string                 `protobuf:"bytes,2,opt,name=expected_salary_max,json=expectedSalaryMax,proto3" json:"expected_salary_max,omitempty"`
	WorkLocation      string                 `protobuf:"bytes,3,opt,name=work_location,json=workLocation,proto3" json:"work_location,omitempty"`
	ExperienceLevel   string                 `protobuf:"bytes,4,opt,name=experience_level,json=experienceLevel,proto3" json:"experience_level,omitempty"`
	Bio               string                 `protobuf:"bytes,5,opt,name=bio,proto3" json:"bio,omitempty"`
	AvatarUrl         string                 `protobuf:"bytes,6,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateProfileRequest) Reset() {
	*x = CreateProfileRequest{}
	mi := &file_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileRequest) ProtoMessage() {}

func (x *CreateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileRequest.ProtoReflect.Descriptor instead.
func (*CreateProfileRequest) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{2}
}

func (x *CreateProfileRequest) GetExpectedSalaryMin() string {
	if x != nil {
		return x.ExpectedSalaryMin
	}
	return ""
}

func (x *CreateProfileRequest) GetExpectedSalaryMax() string {
	if x != nil {
		return x.ExpectedSalaryMax
	}
	return ""
}

func (x *CreateProfileRequest) GetWorkLocation() string {
	if x != nil {
		return x.WorkLocation
	}
	return ""
}

func (x *CreateProfileRequest) GetExperienceLevel() string {
	if x != nil {
		return x.ExperienceLevel
	}
	return ""
}

func (x *CreateProfileRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *CreateProfileRequest) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type CreateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *UserProfile           `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProfileResponse) Reset() {
	*x = CreateProfileResponse{}
	mi := &file_profile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileResponse) ProtoMessage() {}

func (x *CreateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileResponse.ProtoReflect.Descriptor instead.
func (*CreateProfileResponse) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{3}
}

func (x *CreateProfileResponse) GetProfile() *UserProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type UpdateProfileRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Username          string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	ExpectedSalaryMin string                 `protobuf:"bytes,2,opt,name=expected_salary_min,json=expectedSalaryMin,proto3" json:"expected_salary_min,omitempty"`
	ExpectedSalaryMax string                 `protobuf:"bytes,3,opt,name=expected_salary_max,json=expectedSalaryMax,proto3" json:"expected_salary_max,omitempty"`
	WorkLocation      string                 `protobuf:"bytes,4,opt,name=work_location,json=workLocation,proto3" json:"work_location,omitempty"`
	ExperienceLevel   string                 `protobuf:"bytes,5,opt,name=experience_level,json=experienceLevel,proto3" json:"experience_level,omitempty"`
	Bio               string                 `protobuf:"bytes,6,opt,name=bio,proto3" json:"bio,omitempty"`
	AvatarUrl         string                 `protobuf:"bytes,7,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Role              string                 `protobuf:"bytes,8,opt,name=role,proto3" json:"role,omitempty"` // HUNTER | POSTER
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_profile_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateProfileRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateProfileRequest) GetExpectedSalaryMin() string {
	if x != nil {
		return x.ExpectedSalaryMin
	}
	return ""
}

func (x *UpdateProfileRequest) GetExpectedSalaryMax() string {
	if x != nil {
		return x.ExpectedSalaryMax
	}
	return ""
}

func (x *UpdateProfileRequest) GetWorkLocation() string {
	if x != nil {
		return x.WorkLocation
	}
	return ""
}

func (x *UpdateProfileRequest) GetExperienceLevel() string {
	if x != nil {
		return x.ExperienceLevel
	}
	return ""
}

func (x *UpdateProfileRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UpdateProfileRequest) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *UpdateProfileRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type UpdateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *UserProfile           `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileResponse) Reset() {
	*x = UpdateProfileResponse{}
	mi := &file_profile_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResponse) ProtoMessage() {}

func (x *UpdateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateProfileResponse) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateProfileResponse) GetProfile() *UserProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type RefreshProfileStatsRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Username                 string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	BountyId                 int64                  `protobuf:"varint,2,opt,name=bounty_id,json=bountyId,proto3" json:"bounty_id,omitempty"`
	DeltaCompleted           int32                  `protobuf:"varint,3,opt,name=delta_completed,json=deltaCompleted,proto3" json:"delta_completed,omitempty"`                                   // +1 完成, -1 取消
	DeltaEarnings            int64                  `protobuf:"varint,4,opt,name=delta_earnings,json=deltaEarnings,proto3" json:"delta_earnings,omitempty"`                                      // 本次悬赏金额（分）
	DeltaPosted              int32                  `protobuf:"varint,5,opt,name=delta_posted,json=deltaPosted,proto3" json:"delta_posted,omitempty"`                                            // +1 发布
	DeltaCompletedAsEmployer int32                  `protobuf:"varint,6,opt,name=delta_completed_as_employer,json=deltaCompletedAsEmployer,proto3" json:"delta_completed_as_employer,omitempty"` // 雇主完成数 +1
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *RefreshProfileStatsRequest) Reset() {
	*x = RefreshProfileStatsRequest{}
	mi := &file_profile_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshProfileStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshProfileStatsRequest) ProtoMessage() {}

func (x *RefreshProfileStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshProfileStatsRequest.ProtoReflect.Descriptor instead.
func (*RefreshProfileStatsRequest) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{6}
}

func (x *RefreshProfileStatsRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RefreshProfileStatsRequest) GetBountyId() int64 {
	if x != nil {
		return x.BountyId
	}
	return 0
}

func (x *RefreshProfileStatsRequest) GetDeltaCompleted() int32 {
	if x != nil {
		return x.DeltaCompleted
	}
	return 0
}

func (x *RefreshProfileStatsRequest) GetDeltaEarnings() int64 {
	if x != nil {
		return x.DeltaEarnings
	}
	return 0
}

func (x *RefreshProfileStatsRequest) GetDeltaPosted() int32 {
	if x != nil {
		return x.DeltaPosted
	}
	return 0
}

func (x *RefreshProfileStatsRequest) GetDeltaCompletedAsEmployer() int32 {
	if x != nil {
		return x.DeltaCompletedAsEmployer
	}
	return 0
}

type RefreshProfileStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *UserProfile           `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshProfileStatsResponse) Reset() {
	*x = RefreshProfileStatsResponse{}
	mi := &file_profile_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshProfileStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshProfileStatsResponse) ProtoMessage() {}

func (x *RefreshProfileStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshProfileStatsResponse.ProtoReflect.Descriptor instead.
func (*RefreshProfileStatsResponse) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{7}
}

func (x *RefreshProfileStatsResponse) GetProfile() *UserProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type SearchUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsersRequest) Reset() {
	*x = SearchUsersRequest{}
	mi := &file_profile_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersRequest) ProtoMessage() {}

func (x *SearchUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersRequest.ProtoReflect.Descriptor instead.
func (*SearchUsersRequest) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{8}
}

func (x *SearchUsersRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchUsersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserSummary         `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsersResponse) Reset() {
	*x = SearchUsersResponse{}
	mi := &file_profile_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersResponse) ProtoMessage() {}

func (x *SearchUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersResponse.ProtoReflect.Descriptor instead.
func (*SearchUsersResponse) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{9}
}

func (x *SearchUsersResponse) GetUsers() []*UserSummary {
	if x != nil {
		return x.Users
	}
	return nil
}

type UserSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSummary) Reset() {
	*x = UserSummary{}
	mi := &file_profile_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSummary) ProtoMessage() {}

func (x *UserSummary) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSummary.ProtoReflect.Descriptor instead.
func (*UserSummary) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{10}
}

func (x *UserSummary) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type InitializeProfileRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Username          string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	RequestId         string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ExpectedSalaryMin string                 `protobuf:"bytes,3,opt,name=expected_salary_min,json=expectedSalaryMin,proto3" json:"expected_salary_min,omitempty"`
	ExpectedSalaryMax string                 `protobuf:"bytes,4,opt,name=expected_salary_max,json=expectedSalaryMax,proto3" json:"expected_salary_max,omitempty"`
	WorkLocation      string                 `protobuf:"bytes,5,opt,name=work_location,json=workLocation,proto3" json:"work_location,omitempty"`
	ExperienceLevel   string                 `protobuf:"bytes,6,opt,name=experience_level,json=experienceLevel,proto3" json:"experience_level,omitempty"`
	Bio               string                 `protobuf:"bytes,7,opt,name=bio,proto3" json:"bio,omitempty"`
	AvatarUrl         string                 `protobuf:"bytes,8,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InitializeProfileRequest) Reset() {
	*x = InitializeProfileRequest{}
	mi := &file_profile_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeProfileRequest) ProtoMessage() {}

func (x *InitializeProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeProfileRequest.ProtoReflect.Descriptor instead.
func (*InitializeProfileRequest) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{11}
}

func (x *InitializeProfileRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *InitializeProfileRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *InitializeProfileRequest) GetExpectedSalaryMin() string {
	if x != nil {
		return x.ExpectedSalaryMin
	}
	return ""
}

func (x *InitializeProfileRequest) GetExpectedSalaryMax() string {
	if x != nil {
		return x.ExpectedSalaryMax
	}
	return ""
}

func (x *InitializeProfileRequest) GetWorkLocation() string {
	if x != nil {
		return x.WorkLocation
	}
	return ""
}

func (x *InitializeProfileRequest) GetExperienceLevel() string {
	if x != nil {
		return x.ExperienceLevel
	}
	return ""
}

func (x *InitializeProfileRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *InitializeProfileRequest) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type InitializeProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *UserProfile           `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Created       bool                   `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeProfileResponse) Reset() {
	*x = InitializeProfileResponse{}
	mi := &file_profile_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeProfileResponse) ProtoMessage() {}

func (x *InitializeProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeProfileResponse.ProtoReflect.Descriptor instead.
func (*InitializeProfileResponse) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{12}
}

func (x *InitializeProfileResponse) GetProfile() *UserProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *InitializeProfileResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

func (x *InitializeProfileResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type UpdateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"` // HUNTER | POSTER
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleRequest) Reset() {
	*x = UpdateRoleRequest{}
	mi := &file_profile_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleRequest) ProtoMessage() {}

func (x *UpdateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoleRequest) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateRoleRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateRoleRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type UpdateRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *UserProfile           `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleResponse) Reset() {
	*x = UpdateRoleResponse{}
	mi := &file_profile_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleResponse) ProtoMessage() {}

func (x *UpdateRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleResponse.ProtoReflect.Descriptor instead.
func (*UpdateRoleResponse) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateRoleResponse) GetProfile() *UserProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type SearchHuntersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	SortBy        string                 `protobuf:"bytes,3,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"` // completion_rate | good_review_rate | total_bounties_completed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchHuntersRequest) Reset() {
	*x = SearchHuntersRequest{}
	mi := &file_profile_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchHuntersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHuntersRequest) ProtoMessage() {}

func (x *SearchHuntersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHuntersRequest.ProtoReflect.Descriptor instead.
func (*SearchHuntersRequest) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{15}
}

func (x *SearchHuntersRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchHuntersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchHuntersRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

type SearchHuntersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hunters       []*UserProfile         `protobuf:"bytes,1,rep,name=hunters,proto3" json:"hunters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchHuntersResponse) Reset() {
	*x = SearchHuntersResponse{}
	mi := &file_profile_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchHuntersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHuntersResponse) ProtoMessage() {}

func (x *SearchHuntersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHuntersResponse.ProtoReflect.Descriptor instead.
func (*SearchHuntersResponse) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{16}
}

func (x *SearchHuntersResponse) GetHunters() []*UserProfile {
	if x != nil {
		return x.Hunters
	}
	return nil
}

var File_profile_proto protoreflect.FileDescriptor

const file_profile_proto_rawDesc = "" +
	"\n" +
	"\rprofile.proto\x12\x02pb\x1a\x1cgoogle/api/annotations.proto\x1a\fcommon.proto\"/\n" +
	"\x11GetProfileRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"?\n" +
	"\x12GetProfileResponse\x12)\n" +
	"\aprofile\x18\x01 \x01(\v2\x0f.pb.UserProfileR\aprofile\"\xf7\x01\n" +
	"\x14CreateProfileRequest\x12.\n" +
	"\x13expected_salary_min\x18\x01 \x01(\tR\x11expectedSalaryMin\x12.\n" +
	"\x13expected_salary_max\x18\x02 \x01(\tR\x11expectedSalaryMax\x12#\n" +
	"\rwork_location\x18\x03 \x01(\tR\fworkLocation\x12)\n" +
	"\x10experience_level\x18\x04 \x01(\tR\x0fexperienceLevel\x12\x10\n" +
	"\x03bio\x18\x05 \x01(\tR\x03bio\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x06 \x01(\tR\tavatarUrl\"B\n" +
	"\x15CreateProfileResponse\x12)\n" +
	"\aprofile\x18\x01 \x01(\v2\x0f.pb.UserProfileR\aprofile\"\xa7\x02\n" +
	"\x14UpdateProfileRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12.\n" +
	"\x13expected_salary_min\x18\x02 \x01(\tR\x11expectedSalaryMin\x12.\n" +
	"\x13expected_salary_max\x18\x03 \x01(\tR\x11expectedSalaryMax\x12#\n" +
	"\rwork_location\x18\x04 \x01(\tR\fworkLocation\x12)\n" +
	"\x10experience_level\x18\x05 \x01(\tR\x0fexperienceLevel\x12\x10\n" +
	"\x03bio\x18\x06 \x01(\tR\x03bio\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\a \x01(\tR\tavatarUrl\x12\x12\n" +
	"\x04role\x18\b \x01(\tR\x04role\"B\n" +
	"\x15UpdateProfileResponse\x12)\n" +
	"\aprofile\x18\x01 \x01(\v2\x0f.pb.UserProfileR\aprofile\"\x87\x02\n" +
	"\x1aRefreshProfileStatsRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1b\n" +
	"\tbounty_id\x18\x02 \x01(\x03R\bbountyId\x12'\n" +
	"\x0fdelta_completed\x18\x03 \x01(\x05R\x0edeltaCompleted\x12%\n" +
	"\x0edelta_earnings\x18\x04 \x01(\x03R\rdeltaEarnings\x12!\n" +
	"\fdelta_posted\x18\x05 \x01(\x05R\vdeltaPosted\x12=\n" +
	"\x1bdelta_completed_as_employer\x18\x06 \x01(\x05R\x18deltaCompletedAsEmployer\"H\n" +
	"\x1bRefreshProfileStatsResponse\x12)\n" +
	"\aprofile\x18\x01 \x01(\v2\x0f.pb.UserProfileR\aprofile\"@\n" +
	"\x12SearchUsersRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"<\n" +
	"\x13SearchUsersResponse\x12%\n" +
	"\x05users\x18\x01 \x03(\v2\x0f.pb.UserSummaryR\x05users\")\n" +
	"\vUserSummary\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"\xb6\x02\n" +
	"\x18InitializeProfileRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12.\n" +
	"\x13expected_salary_min\x18\x03 \x01(\tR\x11expectedSalaryMin\x12.\n" +
	"\x13expected_salary_max\x18\x04 \x01(\tR\x11expectedSalaryMax\x12#\n" +
	"\rwork_location\x18\x05 \x01(\tR\fworkLocation\x12)\n" +
	"\x10experience_level\x18\x06 \x01(\tR\x0fexperienceLevel\x12\x10\n" +
	"\x03bio\x18\a \x01(\tR\x03bio\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\b \x01(\tR\tavatarUrl\"\x7f\n" +
	"\x19InitializeProfileResponse\x12)\n" +
	"\aprofile\x18\x01 \x01(\v2\x0f.pb.UserProfileR\aprofile\x12\x18\n" +
	"\acreated\x18\x02 \x01(\bR\acreated\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\"C\n" +
	"\x11UpdateRoleRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\"?\n" +
	"\x12UpdateRoleResponse\x12)\n" +
	"\aprofile\x18\x01 \x01(\v2\x0f.pb.UserProfileR\aprofile\"[\n" +
	"\x14SearchHuntersRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x17\n" +
	"\asort_by\x18\x03 \x01(\tR\x06sortBy\"B\n" +
	"\x15SearchHuntersResponse\x12)\n" +
	"\ahunters\x18\x01 \x03(\v2\x0f.pb.UserProfileR\ahuntersB2Z0github.com/grayfalcon666/user-profile-service/pbb\x06proto3"

var (
	file_profile_proto_rawDescOnce sync.Once
	file_profile_proto_rawDescData []byte
)

func file_profile_proto_rawDescGZIP() []byte {
	file_profile_proto_rawDescOnce.Do(func() {
		file_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_profile_proto_rawDesc), len(file_profile_proto_rawDesc)))
	})
	return file_profile_proto_rawDescData
}

var file_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_profile_proto_goTypes = []any{
	(*GetProfileRequest)(nil),           // 0: pb.GetProfileRequest
	(*GetProfileResponse)(nil),          // 1: pb.GetProfileResponse
	(*CreateProfileRequest)(nil),        // 2: pb.CreateProfileRequest
	(*CreateProfileResponse)(nil),       // 3: pb.CreateProfileResponse
	(*UpdateProfileRequest)(nil),        // 4: pb.UpdateProfileRequest
	(*UpdateProfileResponse)(nil),       // 5: pb.UpdateProfileResponse
	(*RefreshProfileStatsRequest)(nil),  // 6: pb.RefreshProfileStatsRequest
	(*RefreshProfileStatsResponse)(nil), // 7: pb.RefreshProfileStatsResponse
	(*SearchUsersRequest)(nil),          // 8: pb.SearchUsersRequest
	(*SearchUsersResponse)(nil),         // 9: pb.SearchUsersResponse
	(*UserSummary)(nil),                 // 10: pb.UserSummary
	(*InitializeProfileRequest)(nil),    // 11: pb.InitializeProfileRequest
	(*InitializeProfileResponse)(nil),   // 12: pb.InitializeProfileResponse
	(*UpdateRoleRequest)(nil),           // 13: pb.UpdateRoleRequest
	(*UpdateRoleResponse)(nil),          // 14: pb.UpdateRoleResponse
	(*SearchHuntersRequest)(nil),        // 15: pb.SearchHuntersRequest
	(*SearchHuntersResponse)(nil),       // 16: pb.SearchHuntersResponse
	(*UserProfile)(nil),                 // 17: pb.UserProfile
}
var file_profile_proto_depIdxs = []int32{
	17, // 0: pb.GetProfileResponse.profile:type_name -> pb.UserProfile
	17, // 1: pb.CreateProfileResponse.profile:type_name -> pb.UserProfile
	17, // 2: pb.UpdateProfileResponse.profile:type_name -> pb.UserProfile
	17, // 3: pb.RefreshProfileStatsResponse.profile:type_name -> pb.UserProfile
	10, // 4: pb.SearchUsersResponse.users:type_name -> pb.UserSummary
	17, // 5: pb.InitializeProfileResponse.profile:type_name -> pb.UserProfile
	17, // 6: pb.UpdateRoleResponse.profile:type_name -> pb.UserProfile
	17, // 7: pb.SearchHuntersResponse.hunters:type_name -> pb.UserProfile
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_profile_proto_init() }
func file_profile_proto_init() {
	if File_profile_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_profile_proto_rawDesc), len(file_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_profile_proto_goTypes,
		DependencyIndexes: file_profile_proto_depIdxs,
		MessageInfos:      file_profile_proto_msgTypes,
	}.Build()
	File_profile_proto = out.File
	file_profile_proto_goTypes = nil
	file_profile_proto_depIdxs = nil
}
