// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account.sql

package db

import (
	"context"
)

const addAccountBalance = `-- name: AddAccountBalance :one
UPDATE accounts
SET balance = balance + $1
WHERE id = $2
RETURNING id, owner, balance, frozen_balance, currency, created_at
`

type AddAccountBalanceParams struct {
	Amount int64 `json:"amount"`
	ID     int64 `json:"id"`
}

func (q *Queries) AddAccountBalance(ctx context.Context, arg AddAccountBalanceParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, addAccountBalance, arg.Amount, arg.ID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Balance,
		&i.FrozenBalance,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
  owner,
  balance,
  frozen_balance,
  currency
) VALUES (
  $1, $2, 0, $3
)
RETURNING id, owner, balance, frozen_balance, currency, created_at
`

type CreateAccountParams struct {
	Owner    string `json:"owner"`
	Balance  int64  `json:"balance"`
	Currency string `json:"currency"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount, arg.Owner, arg.Balance, arg.Currency)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Balance,
		&i.FrozenBalance,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts
WHERE id = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAccount, id)
	return err
}

const freezeAccount = `-- name: FreezeAccount :one
UPDATE accounts
SET balance = balance - $2,
    frozen_balance = frozen_balance + $2
WHERE id = $1 AND balance >= $2
RETURNING id, owner, balance, frozen_balance, currency, created_at
`

type FreezeAccountParams struct {
	ID      int64 `json:"id"`
	Balance int64 `json:"balance"`
}

// Freeze amount: deduct from balance and add to frozen_balance
// Fails if balance < amount (returns no rows)
func (q *Queries) FreezeAccount(ctx context.Context, arg FreezeAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, freezeAccount, arg.ID, arg.Balance)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Balance,
		&i.FrozenBalance,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, owner, balance, frozen_balance, currency, created_at FROM accounts
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAccount(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Balance,
		&i.FrozenBalance,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, owner, balance, frozen_balance, currency, created_at FROM accounts
WHERE owner = $1
ORDER BY id
LIMIT $2
OFFSET $3
`

type ListAccountsParams struct {
	Owner  string `json:"owner"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listAccounts, arg.Owner, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Balance,
			&i.FrozenBalance,
			&i.Currency,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const spendFrozenBalance = `-- name: SpendFrozenBalance :one
UPDATE accounts
SET frozen_balance = frozen_balance - $2
WHERE id = $1 AND frozen_balance >= $2
RETURNING id, owner, balance, frozen_balance, currency, created_at
`

type SpendFrozenBalanceParams struct {
	ID            int64 `json:"id"`
	FrozenBalance int64 `json:"frozen_balance"`
}

// Used for BOUNTY_PAYOUT: deduct from frozen_balance only
// (balance was already deducted during Freeze)
// Fails if frozen_balance < amount (returns no rows)
func (q *Queries) SpendFrozenBalance(ctx context.Context, arg SpendFrozenBalanceParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, spendFrozenBalance, arg.ID, arg.FrozenBalance)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Balance,
		&i.FrozenBalance,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const spendFrozenForWithdrawal = `-- name: SpendFrozenForWithdrawal :one
UPDATE accounts
SET frozen_balance = frozen_balance - $2
WHERE id = $1 AND frozen_balance >= $2
RETURNING id, owner, balance, frozen_balance, currency, created_at
`

type SpendFrozenForWithdrawalParams struct {
	ID            int64 `json:"id"`
	FrozenBalance int64 `json:"frozen_balance"`
}

// Permanently deduct from frozen_balance for withdrawal (WITHDRAWAL_OUT)
// Fails if frozen_balance < amount (returns no rows)
func (q *Queries) SpendFrozenForWithdrawal(ctx context.Context, arg SpendFrozenForWithdrawalParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, spendFrozenForWithdrawal, arg.ID, arg.FrozenBalance)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Balance,
		&i.FrozenBalance,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const unfreezeAccount = `-- name: UnfreezeAccount :one
UPDATE accounts
SET frozen_balance = frozen_balance - $2,
    balance = balance + $2
WHERE id = $1 AND frozen_balance >= $2
RETURNING id, owner, balance, frozen_balance, currency, created_at
`

type UnfreezeAccountParams struct {
	ID            int64 `json:"id"`
	FrozenBalance int64 `json:"frozen_balance"`
}

// Unfreeze amount: return from frozen_balance back to balance
// Fails if frozen_balance < amount (returns no rows)
func (q *Queries) UnfreezeAccount(ctx context.Context, arg UnfreezeAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, unfreezeAccount, arg.ID, arg.FrozenBalance)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Balance,
		&i.FrozenBalance,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts
SET balance = $2
WHERE id = $1
RETURNING id, owner, balance, frozen_balance, currency, created_at
`

type UpdateAccountParams struct {
	ID      int64 `json:"id"`
	Balance int64 `json:"balance"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, updateAccount, arg.ID, arg.Balance)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Balance,
		&i.FrozenBalance,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}
