// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_initialization.sql

package db

import (
	"context"
	"encoding/json"
)

const checkEventProcessed = `-- name: CheckEventProcessed :one
SELECT EXISTS (
    SELECT 1 FROM user_initialization_events
    WHERE request_id = $1
) as processed
`

func (q *Queries) CheckEventProcessed(ctx context.Context, requestID string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkEventProcessed, requestID)
	var processed bool
	err := row.Scan(&processed)
	return processed, err
}

const createUserAccount = `-- name: CreateUserAccount :one
INSERT INTO accounts (owner, balance, currency, created_at)
VALUES ($1, 0, $2, NOW())
RETURNING id
`

type CreateUserAccountParams struct {
	Owner    string `json:"owner"`
	Currency string `json:"currency"`
}

func (q *Queries) CreateUserAccount(ctx context.Context, arg CreateUserAccountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createUserAccount, arg.Owner, arg.Currency)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const markEventProcessed = `-- name: MarkEventProcessed :exec
INSERT INTO user_initialization_events (request_id, username, event_type, payload, created_at)
VALUES ($1, $2, $3, $4::jsonb, NOW())
ON CONFLICT (request_id) DO NOTHING
`

type MarkEventProcessedParams struct {
	RequestID string          `json:"request_id"`
	Username  string          `json:"username"`
	EventType string          `json:"event_type"`
	Payload   json.RawMessage `json:"payload"`
}

func (q *Queries) MarkEventProcessed(ctx context.Context, arg MarkEventProcessedParams) error {
	_, err := q.db.ExecContext(ctx, markEventProcessed,
		arg.RequestID,
		arg.Username,
		arg.EventType,
		arg.Payload,
	)
	return err
}

const updateUserStatus = `-- name: UpdateUserStatus :exec
UPDATE users
SET status = $1::VARCHAR,
    initialization_request_id = $2::VARCHAR,
    initialized_at = CASE WHEN $1 = 'INITIALIZED' THEN NOW() ELSE initialized_at END,
    failed_reason = $3::TEXT
WHERE username = $4
`

type UpdateUserStatusParams struct {
	Status       string `json:"status"`
	RequestID    string `json:"request_id"`
	FailedReason string `json:"failed_reason"`
	Username     string `json:"username"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateUserStatus,
		arg.Status,
		arg.RequestID,
		arg.FailedReason,
		arg.Username,
	)
	return err
}
