// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: idempotency.sql

package db

import (
	"context"
)

const createIdempotencyKey = `-- name: CreateIdempotencyKey :exec
INSERT INTO idempotency_keys (
  key
) VALUES (
  $1
)
ON CONFLICT (key) DO NOTHING
`

func (q *Queries) CreateIdempotencyKey(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, createIdempotencyKey, key)
	return err
}

const tryAcquireIdempotencyKey = `-- name: TryAcquireIdempotencyKey :one
INSERT INTO idempotency_keys (
  key
) VALUES (
  $1
)
ON CONFLICT (key) DO NOTHING
RETURNING key
`

// Returns the key if newly inserted, or nothing if already exists.
// Caller can distinguish via sql.ErrNoRows to know it was a duplicate.
func (q *Queries) TryAcquireIdempotencyKey(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, tryAcquireIdempotencyKey, key)
	err := row.Scan(&key)
	return key, err
}
