// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ledger.sql

package db

import (
	"context"
	"database/sql"
)

const createLedgerEntry = `-- name: CreateLedgerEntry :one
INSERT INTO ledger_entries (
    account_id,
    bounty_id,
    event_type,
    amount,
    counterparty,
    description
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, account_id, bounty_id, event_type, amount, counterparty, description, created_at
`

type CreateLedgerEntryParams struct {
	AccountID    int64          `json:"account_id"`
	BountyID     sql.NullInt64  `json:"bounty_id"`
	EventType    string         `json:"event_type"`
	Amount       int64          `json:"amount"`
	Counterparty sql.NullString `json:"counterparty"`
	Description  sql.NullString `json:"description"`
}

func (q *Queries) CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) (LedgerEntry, error) {
	row := q.db.QueryRowContext(ctx, createLedgerEntry,
		arg.AccountID,
		arg.BountyID,
		arg.EventType,
		arg.Amount,
		arg.Counterparty,
		arg.Description,
	)
	var i LedgerEntry
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.BountyID,
		&i.EventType,
		&i.Amount,
		&i.Counterparty,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listLedgerEntriesByAccount = `-- name: ListLedgerEntriesByAccount :many
SELECT id, account_id, bounty_id, event_type, amount, counterparty, description, created_at FROM ledger_entries
WHERE account_id = $1
ORDER BY created_at DESC
LIMIT $2
OFFSET $3
`

type ListLedgerEntriesByAccountParams struct {
	AccountID int64 `json:"account_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

func (q *Queries) ListLedgerEntriesByAccount(ctx context.Context, arg ListLedgerEntriesByAccountParams) ([]LedgerEntry, error) {
	rows, err := q.db.QueryContext(ctx, listLedgerEntriesByAccount, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerEntry{}
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.BountyID,
			&i.EventType,
			&i.Amount,
			&i.Counterparty,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerEntriesByAccountAndType = `-- name: ListLedgerEntriesByAccountAndType :many
SELECT id, account_id, bounty_id, event_type, amount, counterparty, description, created_at FROM ledger_entries
WHERE account_id = $1 AND event_type = $2
ORDER BY created_at DESC
LIMIT $3
OFFSET $4
`

type ListLedgerEntriesByAccountAndTypeParams struct {
	AccountID int64  `json:"account_id"`
	EventType string `json:"event_type"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

func (q *Queries) ListLedgerEntriesByAccountAndType(ctx context.Context, arg ListLedgerEntriesByAccountAndTypeParams) ([]LedgerEntry, error) {
	rows, err := q.db.QueryContext(ctx, listLedgerEntriesByAccountAndType,
		arg.AccountID,
		arg.EventType,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerEntry{}
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.BountyID,
			&i.EventType,
			&i.Amount,
			&i.Counterparty,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerEntriesByBounty = `-- name: ListLedgerEntriesByBounty :many
SELECT id, account_id, bounty_id, event_type, amount, counterparty, description, created_at FROM ledger_entries
WHERE bounty_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListLedgerEntriesByBounty(ctx context.Context, bountyID sql.NullInt64) ([]LedgerEntry, error) {
	rows, err := q.db.QueryContext(ctx, listLedgerEntriesByBounty, bountyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerEntry{}
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.BountyID,
			&i.EventType,
			&i.Amount,
			&i.Counterparty,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
