// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID            int64     `json:"id"`
	Owner         string    `json:"owner"`
	Balance       int64     `json:"balance"`
	FrozenBalance int64     `json:"frozen_balance"`
	Currency      string    `json:"currency"`
	CreatedAt     time.Time `json:"created_at"`
}

type Entry struct {
	ID        int64     `json:"id"`
	AccountID int64     `json:"account_id"`
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}

type IdempotencyKey struct {
	Key       string    `json:"key"`
	CreatedAt time.Time `json:"created_at"`
}

type LedgerEntry struct {
	ID           uuid.UUID      `json:"id"`
	AccountID    int64          `json:"account_id"`
	BountyID     sql.NullInt64  `json:"bounty_id"`
	EventType    string         `json:"event_type"`
	Amount       int64          `json:"amount"`
	Counterparty sql.NullString `json:"counterparty"`
	Description  sql.NullString `json:"description"`
	CreatedAt    sql.NullTime   `json:"created_at"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type Transfer struct {
	ID            int64          `json:"id"`
	FromAccountID int64          `json:"from_account_id"`
	ToAccountID   int64          `json:"to_account_id"`
	Amount        int64          `json:"amount"`
	TradeType     string         `json:"trade_type"`
	TradeID       sql.NullInt64  `json:"trade_id"`
	Description   sql.NullString `json:"description"`
	CreatedAt     time.Time      `json:"created_at"`
}

type User struct {
	Username          string    `json:"username"`
	HashedPassword    string    `json:"hashed_password"`
	FullName          string    `json:"full_name"`
	Email             string    `json:"email"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
	IsEmailVerified   bool      `json:"is_email_verified"`
}

type UserInitializationEvent struct {
	RequestID   string          `json:"request_id"`
	Username    string          `json:"username"`
	EventType   string          `json:"event_type"`
	Payload     json.RawMessage `json:"payload"`
	CreatedAt   sql.NullTime    `json:"created_at"`
	ProcessedAt sql.NullTime    `json:"processed_at"`
}

type VerifyEmail struct {
	ID         int64     `json:"id"`
	Username   string    `json:"username"`
	Email      string    `json:"email"`
	SecretCode string    `json:"secret_code"`
	IsUsed     bool      `json:"is_used"`
	CreatedAt  time.Time `json:"created_at"`
	ExpiredAt  time.Time `json:"expired_at"`
}
