// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	AddAccountBalance(ctx context.Context, arg AddAccountBalanceParams) (Account, error)
	CheckEventProcessed(ctx context.Context, requestID string) (bool, error)
	CountAccountTransfers(ctx context.Context, fromAccountID int64) (int64, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	CreateIdempotencyKey(ctx context.Context, key string) error
	CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) (LedgerEntry, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserAccount(ctx context.Context, arg CreateUserAccountParams) (int64, error)
	CreateVerifyEmail(ctx context.Context, arg CreateVerifyEmailParams) (VerifyEmail, error)
	DeleteAccount(ctx context.Context, id int64) error
	DeleteTransfer(ctx context.Context, id int64) error
	// Freeze amount: deduct from balance and add to frozen_balance
	// Fails if balance < amount (returns no rows)
	FreezeAccount(ctx context.Context, arg FreezeAccountParams) (Account, error)
	GetAccount(ctx context.Context, id int64) (Account, error)
	GetEntry(ctx context.Context, id int64) (Entry, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetTransfer(ctx context.Context, id int64) (Transfer, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListAccountTransfers(ctx context.Context, arg ListAccountTransfersParams) ([]ListAccountTransfersRow, error)
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error)
	ListEntries(ctx context.Context, arg ListEntriesParams) ([]Entry, error)
	ListEntriesByAccountID(ctx context.Context, arg ListEntriesByAccountIDParams) ([]Entry, error)
	ListLedgerEntriesByAccount(ctx context.Context, arg ListLedgerEntriesByAccountParams) ([]LedgerEntry, error)
	ListLedgerEntriesByAccountAndType(ctx context.Context, arg ListLedgerEntriesByAccountAndTypeParams) ([]LedgerEntry, error)
	ListLedgerEntriesByBounty(ctx context.Context, bountyID sql.NullInt64) ([]LedgerEntry, error)
	ListTransfers(ctx context.Context, arg ListTransfersParams) ([]Transfer, error)
	ListTransfersByFromAccount(ctx context.Context, arg ListTransfersByFromAccountParams) ([]Transfer, error)
	ListTransfersByToAccount(ctx context.Context, arg ListTransfersByToAccountParams) ([]Transfer, error)
	MarkEventProcessed(ctx context.Context, arg MarkEventProcessedParams) error
	// Used for BOUNTY_PAYOUT: deduct from frozen_balance only
	// (balance was already deducted during Freeze)
	// Fails if frozen_balance < amount (returns no rows)
	SpendFrozenBalance(ctx context.Context, arg SpendFrozenBalanceParams) (Account, error)
	// Permanently deduct from frozen_balance for withdrawal (WITHDRAWAL_OUT)
	// Fails if frozen_balance < amount (returns no rows)
	SpendFrozenForWithdrawal(ctx context.Context, arg SpendFrozenForWithdrawalParams) (Account, error)
	// Returns the key if newly inserted, or nothing if already exists.
	// Caller can distinguish via sql.ErrNoRows to know it was a duplicate.
	TryAcquireIdempotencyKey(ctx context.Context, key string) (string, error)
	// Unfreeze amount: return from frozen_balance back to balance
	// Fails if frozen_balance < amount (returns no rows)
	UnfreezeAccount(ctx context.Context, arg UnfreezeAccountParams) (Account, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateTransfer(ctx context.Context, arg UpdateTransferParams) (Transfer, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error
	UpdateVerifyEmail(ctx context.Context, arg UpdateVerifyEmailParams) (VerifyEmail, error)
}

var _ Querier = (*Queries)(nil)
