// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: service_simple_bank.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_simple_bank_proto protoreflect.FileDescriptor

const file_service_simple_bank_proto_rawDesc = "" +
	"\n" +
	"\x19service_simple_bank.proto\x12\x02pb\x1a\x1cgoogle/api/annotations.proto\x1a\x15rpc_create_user.proto\x1a\x14rpc_login_user.proto\x1a\x16rpc_verify_email.proto\x1a\x15rpc_update_user.proto\x1a\x15rpc_transfer_tx.proto\x1a\x18rpc_create_account.proto\x1a\x15rpc_get_account.proto\x1a\x17rpc_list_accounts.proto\x1a\x18rpc_list_transfers.proto\x1a\x10rpc_bounty.proto2\x83\b\n" +
	"\n" +
	"SimpleBank\x12W\n" +
	"\n" +
	"CreateUser\x12\x15.pb.CreateUserRequest\x1a\x16.pb.CreateUserResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/create_user\x12c\n" +
	"\rCreateAccount\x12\x18.pb.CreateAccountRequest\x1a\x19.pb.CreateAccountResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/create_account\x12S\n" +
	"\tLoginUser\x12\x14.pb.LoginUserRequest\x1a\x15.pb.LoginUserResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/login_user\x12X\n" +
	"\vVerifyEmail\x12\x16.pb.VerifyEmailRequest\x1a\x17.pb.VerifyEmailResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/verify_email\x12W\n" +
	"\n" +
	"UpdateUser\x12\x15.pb.UpdateUserRequest\x1a\x16.pb.UpdateUserResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/update_user\x12S\n" +
	"\bTransfer\x12\x15.pb.TransferTxRequest\x1a\x16.pb.TransferTxResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/transfers\x12=\n" +
	"\n" +
	"GetAccount\x12\x15.pb.GetAccountRequest\x1a\x16.pb.GetAccountResponse\"\x00\x12W\n" +
	"\fListAccounts\x12\x17.pb.ListAccountsRequest\x1a\x18.pb.ListAccountsResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/accounts\x12[\n" +
	"\rListTransfers\x12\x18.pb.ListTransfersRequest\x1a\x19.pb.ListTransfersResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/transfers\x121\n" +
	"\x06Freeze\x12\x11.pb.FreezeRequest\x1a\x12.pb.FreezeResponse\"\x00\x127\n" +
	"\bUnfreeze\x12\x13.pb.UnfreezeRequest\x1a\x14.pb.UnfreezeResponse\"\x00\x12C\n" +
	"\fBountyPayout\x12\x17.pb.BountyPayoutRequest\x1a\x18.pb.BountyPayoutResponse\"\x00\x124\n" +
	"\aDeposit\x12\x12.pb.DepositRequest\x1a\x13.pb.DepositResponse\"\x00B\x0fZ\rsimplebank/pbb\x06proto3"

var file_service_simple_bank_proto_goTypes = []any{
	(*CreateUserRequest)(nil),     // 0: pb.CreateUserRequest
	(*CreateAccountRequest)(nil),  // 1: pb.CreateAccountRequest
	(*LoginUserRequest)(nil),      // 2: pb.LoginUserRequest
	(*VerifyEmailRequest)(nil),    // 3: pb.VerifyEmailRequest
	(*UpdateUserRequest)(nil),     // 4: pb.UpdateUserRequest
	(*TransferTxRequest)(nil),     // 5: pb.TransferTxRequest
	(*GetAccountRequest)(nil),     // 6: pb.GetAccountRequest
	(*ListAccountsRequest)(nil),   // 7: pb.ListAccountsRequest
	(*ListTransfersRequest)(nil),  // 8: pb.ListTransfersRequest
	(*FreezeRequest)(nil),         // 9: pb.FreezeRequest
	(*UnfreezeRequest)(nil),       // 10: pb.UnfreezeRequest
	(*BountyPayoutRequest)(nil),   // 11: pb.BountyPayoutRequest
	(*DepositRequest)(nil),        // 12: pb.DepositRequest
	(*CreateUserResponse)(nil),    // 13: pb.CreateUserResponse
	(*CreateAccountResponse)(nil), // 14: pb.CreateAccountResponse
	(*LoginUserResponse)(nil),     // 15: pb.LoginUserResponse
	(*VerifyEmailResponse)(nil),   // 16: pb.VerifyEmailResponse
	(*UpdateUserResponse)(nil),    // 17: pb.UpdateUserResponse
	(*TransferTxResponse)(nil),    // 18: pb.TransferTxResponse
	(*GetAccountResponse)(nil),    // 19: pb.GetAccountResponse
	(*ListAccountsResponse)(nil),  // 20: pb.ListAccountsResponse
	(*ListTransfersResponse)(nil), // 21: pb.ListTransfersResponse
	(*FreezeResponse)(nil),        // 22: pb.FreezeResponse
	(*UnfreezeResponse)(nil),      // 23: pb.UnfreezeResponse
	(*BountyPayoutResponse)(nil),  // 24: pb.BountyPayoutResponse
	(*DepositResponse)(nil),       // 25: pb.DepositResponse
}
var file_service_simple_bank_proto_depIdxs = []int32{
	0,  // 0: pb.SimpleBank.CreateUser:input_type -> pb.CreateUserRequest
	1,  // 1: pb.SimpleBank.CreateAccount:input_type -> pb.CreateAccountRequest
	2,  // 2: pb.SimpleBank.LoginUser:input_type -> pb.LoginUserRequest
	3,  // 3: pb.SimpleBank.VerifyEmail:input_type -> pb.VerifyEmailRequest
	4,  // 4: pb.SimpleBank.UpdateUser:input_type -> pb.UpdateUserRequest
	5,  // 5: pb.SimpleBank.Transfer:input_type -> pb.TransferTxRequest
	6,  // 6: pb.SimpleBank.GetAccount:input_type -> pb.GetAccountRequest
	7,  // 7: pb.SimpleBank.ListAccounts:input_type -> pb.ListAccountsRequest
	8,  // 8: pb.SimpleBank.ListTransfers:input_type -> pb.ListTransfersRequest
	9,  // 9: pb.SimpleBank.Freeze:input_type -> pb.FreezeRequest
	10, // 10: pb.SimpleBank.Unfreeze:input_type -> pb.UnfreezeRequest
	11, // 11: pb.SimpleBank.BountyPayout:input_type -> pb.BountyPayoutRequest
	12, // 12: pb.SimpleBank.Deposit:input_type -> pb.DepositRequest
	13, // 13: pb.SimpleBank.CreateUser:output_type -> pb.CreateUserResponse
	14, // 14: pb.SimpleBank.CreateAccount:output_type -> pb.CreateAccountResponse
	15, // 15: pb.SimpleBank.LoginUser:output_type -> pb.LoginUserResponse
	16, // 16: pb.SimpleBank.VerifyEmail:output_type -> pb.VerifyEmailResponse
	17, // 17: pb.SimpleBank.UpdateUser:output_type -> pb.UpdateUserResponse
	18, // 18: pb.SimpleBank.Transfer:output_type -> pb.TransferTxResponse
	19, // 19: pb.SimpleBank.GetAccount:output_type -> pb.GetAccountResponse
	20, // 20: pb.SimpleBank.ListAccounts:output_type -> pb.ListAccountsResponse
	21, // 21: pb.SimpleBank.ListTransfers:output_type -> pb.ListTransfersResponse
	22, // 22: pb.SimpleBank.Freeze:output_type -> pb.FreezeResponse
	23, // 23: pb.SimpleBank.Unfreeze:output_type -> pb.UnfreezeResponse
	24, // 24: pb.SimpleBank.BountyPayout:output_type -> pb.BountyPayoutResponse
	25, // 25: pb.SimpleBank.Deposit:output_type -> pb.DepositResponse
	13, // [13:26] is the sub-list for method output_type
	0,  // [0:13] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_service_simple_bank_proto_init() }
func file_service_simple_bank_proto_init() {
	if File_service_simple_bank_proto != nil {
		return
	}
	file_rpc_create_user_proto_init()
	file_rpc_login_user_proto_init()
	file_rpc_verify_email_proto_init()
	file_rpc_update_user_proto_init()
	file_rpc_transfer_tx_proto_init()
	file_rpc_create_account_proto_init()
	file_rpc_get_account_proto_init()
	file_rpc_list_accounts_proto_init()
	file_rpc_list_transfers_proto_init()
	file_rpc_bounty_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_simple_bank_proto_rawDesc), len(file_service_simple_bank_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_simple_bank_proto_goTypes,
		DependencyIndexes: file_service_simple_bank_proto_depIdxs,
	}.Build()
	File_service_simple_bank_proto = out.File
	file_service_simple_bank_proto_goTypes = nil
	file_service_simple_bank_proto_depIdxs = nil
}
