ALTER TABLE user_profiles
    ADD COLUMN IF NOT EXISTS fulfillment_index INTEGER DEFAULT 50,
    ADD COLUMN IF NOT EXISTS cooling_lambda DOUBLE PRECISION DEFAULT 0.1,
    ADD COLUMN IF NOT EXISTS task_window_size INTEGER DEFAULT 50,
    ADD COLUMN IF NOT EXISTS version INTEGER DEFAULT 1;
