// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: bounty.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 悬赏相关请求/响应
type CreateBountyRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Title             string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description       string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	RewardAmount      int64                  `protobuf:"varint,3,opt,name=reward_amount,json=rewardAmount,proto3" json:"reward_amount,omitempty"`
	EmployerAccountId int64                  `protobuf:"varint,4,opt,name=employer_account_id,json=employerAccountId,proto3" json:"employer_account_id,omitempty"`
	EmployerUsername  string                 `protobuf:"bytes,5,opt,name=employer_username,json=employerUsername,proto3" json:"employer_username,omitempty"`     // 可选；未提供则从 JWT token 中获取
	DeadlineTimestamp int64                  `protobuf:"varint,6,opt,name=deadline_timestamp,json=deadlineTimestamp,proto3" json:"deadline_timestamp,omitempty"` // 截止时间（秒），可选
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateBountyRequest) Reset() {
	*x = CreateBountyRequest{}
	mi := &file_bounty_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBountyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBountyRequest) ProtoMessage() {}

func (x *CreateBountyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bounty_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBountyRequest.ProtoReflect.Descriptor instead.
func (*CreateBountyRequest) Descriptor() ([]byte, []int) {
	return file_bounty_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBountyRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateBountyRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateBountyRequest) GetRewardAmount() int64 {
	if x != nil {
		return x.RewardAmount
	}
	return 0
}

func (x *CreateBountyRequest) GetEmployerAccountId() int64 {
	if x != nil {
		return x.EmployerAccountId
	}
	return 0
}

func (x *CreateBountyRequest) GetEmployerUsername() string {
	if x != nil {
		return x.EmployerUsername
	}
	return ""
}

func (x *CreateBountyRequest) GetDeadlineTimestamp() int64 {
	if x != nil {
		return x.DeadlineTimestamp
	}
	return 0
}

type CreateBountyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bounty        *Bounty                `protobuf:"bytes,1,opt,name=bounty,proto3" json:"bounty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBountyResponse) Reset() {
	*x = CreateBountyResponse{}
	mi := &file_bounty_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBountyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBountyResponse) ProtoMessage() {}

func (x *CreateBountyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bounty_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBountyResponse.ProtoReflect.Descriptor instead.
func (*CreateBountyResponse) Descriptor() ([]byte, []int) {
	return file_bounty_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBountyResponse) GetBounty() *Bounty {
	if x != nil {
		return x.Bounty
	}
	return nil
}

type ListBountiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	PageId        int32                  `protobuf:"varint,2,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBountiesRequest) Reset() {
	*x = ListBountiesRequest{}
	mi := &file_bounty_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBountiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBountiesRequest) ProtoMessage() {}

func (x *ListBountiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bounty_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBountiesRequest.ProtoReflect.Descriptor instead.
func (*ListBountiesRequest) Descriptor() ([]byte, []int) {
	return file_bounty_proto_rawDescGZIP(), []int{2}
}

func (x *ListBountiesRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListBountiesRequest) GetPageId() int32 {
	if x != nil {
		return x.PageId
	}
	return 0
}

func (x *ListBountiesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListBountiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bounties      []*Bounty              `protobuf:"bytes,1,rep,name=bounties,proto3" json:"bounties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBountiesResponse) Reset() {
	*x = ListBountiesResponse{}
	mi := &file_bounty_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBountiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBountiesResponse) ProtoMessage() {}

func (x *ListBountiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bounty_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBountiesResponse.ProtoReflect.Descriptor instead.
func (*ListBountiesResponse) Descriptor() ([]byte, []int) {
	return file_bounty_proto_rawDescGZIP(), []int{3}
}

func (x *ListBountiesResponse) GetBounties() []*Bounty {
	if x != nil {
		return x.Bounties
	}
	return nil
}

type GetBountyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBountyRequest) Reset() {
	*x = GetBountyRequest{}
	mi := &file_bounty_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBountyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBountyRequest) ProtoMessage() {}

func (x *GetBountyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bounty_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBountyRequest.ProtoReflect.Descriptor instead.
func (*GetBountyRequest) Descriptor() ([]byte, []int) {
	return file_bounty_proto_rawDescGZIP(), []int{4}
}

func (x *GetBountyRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetBountyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bounty        *Bounty                `protobuf:"bytes,1,opt,name=bounty,proto3" json:"bounty,omitempty"`
	Applications  []*BountyApplication   `protobuf:"bytes,2,rep,name=applications,proto3" json:"applications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBountyResponse) Reset() {
	*x = GetBountyResponse{}
	mi := &file_bounty_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBountyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBountyResponse) ProtoMessage() {}

func (x *GetBountyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bounty_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBountyResponse.ProtoReflect.Descriptor instead.
func (*GetBountyResponse) Descriptor() ([]byte, []int) {
	return file_bounty_proto_rawDescGZIP(), []int{5}
}

func (x *GetBountyResponse) GetBounty() *Bounty {
	if x != nil {
		return x.Bounty
	}
	return nil
}

func (x *GetBountyResponse) GetApplications() []*BountyApplication {
	if x != nil {
		return x.Applications
	}
	return nil
}

type DeleteBountyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BountyId      int64                  `protobuf:"varint,1,opt,name=bounty_id,json=bountyId,proto3" json:"bounty_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBountyRequest) Reset() {
	*x = DeleteBountyRequest{}
	mi := &file_bounty_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBountyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBountyRequest) ProtoMessage() {}

func (x *DeleteBountyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bounty_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBountyRequest.ProtoReflect.Descriptor instead.
func (*DeleteBountyRequest) Descriptor() ([]byte, []int) {
	return file_bounty_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteBountyRequest) GetBountyId() int64 {
	if x != nil {
		return x.BountyId
	}
	return 0
}

type DeleteBountyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBountyResponse) Reset() {
	*x = DeleteBountyResponse{}
	mi := &file_bounty_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBountyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBountyResponse) ProtoMessage() {}

func (x *DeleteBountyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bounty_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBountyResponse.ProtoReflect.Descriptor instead.
func (*DeleteBountyResponse) Descriptor() ([]byte, []int) {
	return file_bounty_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteBountyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 猎人提交工作成果
type SubmitBountyRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BountyId       int64                  `protobuf:"varint,1,opt,name=bounty_id,json=bountyId,proto3" json:"bounty_id,omitempty"`
	SubmissionText string                 `protobuf:"bytes,2,opt,name=submission_text,json=submissionText,proto3" json:"submission_text,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubmitBountyRequest) Reset() {
	*x = SubmitBountyRequest{}
	mi := &file_bounty_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitBountyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitBountyRequest) ProtoMessage() {}

func (x *SubmitBountyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bounty_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitBountyRequest.ProtoReflect.Descriptor instead.
func (*SubmitBountyRequest) Descriptor() ([]byte, []int) {
	return file_bounty_proto_rawDescGZIP(), []int{8}
}

func (x *SubmitBountyRequest) GetBountyId() int64 {
	if x != nil {
		return x.BountyId
	}
	return 0
}

func (x *SubmitBountyRequest) GetSubmissionText() string {
	if x != nil {
		return x.SubmissionText
	}
	return ""
}

type SubmitBountyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bounty        *Bounty                `protobuf:"bytes,1,opt,name=bounty,proto3" json:"bounty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitBountyResponse) Reset() {
	*x = SubmitBountyResponse{}
	mi := &file_bounty_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitBountyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitBountyResponse) ProtoMessage() {}

func (x *SubmitBountyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bounty_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitBountyResponse.ProtoReflect.Descriptor instead.
func (*SubmitBountyResponse) Descriptor() ([]byte, []int) {
	return file_bounty_proto_rawDescGZIP(), []int{9}
}

func (x *SubmitBountyResponse) GetBounty() *Bounty {
	if x != nil {
		return x.Bounty
	}
	return nil
}

// 雇主审核通过
type ApproveBountyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BountyId      int64                  `protobuf:"varint,1,opt,name=bounty_id,json=bountyId,proto3" json:"bounty_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveBountyRequest) Reset() {
	*x = ApproveBountyRequest{}
	mi := &file_bounty_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveBountyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveBountyRequest) ProtoMessage() {}

func (x *ApproveBountyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bounty_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveBountyRequest.ProtoReflect.Descriptor instead.
func (*ApproveBountyRequest) Descriptor() ([]byte, []int) {
	return file_bounty_proto_rawDescGZIP(), []int{10}
}

func (x *ApproveBountyRequest) GetBountyId() int64 {
	if x != nil {
		return x.BountyId
	}
	return 0
}

type ApproveBountyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bounty        *Bounty                `protobuf:"bytes,1,opt,name=bounty,proto3" json:"bounty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveBountyResponse) Reset() {
	*x = ApproveBountyResponse{}
	mi := &file_bounty_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveBountyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveBountyResponse) ProtoMessage() {}

func (x *ApproveBountyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bounty_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveBountyResponse.ProtoReflect.Descriptor instead.
func (*ApproveBountyResponse) Descriptor() ([]byte, []int) {
	return file_bounty_proto_rawDescGZIP(), []int{11}
}

func (x *ApproveBountyResponse) GetBounty() *Bounty {
	if x != nil {
		return x.Bounty
	}
	return nil
}

// 雇主审核拒绝
type RejectBountyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BountyId      int64                  `protobuf:"varint,1,opt,name=bounty_id,json=bountyId,proto3" json:"bounty_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectBountyRequest) Reset() {
	*x = RejectBountyRequest{}
	mi := &file_bounty_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectBountyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectBountyRequest) ProtoMessage() {}

func (x *RejectBountyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bounty_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectBountyRequest.ProtoReflect.Descriptor instead.
func (*RejectBountyRequest) Descriptor() ([]byte, []int) {
	return file_bounty_proto_rawDescGZIP(), []int{12}
}

func (x *RejectBountyRequest) GetBountyId() int64 {
	if x != nil {
		return x.BountyId
	}
	return 0
}

type RejectBountyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bounty        *Bounty                `protobuf:"bytes,1,opt,name=bounty,proto3" json:"bounty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectBountyResponse) Reset() {
	*x = RejectBountyResponse{}
	mi := &file_bounty_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectBountyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectBountyResponse) ProtoMessage() {}

func (x *RejectBountyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bounty_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectBountyResponse.ProtoReflect.Descriptor instead.
func (*RejectBountyResponse) Descriptor() ([]byte, []int) {
	return file_bounty_proto_rawDescGZIP(), []int{13}
}

func (x *RejectBountyResponse) GetBounty() *Bounty {
	if x != nil {
		return x.Bounty
	}
	return nil
}

type Invitation struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BountyId       int64                  `protobuf:"varint,2,opt,name=bounty_id,json=bountyId,proto3" json:"bounty_id,omitempty"`
	PosterUsername string                 `protobuf:"bytes,3,opt,name=poster_username,json=posterUsername,proto3" json:"poster_username,omitempty"`
	HunterUsername string                 `protobuf:"bytes,4,opt,name=hunter_username,json=hunterUsername,proto3" json:"hunter_username,omitempty"`
	Status         string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`                         // PENDING | ACCEPTED | DECLINED
	CreatedAt      int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // 秒级时间戳
	UpdatedAt      int64                  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// 关联悬赏信息（响应中附加）
	Bounty        *Bounty `protobuf:"bytes,8,opt,name=bounty,proto3" json:"bounty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Invitation) Reset() {
	*x = Invitation{}
	mi := &file_bounty_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invitation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invitation) ProtoMessage() {}

func (x *Invitation) ProtoReflect() protoreflect.Message {
	mi := &file_bounty_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invitation.ProtoReflect.Descriptor instead.
func (*Invitation) Descriptor() ([]byte, []int) {
	return file_bounty_proto_rawDescGZIP(), []int{14}
}

func (x *Invitation) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Invitation) GetBountyId() int64 {
	if x != nil {
		return x.BountyId
	}
	return 0
}

func (x *Invitation) GetPosterUsername() string {
	if x != nil {
		return x.PosterUsername
	}
	return ""
}

func (x *Invitation) GetHunterUsername() string {
	if x != nil {
		return x.HunterUsername
	}
	return ""
}

func (x *Invitation) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Invitation) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Invitation) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Invitation) GetBounty() *Bounty {
	if x != nil {
		return x.Bounty
	}
	return nil
}

// 雇主创建邀请
type CreateInvitationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BountyId       int64                  `protobuf:"varint,1,opt,name=bounty_id,json=bountyId,proto3" json:"bounty_id,omitempty"`
	HunterUsername string                 `protobuf:"bytes,2,opt,name=hunter_username,json=hunterUsername,proto3" json:"hunter_username,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateInvitationRequest) Reset() {
	*x = CreateInvitationRequest{}
	mi := &file_bounty_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInvitationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInvitationRequest) ProtoMessage() {}

func (x *CreateInvitationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bounty_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInvitationRequest.ProtoReflect.Descriptor instead.
func (*CreateInvitationRequest) Descriptor() ([]byte, []int) {
	return file_bounty_proto_rawDescGZIP(), []int{15}
}

func (x *CreateInvitationRequest) GetBountyId() int64 {
	if x != nil {
		return x.BountyId
	}
	return 0
}

func (x *CreateInvitationRequest) GetHunterUsername() string {
	if x != nil {
		return x.HunterUsername
	}
	return ""
}

type CreateInvitationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invitation    *Invitation            `protobuf:"bytes,1,opt,name=invitation,proto3" json:"invitation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInvitationResponse) Reset() {
	*x = CreateInvitationResponse{}
	mi := &file_bounty_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInvitationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInvitationResponse) ProtoMessage() {}

func (x *CreateInvitationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bounty_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInvitationResponse.ProtoReflect.Descriptor instead.
func (*CreateInvitationResponse) Descriptor() ([]byte, []int) {
	return file_bounty_proto_rawDescGZIP(), []int{16}
}

func (x *CreateInvitationResponse) GetInvitation() *Invitation {
	if x != nil {
		return x.Invitation
	}
	return nil
}

// 获取我收到的邀请（猎人视角）
type GetMyInvitationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // 可选：PENDING | ACCEPTED | DECLINED
	PageId        int32                  `protobuf:"varint,2,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyInvitationsRequest) Reset() {
	*x = GetMyInvitationsRequest{}
	mi := &file_bounty_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyInvitationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyInvitationsRequest) ProtoMessage() {}

func (x *GetMyInvitationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bounty_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyInvitationsRequest.ProtoReflect.Descriptor instead.
func (*GetMyInvitationsRequest) Descriptor() ([]byte, []int) {
	return file_bounty_proto_rawDescGZIP(), []int{17}
}

func (x *GetMyInvitationsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetMyInvitationsRequest) GetPageId() int32 {
	if x != nil {
		return x.PageId
	}
	return 0
}

func (x *GetMyInvitationsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetMyInvitationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invitations   []*Invitation          `protobuf:"bytes,1,rep,name=invitations,proto3" json:"invitations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyInvitationsResponse) Reset() {
	*x = GetMyInvitationsResponse{}
	mi := &file_bounty_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyInvitationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyInvitationsResponse) ProtoMessage() {}

func (x *GetMyInvitationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bounty_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyInvitationsResponse.ProtoReflect.Descriptor instead.
func (*GetMyInvitationsResponse) Descriptor() ([]byte, []int) {
	return file_bounty_proto_rawDescGZIP(), []int{18}
}

func (x *GetMyInvitationsResponse) GetInvitations() []*Invitation {
	if x != nil {
		return x.Invitations
	}
	return nil
}

// 猎人响应邀请（接受/拒绝）
type RespondToInvitationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvitationId  int64                  `protobuf:"varint,1,opt,name=invitation_id,json=invitationId,proto3" json:"invitation_id,omitempty"`
	Accept        bool                   `protobuf:"varint,2,opt,name=accept,proto3" json:"accept,omitempty"` // true = 接受，false = 拒绝
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespondToInvitationRequest) Reset() {
	*x = RespondToInvitationRequest{}
	mi := &file_bounty_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondToInvitationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondToInvitationRequest) ProtoMessage() {}

func (x *RespondToInvitationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bounty_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondToInvitationRequest.ProtoReflect.Descriptor instead.
func (*RespondToInvitationRequest) Descriptor() ([]byte, []int) {
	return file_bounty_proto_rawDescGZIP(), []int{19}
}

func (x *RespondToInvitationRequest) GetInvitationId() int64 {
	if x != nil {
		return x.InvitationId
	}
	return 0
}

func (x *RespondToInvitationRequest) GetAccept() bool {
	if x != nil {
		return x.Accept
	}
	return false
}

type RespondToInvitationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invitation    *Invitation            `protobuf:"bytes,1,opt,name=invitation,proto3" json:"invitation,omitempty"`
	Bounty        *Bounty                `protobuf:"bytes,2,opt,name=bounty,proto3" json:"bounty,omitempty"` // 如果接受，附加悬赏信息用于跳转到详情
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespondToInvitationResponse) Reset() {
	*x = RespondToInvitationResponse{}
	mi := &file_bounty_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondToInvitationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondToInvitationResponse) ProtoMessage() {}

func (x *RespondToInvitationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bounty_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondToInvitationResponse.ProtoReflect.Descriptor instead.
func (*RespondToInvitationResponse) Descriptor() ([]byte, []int) {
	return file_bounty_proto_rawDescGZIP(), []int{20}
}

func (x *RespondToInvitationResponse) GetInvitation() *Invitation {
	if x != nil {
		return x.Invitation
	}
	return nil
}

func (x *RespondToInvitationResponse) GetBounty() *Bounty {
	if x != nil {
		return x.Bounty
	}
	return nil
}

// 雇主查看自己发出的邀请
type GetMySentInvitationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BountyId      int64                  `protobuf:"varint,1,opt,name=bounty_id,json=bountyId,proto3" json:"bounty_id,omitempty"` // 可选：筛选特定悬赏的邀请
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMySentInvitationsRequest) Reset() {
	*x = GetMySentInvitationsRequest{}
	mi := &file_bounty_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMySentInvitationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMySentInvitationsRequest) ProtoMessage() {}

func (x *GetMySentInvitationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bounty_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMySentInvitationsRequest.ProtoReflect.Descriptor instead.
func (*GetMySentInvitationsRequest) Descriptor() ([]byte, []int) {
	return file_bounty_proto_rawDescGZIP(), []int{21}
}

func (x *GetMySentInvitationsRequest) GetBountyId() int64 {
	if x != nil {
		return x.BountyId
	}
	return 0
}

func (x *GetMySentInvitationsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetMySentInvitationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invitations   []*Invitation          `protobuf:"bytes,1,rep,name=invitations,proto3" json:"invitations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMySentInvitationsResponse) Reset() {
	*x = GetMySentInvitationsResponse{}
	mi := &file_bounty_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMySentInvitationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMySentInvitationsResponse) ProtoMessage() {}

func (x *GetMySentInvitationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bounty_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMySentInvitationsResponse.ProtoReflect.Descriptor instead.
func (*GetMySentInvitationsResponse) Descriptor() ([]byte, []int) {
	return file_bounty_proto_rawDescGZIP(), []int{22}
}

func (x *GetMySentInvitationsResponse) GetInvitations() []*Invitation {
	if x != nil {
		return x.Invitations
	}
	return nil
}

var File_bounty_proto protoreflect.FileDescriptor

const file_bounty_proto_rawDesc = "" +
	"\n" +
	"\fbounty.proto\x12\x02pb\x1a\fcommon.proto\"\xfe\x01\n" +
	"\x13CreateBountyRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12#\n" +
	"\rreward_amount\x18\x03 \x01(\x03R\frewardAmount\x12.\n" +
	"\x13employer_account_id\x18\x04 \x01(\x03R\x11employerAccountId\x12+\n" +
	"\x11employer_username\x18\x05 \x01(\tR\x10employerUsername\x12-\n" +
	"\x12deadline_timestamp\x18\x06 \x01(\x03R\x11deadlineTimestamp\":\n" +
	"\x14CreateBountyResponse\x12\"\n" +
	"\x06bounty\x18\x01 \x01(\v2\n" +
	".pb.BountyR\x06bounty\"c\n" +
	"\x13ListBountiesRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x17\n" +
	"\apage_id\x18\x02 \x01(\x05R\x06pageId\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\">\n" +
	"\x14ListBountiesResponse\x12&\n" +
	"\bbounties\x18\x01 \x03(\v2\n" +
	".pb.BountyR\bbounties\"\"\n" +
	"\x10GetBountyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"r\n" +
	"\x11GetBountyResponse\x12\"\n" +
	"\x06bounty\x18\x01 \x01(\v2\n" +
	".pb.BountyR\x06bounty\x129\n" +
	"\fapplications\x18\x02 \x03(\v2\x15.pb.BountyApplicationR\fapplications\"2\n" +
	"\x13DeleteBountyRequest\x12\x1b\n" +
	"\tbounty_id\x18\x01 \x01(\x03R\bbountyId\"0\n" +
	"\x14DeleteBountyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"[\n" +
	"\x13SubmitBountyRequest\x12\x1b\n" +
	"\tbounty_id\x18\x01 \x01(\x03R\bbountyId\x12'\n" +
	"\x0fsubmission_text\x18\x02 \x01(\tR\x0esubmissionText\":\n" +
	"\x14SubmitBountyResponse\x12\"\n" +
	"\x06bounty\x18\x01 \x01(\v2\n" +
	".pb.BountyR\x06bounty\"3\n" +
	"\x14ApproveBountyRequest\x12\x1b\n" +
	"\tbounty_id\x18\x01 \x01(\x03R\bbountyId\";\n" +
	"\x15ApproveBountyResponse\x12\"\n" +
	"\x06bounty\x18\x01 \x01(\v2\n" +
	".pb.BountyR\x06bounty\"2\n" +
	"\x13RejectBountyRequest\x12\x1b\n" +
	"\tbounty_id\x18\x01 \x01(\x03R\bbountyId\":\n" +
	"\x14RejectBountyResponse\x12\"\n" +
	"\x06bounty\x18\x01 \x01(\v2\n" +
	".pb.BountyR\x06bounty\"\x85\x02\n" +
	"\n" +
	"Invitation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tbounty_id\x18\x02 \x01(\x03R\bbountyId\x12'\n" +
	"\x0fposter_username\x18\x03 \x01(\tR\x0eposterUsername\x12'\n" +
	"\x0fhunter_username\x18\x04 \x01(\tR\x0ehunterUsername\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAt\x12\"\n" +
	"\x06bounty\x18\b \x01(\v2\n" +
	".pb.BountyR\x06bounty\"_\n" +
	"\x17CreateInvitationRequest\x12\x1b\n" +
	"\tbounty_id\x18\x01 \x01(\x03R\bbountyId\x12'\n" +
	"\x0fhunter_username\x18\x02 \x01(\tR\x0ehunterUsername\"J\n" +
	"\x18CreateInvitationResponse\x12.\n" +
	"\n" +
	"invitation\x18\x01 \x01(\v2\x0e.pb.InvitationR\n" +
	"invitation\"g\n" +
	"\x17GetMyInvitationsRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x17\n" +
	"\apage_id\x18\x02 \x01(\x05R\x06pageId\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"L\n" +
	"\x18GetMyInvitationsResponse\x120\n" +
	"\vinvitations\x18\x01 \x03(\v2\x0e.pb.InvitationR\vinvitations\"Y\n" +
	"\x1aRespondToInvitationRequest\x12#\n" +
	"\rinvitation_id\x18\x01 \x01(\x03R\finvitationId\x12\x16\n" +
	"\x06accept\x18\x02 \x01(\bR\x06accept\"q\n" +
	"\x1bRespondToInvitationResponse\x12.\n" +
	"\n" +
	"invitation\x18\x01 \x01(\v2\x0e.pb.InvitationR\n" +
	"invitation\x12\"\n" +
	"\x06bounty\x18\x02 \x01(\v2\n" +
	".pb.BountyR\x06bounty\"R\n" +
	"\x1bGetMySentInvitationsRequest\x12\x1b\n" +
	"\tbounty_id\x18\x01 \x01(\x03R\bbountyId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"P\n" +
	"\x1cGetMySentInvitationsResponse\x120\n" +
	"\vinvitations\x18\x01 \x03(\v2\x0e.pb.InvitationR\vinvitationsB+Z)github.com/grayfalcon666/escrow-bounty/pbb\x06proto3"

var (
	file_bounty_proto_rawDescOnce sync.Once
	file_bounty_proto_rawDescData []byte
)

func file_bounty_proto_rawDescGZIP() []byte {
	file_bounty_proto_rawDescOnce.Do(func() {
		file_bounty_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bounty_proto_rawDesc), len(file_bounty_proto_rawDesc)))
	})
	return file_bounty_proto_rawDescData
}

var file_bounty_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_bounty_proto_goTypes = []any{
	(*CreateBountyRequest)(nil),          // 0: pb.CreateBountyRequest
	(*CreateBountyResponse)(nil),         // 1: pb.CreateBountyResponse
	(*ListBountiesRequest)(nil),          // 2: pb.ListBountiesRequest
	(*ListBountiesResponse)(nil),         // 3: pb.ListBountiesResponse
	(*GetBountyRequest)(nil),             // 4: pb.GetBountyRequest
	(*GetBountyResponse)(nil),            // 5: pb.GetBountyResponse
	(*DeleteBountyRequest)(nil),          // 6: pb.DeleteBountyRequest
	(*DeleteBountyResponse)(nil),         // 7: pb.DeleteBountyResponse
	(*SubmitBountyRequest)(nil),          // 8: pb.SubmitBountyRequest
	(*SubmitBountyResponse)(nil),         // 9: pb.SubmitBountyResponse
	(*ApproveBountyRequest)(nil),         // 10: pb.ApproveBountyRequest
	(*ApproveBountyResponse)(nil),        // 11: pb.ApproveBountyResponse
	(*RejectBountyRequest)(nil),          // 12: pb.RejectBountyRequest
	(*RejectBountyResponse)(nil),         // 13: pb.RejectBountyResponse
	(*Invitation)(nil),                   // 14: pb.Invitation
	(*CreateInvitationRequest)(nil),      // 15: pb.CreateInvitationRequest
	(*CreateInvitationResponse)(nil),     // 16: pb.CreateInvitationResponse
	(*GetMyInvitationsRequest)(nil),      // 17: pb.GetMyInvitationsRequest
	(*GetMyInvitationsResponse)(nil),     // 18: pb.GetMyInvitationsResponse
	(*RespondToInvitationRequest)(nil),   // 19: pb.RespondToInvitationRequest
	(*RespondToInvitationResponse)(nil),  // 20: pb.RespondToInvitationResponse
	(*GetMySentInvitationsRequest)(nil),  // 21: pb.GetMySentInvitationsRequest
	(*GetMySentInvitationsResponse)(nil), // 22: pb.GetMySentInvitationsResponse
	(*Bounty)(nil),                       // 23: pb.Bounty
	(*BountyApplication)(nil),            // 24: pb.BountyApplication
}
var file_bounty_proto_depIdxs = []int32{
	23, // 0: pb.CreateBountyResponse.bounty:type_name -> pb.Bounty
	23, // 1: pb.ListBountiesResponse.bounties:type_name -> pb.Bounty
	23, // 2: pb.GetBountyResponse.bounty:type_name -> pb.Bounty
	24, // 3: pb.GetBountyResponse.applications:type_name -> pb.BountyApplication
	23, // 4: pb.SubmitBountyResponse.bounty:type_name -> pb.Bounty
	23, // 5: pb.ApproveBountyResponse.bounty:type_name -> pb.Bounty
	23, // 6: pb.RejectBountyResponse.bounty:type_name -> pb.Bounty
	23, // 7: pb.Invitation.bounty:type_name -> pb.Bounty
	14, // 8: pb.CreateInvitationResponse.invitation:type_name -> pb.Invitation
	14, // 9: pb.GetMyInvitationsResponse.invitations:type_name -> pb.Invitation
	14, // 10: pb.RespondToInvitationResponse.invitation:type_name -> pb.Invitation
	23, // 11: pb.RespondToInvitationResponse.bounty:type_name -> pb.Bounty
	14, // 12: pb.GetMySentInvitationsResponse.invitations:type_name -> pb.Invitation
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_bounty_proto_init() }
func file_bounty_proto_init() {
	if File_bounty_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bounty_proto_rawDesc), len(file_bounty_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bounty_proto_goTypes,
		DependencyIndexes: file_bounty_proto_depIdxs,
		MessageInfos:      file_bounty_proto_msgTypes,
	}.Build()
	File_bounty_proto = out.File
	file_bounty_proto_goTypes = nil
	file_bounty_proto_depIdxs = nil
}
