// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: common.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bounty struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	EmployerUsername  string                 `protobuf:"bytes,2,opt,name=employer_username,json=employerUsername,proto3" json:"employer_username,omitempty"`
	EmployerAccountId int64                  `protobuf:"varint,9,opt,name=employer_account_id,json=employerAccountId,proto3" json:"employer_account_id,omitempty"`
	Title             string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description       string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	RewardAmount      int64                  `protobuf:"varint,5,opt,name=reward_amount,json=rewardAmount,proto3" json:"reward_amount,omitempty"`
	Status            string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Deadline          *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=deadline,proto3" json:"deadline,omitempty"`
	SubmissionText    string                 `protobuf:"bytes,11,opt,name=submission_text,json=submissionText,proto3" json:"submission_text,omitempty"`
	HunterUsername    string                 `protobuf:"bytes,12,opt,name=hunter_username,json=hunterUsername,proto3" json:"hunter_username,omitempty"` // 当前 ACCEPTED 的猎人用户名（无则空字符串）
	EmployerAvatarUrl string                 `protobuf:"bytes,13,opt,name=employer_avatar_url,json=employerAvatarUrl,proto3" json:"employer_avatar_url,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Bounty) Reset() {
	*x = Bounty{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bounty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bounty) ProtoMessage() {}

func (x *Bounty) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bounty.ProtoReflect.Descriptor instead.
func (*Bounty) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *Bounty) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Bounty) GetEmployerUsername() string {
	if x != nil {
		return x.EmployerUsername
	}
	return ""
}

func (x *Bounty) GetEmployerAccountId() int64 {
	if x != nil {
		return x.EmployerAccountId
	}
	return 0
}

func (x *Bounty) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Bounty) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Bounty) GetRewardAmount() int64 {
	if x != nil {
		return x.RewardAmount
	}
	return 0
}

func (x *Bounty) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Bounty) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Bounty) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Bounty) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *Bounty) GetSubmissionText() string {
	if x != nil {
		return x.SubmissionText
	}
	return ""
}

func (x *Bounty) GetHunterUsername() string {
	if x != nil {
		return x.HunterUsername
	}
	return ""
}

func (x *Bounty) GetEmployerAvatarUrl() string {
	if x != nil {
		return x.EmployerAvatarUrl
	}
	return ""
}

type BountyApplication struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BountyId        int64                  `protobuf:"varint,2,opt,name=bounty_id,json=bountyId,proto3" json:"bounty_id,omitempty"`
	HunterUsername  string                 `protobuf:"bytes,3,opt,name=hunter_username,json=hunterUsername,proto3" json:"hunter_username,omitempty"`
	HunterAccountId int64                  `protobuf:"varint,7,opt,name=hunter_account_id,json=hunterAccountId,proto3" json:"hunter_account_id,omitempty"`
	Status          string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Bounty          *Bounty                `protobuf:"bytes,8,opt,name=bounty,proto3" json:"bounty,omitempty"` // 关联悬赏信息（响应中附加）
	HunterAvatarUrl string                 `protobuf:"bytes,9,opt,name=hunter_avatar_url,json=hunterAvatarUrl,proto3" json:"hunter_avatar_url,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BountyApplication) Reset() {
	*x = BountyApplication{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BountyApplication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BountyApplication) ProtoMessage() {}

func (x *BountyApplication) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BountyApplication.ProtoReflect.Descriptor instead.
func (*BountyApplication) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *BountyApplication) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BountyApplication) GetBountyId() int64 {
	if x != nil {
		return x.BountyId
	}
	return 0
}

func (x *BountyApplication) GetHunterUsername() string {
	if x != nil {
		return x.HunterUsername
	}
	return ""
}

func (x *BountyApplication) GetHunterAccountId() int64 {
	if x != nil {
		return x.HunterAccountId
	}
	return 0
}

func (x *BountyApplication) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BountyApplication) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *BountyApplication) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *BountyApplication) GetBounty() *Bounty {
	if x != nil {
		return x.Bounty
	}
	return nil
}

func (x *BountyApplication) GetHunterAvatarUrl() string {
	if x != nil {
		return x.HunterAvatarUrl
	}
	return ""
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9a\x04\n" +
	"\x06Bounty\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12+\n" +
	"\x11employer_username\x18\x02 \x01(\tR\x10employerUsername\x12.\n" +
	"\x13employer_account_id\x18\t \x01(\x03R\x11employerAccountId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12#\n" +
	"\rreward_amount\x18\x05 \x01(\x03R\frewardAmount\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x126\n" +
	"\bdeadline\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\x12'\n" +
	"\x0fsubmission_text\x18\v \x01(\tR\x0esubmissionText\x12'\n" +
	"\x0fhunter_username\x18\f \x01(\tR\x0ehunterUsername\x12.\n" +
	"\x13employer_avatar_url\x18\r \x01(\tR\x11employerAvatarUrl\"\xf3\x02\n" +
	"\x11BountyApplication\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tbounty_id\x18\x02 \x01(\x03R\bbountyId\x12'\n" +
	"\x0fhunter_username\x18\x03 \x01(\tR\x0ehunterUsername\x12*\n" +
	"\x11hunter_account_id\x18\a \x01(\x03R\x0fhunterAccountId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\"\n" +
	"\x06bounty\x18\b \x01(\v2\n" +
	".pb.BountyR\x06bounty\x12*\n" +
	"\x11hunter_avatar_url\x18\t \x01(\tR\x0fhunterAvatarUrlB+Z)github.com/grayfalcon666/escrow-bounty/pbb\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_proto_goTypes = []any{
	(*Bounty)(nil),                // 0: pb.Bounty
	(*BountyApplication)(nil),     // 1: pb.BountyApplication
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_common_proto_depIdxs = []int32{
	2, // 0: pb.Bounty.created_at:type_name -> google.protobuf.Timestamp
	2, // 1: pb.Bounty.updated_at:type_name -> google.protobuf.Timestamp
	2, // 2: pb.Bounty.deadline:type_name -> google.protobuf.Timestamp
	2, // 3: pb.BountyApplication.created_at:type_name -> google.protobuf.Timestamp
	2, // 4: pb.BountyApplication.updated_at:type_name -> google.protobuf.Timestamp
	0, // 5: pb.BountyApplication.bounty:type_name -> pb.Bounty
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
