// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.6
// source: service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EscrowBountyService_CreateBounty_FullMethodName            = "/pb.EscrowBountyService/CreateBounty"
	EscrowBountyService_ListBounties_FullMethodName            = "/pb.EscrowBountyService/ListBounties"
	EscrowBountyService_GetBounty_FullMethodName               = "/pb.EscrowBountyService/GetBounty"
	EscrowBountyService_AcceptBounty_FullMethodName            = "/pb.EscrowBountyService/AcceptBounty"
	EscrowBountyService_ConfirmHunter_FullMethodName           = "/pb.EscrowBountyService/ConfirmHunter"
	EscrowBountyService_CompleteBounty_FullMethodName          = "/pb.EscrowBountyService/CompleteBounty"
	EscrowBountyService_SubmitBounty_FullMethodName            = "/pb.EscrowBountyService/SubmitBounty"
	EscrowBountyService_ApproveBounty_FullMethodName           = "/pb.EscrowBountyService/ApproveBounty"
	EscrowBountyService_RejectBounty_FullMethodName            = "/pb.EscrowBountyService/RejectBounty"
	EscrowBountyService_CancelBounty_FullMethodName            = "/pb.EscrowBountyService/CancelBounty"
	EscrowBountyService_DeleteBounty_FullMethodName            = "/pb.EscrowBountyService/DeleteBounty"
	EscrowBountyService_SendMessage_FullMethodName             = "/pb.EscrowBountyService/SendMessage"
	EscrowBountyService_ListMessages_FullMethodName            = "/pb.EscrowBountyService/ListMessages"
	EscrowBountyService_GetOrCreateConversation_FullMethodName = "/pb.EscrowBountyService/GetOrCreateConversation"
	EscrowBountyService_ListConversations_FullMethodName       = "/pb.EscrowBountyService/ListConversations"
	EscrowBountyService_ListPrivateMessages_FullMethodName     = "/pb.EscrowBountyService/ListPrivateMessages"
	EscrowBountyService_DeleteConversation_FullMethodName      = "/pb.EscrowBountyService/DeleteConversation"
	EscrowBountyService_MarkMessagesRead_FullMethodName        = "/pb.EscrowBountyService/MarkMessagesRead"
	EscrowBountyService_GetUnreadCounts_FullMethodName         = "/pb.EscrowBountyService/GetUnreadCounts"
	EscrowBountyService_ListComments_FullMethodName            = "/pb.EscrowBountyService/ListComments"
	EscrowBountyService_CreateComment_FullMethodName           = "/pb.EscrowBountyService/CreateComment"
	EscrowBountyService_DeleteComment_FullMethodName           = "/pb.EscrowBountyService/DeleteComment"
	EscrowBountyService_ListUserComments_FullMethodName        = "/pb.EscrowBountyService/ListUserComments"
	EscrowBountyService_CreateInvitation_FullMethodName        = "/pb.EscrowBountyService/CreateInvitation"
	EscrowBountyService_GetMyInvitations_FullMethodName        = "/pb.EscrowBountyService/GetMyInvitations"
	EscrowBountyService_RespondToInvitation_FullMethodName     = "/pb.EscrowBountyService/RespondToInvitation"
	EscrowBountyService_GetMySentInvitations_FullMethodName    = "/pb.EscrowBountyService/GetMySentInvitations"
	EscrowBountyService_GetMyApplications_FullMethodName       = "/pb.EscrowBountyService/GetMyApplications"
)

// EscrowBountyServiceClient is the client API for EscrowBountyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 统一服务接口
type EscrowBountyServiceClient interface {
	// 雇主发布悬赏
	CreateBounty(ctx context.Context, in *CreateBountyRequest, opts ...grpc.CallOption) (*CreateBountyResponse, error)
	// 获取悬赏大厅列表
	ListBounties(ctx context.Context, in *ListBountiesRequest, opts ...grpc.CallOption) (*ListBountiesResponse, error)
	// 获取单个悬赏详情
	GetBounty(ctx context.Context, in *GetBountyRequest, opts ...grpc.CallOption) (*GetBountyResponse, error)
	// 猎人申请接单
	AcceptBounty(ctx context.Context, in *AcceptBountyRequest, opts ...grpc.CallOption) (*AcceptBountyResponse, error)
	// 雇主选定猎人
	ConfirmHunter(ctx context.Context, in *ConfirmHunterRequest, opts ...grpc.CallOption) (*ConfirmHunterResponse, error)
	// 雇主确认完成并打款
	CompleteBounty(ctx context.Context, in *CompleteBountyRequest, opts ...grpc.CallOption) (*CompleteBountyResponse, error)
	// 猎人提交工作成果
	SubmitBounty(ctx context.Context, in *SubmitBountyRequest, opts ...grpc.CallOption) (*SubmitBountyResponse, error)
	// 雇主审核通过
	ApproveBounty(ctx context.Context, in *ApproveBountyRequest, opts ...grpc.CallOption) (*ApproveBountyResponse, error)
	// 雇主审核拒绝
	RejectBounty(ctx context.Context, in *RejectBountyRequest, opts ...grpc.CallOption) (*RejectBountyResponse, error)
	// 雇主取消悬赏并退款
	CancelBounty(ctx context.Context, in *CancelBountyRequest, opts ...grpc.CallOption) (*CancelBountyResponse, error)
	// 雇主删除悬赏（仅 PENDING/FAILED 状态可删除）
	DeleteBounty(ctx context.Context, in *DeleteBountyRequest, opts ...grpc.CallOption) (*DeleteBountyResponse, error)
	// 悬赏内聊天（原有）
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
	ListMessages(ctx context.Context, in *ListMessagesRequest, opts ...grpc.CallOption) (*ListMessagesResponse, error)
	GetOrCreateConversation(ctx context.Context, in *GetOrCreateConversationRequest, opts ...grpc.CallOption) (*GetOrCreateConversationResponse, error)
	ListConversations(ctx context.Context, in *ListConversationsRequest, opts ...grpc.CallOption) (*ListConversationsResponse, error)
	ListPrivateMessages(ctx context.Context, in *ListPrivateMessagesRequest, opts ...grpc.CallOption) (*ListPrivateMessagesResponse, error)
	DeleteConversation(ctx context.Context, in *DeleteConversationRequest, opts ...grpc.CallOption) (*DeleteConversationResponse, error)
	MarkMessagesRead(ctx context.Context, in *MarkReadRequest, opts ...grpc.CallOption) (*MarkReadResponse, error)
	GetUnreadCounts(ctx context.Context, in *GetUnreadCountsRequest, opts ...grpc.CallOption) (*GetUnreadCountsResponse, error)
	ListComments(ctx context.Context, in *ListCommentsRequest, opts ...grpc.CallOption) (*ListCommentsResponse, error)
	CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*CreateCommentResponse, error)
	DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*DeleteCommentResponse, error)
	ListUserComments(ctx context.Context, in *ListUserCommentsRequest, opts ...grpc.CallOption) (*ListUserCommentsResponse, error)
	// 悬赏者邀请猎人接单
	CreateInvitation(ctx context.Context, in *CreateInvitationRequest, opts ...grpc.CallOption) (*CreateInvitationResponse, error)
	// 猎人查看收到的邀请
	GetMyInvitations(ctx context.Context, in *GetMyInvitationsRequest, opts ...grpc.CallOption) (*GetMyInvitationsResponse, error)
	// 猎人响应邀请（接受/拒绝）
	RespondToInvitation(ctx context.Context, in *RespondToInvitationRequest, opts ...grpc.CallOption) (*RespondToInvitationResponse, error)
	// 悬赏者查看发出的邀请
	GetMySentInvitations(ctx context.Context, in *GetMySentInvitationsRequest, opts ...grpc.CallOption) (*GetMySentInvitationsResponse, error)
	// 猎人查看自己发出的申请
	GetMyApplications(ctx context.Context, in *GetMyApplicationsRequest, opts ...grpc.CallOption) (*GetMyApplicationsResponse, error)
}

type escrowBountyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEscrowBountyServiceClient(cc grpc.ClientConnInterface) EscrowBountyServiceClient {
	return &escrowBountyServiceClient{cc}
}

func (c *escrowBountyServiceClient) CreateBounty(ctx context.Context, in *CreateBountyRequest, opts ...grpc.CallOption) (*CreateBountyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBountyResponse)
	err := c.cc.Invoke(ctx, EscrowBountyService_CreateBounty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *escrowBountyServiceClient) ListBounties(ctx context.Context, in *ListBountiesRequest, opts ...grpc.CallOption) (*ListBountiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBountiesResponse)
	err := c.cc.Invoke(ctx, EscrowBountyService_ListBounties_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *escrowBountyServiceClient) GetBounty(ctx context.Context, in *GetBountyRequest, opts ...grpc.CallOption) (*GetBountyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBountyResponse)
	err := c.cc.Invoke(ctx, EscrowBountyService_GetBounty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *escrowBountyServiceClient) AcceptBounty(ctx context.Context, in *AcceptBountyRequest, opts ...grpc.CallOption) (*AcceptBountyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptBountyResponse)
	err := c.cc.Invoke(ctx, EscrowBountyService_AcceptBounty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *escrowBountyServiceClient) ConfirmHunter(ctx context.Context, in *ConfirmHunterRequest, opts ...grpc.CallOption) (*ConfirmHunterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmHunterResponse)
	err := c.cc.Invoke(ctx, EscrowBountyService_ConfirmHunter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *escrowBountyServiceClient) CompleteBounty(ctx context.Context, in *CompleteBountyRequest, opts ...grpc.CallOption) (*CompleteBountyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteBountyResponse)
	err := c.cc.Invoke(ctx, EscrowBountyService_CompleteBounty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *escrowBountyServiceClient) SubmitBounty(ctx context.Context, in *SubmitBountyRequest, opts ...grpc.CallOption) (*SubmitBountyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitBountyResponse)
	err := c.cc.Invoke(ctx, EscrowBountyService_SubmitBounty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *escrowBountyServiceClient) ApproveBounty(ctx context.Context, in *ApproveBountyRequest, opts ...grpc.CallOption) (*ApproveBountyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveBountyResponse)
	err := c.cc.Invoke(ctx, EscrowBountyService_ApproveBounty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *escrowBountyServiceClient) RejectBounty(ctx context.Context, in *RejectBountyRequest, opts ...grpc.CallOption) (*RejectBountyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RejectBountyResponse)
	err := c.cc.Invoke(ctx, EscrowBountyService_RejectBounty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *escrowBountyServiceClient) CancelBounty(ctx context.Context, in *CancelBountyRequest, opts ...grpc.CallOption) (*CancelBountyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelBountyResponse)
	err := c.cc.Invoke(ctx, EscrowBountyService_CancelBounty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *escrowBountyServiceClient) DeleteBounty(ctx context.Context, in *DeleteBountyRequest, opts ...grpc.CallOption) (*DeleteBountyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBountyResponse)
	err := c.cc.Invoke(ctx, EscrowBountyService_DeleteBounty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *escrowBountyServiceClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMessageResponse)
	err := c.cc.Invoke(ctx, EscrowBountyService_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *escrowBountyServiceClient) ListMessages(ctx context.Context, in *ListMessagesRequest, opts ...grpc.CallOption) (*ListMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMessagesResponse)
	err := c.cc.Invoke(ctx, EscrowBountyService_ListMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *escrowBountyServiceClient) GetOrCreateConversation(ctx context.Context, in *GetOrCreateConversationRequest, opts ...grpc.CallOption) (*GetOrCreateConversationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrCreateConversationResponse)
	err := c.cc.Invoke(ctx, EscrowBountyService_GetOrCreateConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *escrowBountyServiceClient) ListConversations(ctx context.Context, in *ListConversationsRequest, opts ...grpc.CallOption) (*ListConversationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConversationsResponse)
	err := c.cc.Invoke(ctx, EscrowBountyService_ListConversations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *escrowBountyServiceClient) ListPrivateMessages(ctx context.Context, in *ListPrivateMessagesRequest, opts ...grpc.CallOption) (*ListPrivateMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPrivateMessagesResponse)
	err := c.cc.Invoke(ctx, EscrowBountyService_ListPrivateMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *escrowBountyServiceClient) DeleteConversation(ctx context.Context, in *DeleteConversationRequest, opts ...grpc.CallOption) (*DeleteConversationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteConversationResponse)
	err := c.cc.Invoke(ctx, EscrowBountyService_DeleteConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *escrowBountyServiceClient) MarkMessagesRead(ctx context.Context, in *MarkReadRequest, opts ...grpc.CallOption) (*MarkReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkReadResponse)
	err := c.cc.Invoke(ctx, EscrowBountyService_MarkMessagesRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *escrowBountyServiceClient) GetUnreadCounts(ctx context.Context, in *GetUnreadCountsRequest, opts ...grpc.CallOption) (*GetUnreadCountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUnreadCountsResponse)
	err := c.cc.Invoke(ctx, EscrowBountyService_GetUnreadCounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *escrowBountyServiceClient) ListComments(ctx context.Context, in *ListCommentsRequest, opts ...grpc.CallOption) (*ListCommentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCommentsResponse)
	err := c.cc.Invoke(ctx, EscrowBountyService_ListComments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *escrowBountyServiceClient) CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*CreateCommentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCommentResponse)
	err := c.cc.Invoke(ctx, EscrowBountyService_CreateComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *escrowBountyServiceClient) DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*DeleteCommentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCommentResponse)
	err := c.cc.Invoke(ctx, EscrowBountyService_DeleteComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *escrowBountyServiceClient) ListUserComments(ctx context.Context, in *ListUserCommentsRequest, opts ...grpc.CallOption) (*ListUserCommentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUserCommentsResponse)
	err := c.cc.Invoke(ctx, EscrowBountyService_ListUserComments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *escrowBountyServiceClient) CreateInvitation(ctx context.Context, in *CreateInvitationRequest, opts ...grpc.CallOption) (*CreateInvitationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateInvitationResponse)
	err := c.cc.Invoke(ctx, EscrowBountyService_CreateInvitation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *escrowBountyServiceClient) GetMyInvitations(ctx context.Context, in *GetMyInvitationsRequest, opts ...grpc.CallOption) (*GetMyInvitationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMyInvitationsResponse)
	err := c.cc.Invoke(ctx, EscrowBountyService_GetMyInvitations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *escrowBountyServiceClient) RespondToInvitation(ctx context.Context, in *RespondToInvitationRequest, opts ...grpc.CallOption) (*RespondToInvitationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RespondToInvitationResponse)
	err := c.cc.Invoke(ctx, EscrowBountyService_RespondToInvitation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *escrowBountyServiceClient) GetMySentInvitations(ctx context.Context, in *GetMySentInvitationsRequest, opts ...grpc.CallOption) (*GetMySentInvitationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMySentInvitationsResponse)
	err := c.cc.Invoke(ctx, EscrowBountyService_GetMySentInvitations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *escrowBountyServiceClient) GetMyApplications(ctx context.Context, in *GetMyApplicationsRequest, opts ...grpc.CallOption) (*GetMyApplicationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMyApplicationsResponse)
	err := c.cc.Invoke(ctx, EscrowBountyService_GetMyApplications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EscrowBountyServiceServer is the server API for EscrowBountyService service.
// All implementations must embed UnimplementedEscrowBountyServiceServer
// for forward compatibility.
//
// 统一服务接口
type EscrowBountyServiceServer interface {
	// 雇主发布悬赏
	CreateBounty(context.Context, *CreateBountyRequest) (*CreateBountyResponse, error)
	// 获取悬赏大厅列表
	ListBounties(context.Context, *ListBountiesRequest) (*ListBountiesResponse, error)
	// 获取单个悬赏详情
	GetBounty(context.Context, *GetBountyRequest) (*GetBountyResponse, error)
	// 猎人申请接单
	AcceptBounty(context.Context, *AcceptBountyRequest) (*AcceptBountyResponse, error)
	// 雇主选定猎人
	ConfirmHunter(context.Context, *ConfirmHunterRequest) (*ConfirmHunterResponse, error)
	// 雇主确认完成并打款
	CompleteBounty(context.Context, *CompleteBountyRequest) (*CompleteBountyResponse, error)
	// 猎人提交工作成果
	SubmitBounty(context.Context, *SubmitBountyRequest) (*SubmitBountyResponse, error)
	// 雇主审核通过
	ApproveBounty(context.Context, *ApproveBountyRequest) (*ApproveBountyResponse, error)
	// 雇主审核拒绝
	RejectBounty(context.Context, *RejectBountyRequest) (*RejectBountyResponse, error)
	// 雇主取消悬赏并退款
	CancelBounty(context.Context, *CancelBountyRequest) (*CancelBountyResponse, error)
	// 雇主删除悬赏（仅 PENDING/FAILED 状态可删除）
	DeleteBounty(context.Context, *DeleteBountyRequest) (*DeleteBountyResponse, error)
	// 悬赏内聊天（原有）
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error)
	ListMessages(context.Context, *ListMessagesRequest) (*ListMessagesResponse, error)
	GetOrCreateConversation(context.Context, *GetOrCreateConversationRequest) (*GetOrCreateConversationResponse, error)
	ListConversations(context.Context, *ListConversationsRequest) (*ListConversationsResponse, error)
	ListPrivateMessages(context.Context, *ListPrivateMessagesRequest) (*ListPrivateMessagesResponse, error)
	DeleteConversation(context.Context, *DeleteConversationRequest) (*DeleteConversationResponse, error)
	MarkMessagesRead(context.Context, *MarkReadRequest) (*MarkReadResponse, error)
	GetUnreadCounts(context.Context, *GetUnreadCountsRequest) (*GetUnreadCountsResponse, error)
	ListComments(context.Context, *ListCommentsRequest) (*ListCommentsResponse, error)
	CreateComment(context.Context, *CreateCommentRequest) (*CreateCommentResponse, error)
	DeleteComment(context.Context, *DeleteCommentRequest) (*DeleteCommentResponse, error)
	ListUserComments(context.Context, *ListUserCommentsRequest) (*ListUserCommentsResponse, error)
	// 悬赏者邀请猎人接单
	CreateInvitation(context.Context, *CreateInvitationRequest) (*CreateInvitationResponse, error)
	// 猎人查看收到的邀请
	GetMyInvitations(context.Context, *GetMyInvitationsRequest) (*GetMyInvitationsResponse, error)
	// 猎人响应邀请（接受/拒绝）
	RespondToInvitation(context.Context, *RespondToInvitationRequest) (*RespondToInvitationResponse, error)
	// 悬赏者查看发出的邀请
	GetMySentInvitations(context.Context, *GetMySentInvitationsRequest) (*GetMySentInvitationsResponse, error)
	// 猎人查看自己发出的申请
	GetMyApplications(context.Context, *GetMyApplicationsRequest) (*GetMyApplicationsResponse, error)
	mustEmbedUnimplementedEscrowBountyServiceServer()
}

// UnimplementedEscrowBountyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEscrowBountyServiceServer struct{}

func (UnimplementedEscrowBountyServiceServer) CreateBounty(context.Context, *CreateBountyRequest) (*CreateBountyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBounty not implemented")
}
func (UnimplementedEscrowBountyServiceServer) ListBounties(context.Context, *ListBountiesRequest) (*ListBountiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBounties not implemented")
}
func (UnimplementedEscrowBountyServiceServer) GetBounty(context.Context, *GetBountyRequest) (*GetBountyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBounty not implemented")
}
func (UnimplementedEscrowBountyServiceServer) AcceptBounty(context.Context, *AcceptBountyRequest) (*AcceptBountyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptBounty not implemented")
}
func (UnimplementedEscrowBountyServiceServer) ConfirmHunter(context.Context, *ConfirmHunterRequest) (*ConfirmHunterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmHunter not implemented")
}
func (UnimplementedEscrowBountyServiceServer) CompleteBounty(context.Context, *CompleteBountyRequest) (*CompleteBountyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteBounty not implemented")
}
func (UnimplementedEscrowBountyServiceServer) SubmitBounty(context.Context, *SubmitBountyRequest) (*SubmitBountyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitBounty not implemented")
}
func (UnimplementedEscrowBountyServiceServer) ApproveBounty(context.Context, *ApproveBountyRequest) (*ApproveBountyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveBounty not implemented")
}
func (UnimplementedEscrowBountyServiceServer) RejectBounty(context.Context, *RejectBountyRequest) (*RejectBountyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectBounty not implemented")
}
func (UnimplementedEscrowBountyServiceServer) CancelBounty(context.Context, *CancelBountyRequest) (*CancelBountyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelBounty not implemented")
}
func (UnimplementedEscrowBountyServiceServer) DeleteBounty(context.Context, *DeleteBountyRequest) (*DeleteBountyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBounty not implemented")
}
func (UnimplementedEscrowBountyServiceServer) SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedEscrowBountyServiceServer) ListMessages(context.Context, *ListMessagesRequest) (*ListMessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMessages not implemented")
}
func (UnimplementedEscrowBountyServiceServer) GetOrCreateConversation(context.Context, *GetOrCreateConversationRequest) (*GetOrCreateConversationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrCreateConversation not implemented")
}
func (UnimplementedEscrowBountyServiceServer) ListConversations(context.Context, *ListConversationsRequest) (*ListConversationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListConversations not implemented")
}
func (UnimplementedEscrowBountyServiceServer) ListPrivateMessages(context.Context, *ListPrivateMessagesRequest) (*ListPrivateMessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPrivateMessages not implemented")
}
func (UnimplementedEscrowBountyServiceServer) DeleteConversation(context.Context, *DeleteConversationRequest) (*DeleteConversationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteConversation not implemented")
}
func (UnimplementedEscrowBountyServiceServer) MarkMessagesRead(context.Context, *MarkReadRequest) (*MarkReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkMessagesRead not implemented")
}
func (UnimplementedEscrowBountyServiceServer) GetUnreadCounts(context.Context, *GetUnreadCountsRequest) (*GetUnreadCountsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUnreadCounts not implemented")
}
func (UnimplementedEscrowBountyServiceServer) ListComments(context.Context, *ListCommentsRequest) (*ListCommentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListComments not implemented")
}
func (UnimplementedEscrowBountyServiceServer) CreateComment(context.Context, *CreateCommentRequest) (*CreateCommentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateComment not implemented")
}
func (UnimplementedEscrowBountyServiceServer) DeleteComment(context.Context, *DeleteCommentRequest) (*DeleteCommentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteComment not implemented")
}
func (UnimplementedEscrowBountyServiceServer) ListUserComments(context.Context, *ListUserCommentsRequest) (*ListUserCommentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUserComments not implemented")
}
func (UnimplementedEscrowBountyServiceServer) CreateInvitation(context.Context, *CreateInvitationRequest) (*CreateInvitationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateInvitation not implemented")
}
func (UnimplementedEscrowBountyServiceServer) GetMyInvitations(context.Context, *GetMyInvitationsRequest) (*GetMyInvitationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMyInvitations not implemented")
}
func (UnimplementedEscrowBountyServiceServer) RespondToInvitation(context.Context, *RespondToInvitationRequest) (*RespondToInvitationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RespondToInvitation not implemented")
}
func (UnimplementedEscrowBountyServiceServer) GetMySentInvitations(context.Context, *GetMySentInvitationsRequest) (*GetMySentInvitationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMySentInvitations not implemented")
}
func (UnimplementedEscrowBountyServiceServer) GetMyApplications(context.Context, *GetMyApplicationsRequest) (*GetMyApplicationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMyApplications not implemented")
}
func (UnimplementedEscrowBountyServiceServer) mustEmbedUnimplementedEscrowBountyServiceServer() {}
func (UnimplementedEscrowBountyServiceServer) testEmbeddedByValue()                             {}

// UnsafeEscrowBountyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EscrowBountyServiceServer will
// result in compilation errors.
type UnsafeEscrowBountyServiceServer interface {
	mustEmbedUnimplementedEscrowBountyServiceServer()
}

func RegisterEscrowBountyServiceServer(s grpc.ServiceRegistrar, srv EscrowBountyServiceServer) {
	// If the following call panics, it indicates UnimplementedEscrowBountyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EscrowBountyService_ServiceDesc, srv)
}

func _EscrowBountyService_CreateBounty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBountyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EscrowBountyServiceServer).CreateBounty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EscrowBountyService_CreateBounty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EscrowBountyServiceServer).CreateBounty(ctx, req.(*CreateBountyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EscrowBountyService_ListBounties_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBountiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EscrowBountyServiceServer).ListBounties(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EscrowBountyService_ListBounties_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EscrowBountyServiceServer).ListBounties(ctx, req.(*ListBountiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EscrowBountyService_GetBounty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBountyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EscrowBountyServiceServer).GetBounty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EscrowBountyService_GetBounty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EscrowBountyServiceServer).GetBounty(ctx, req.(*GetBountyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EscrowBountyService_AcceptBounty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptBountyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EscrowBountyServiceServer).AcceptBounty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EscrowBountyService_AcceptBounty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EscrowBountyServiceServer).AcceptBounty(ctx, req.(*AcceptBountyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EscrowBountyService_ConfirmHunter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmHunterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EscrowBountyServiceServer).ConfirmHunter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EscrowBountyService_ConfirmHunter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EscrowBountyServiceServer).ConfirmHunter(ctx, req.(*ConfirmHunterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EscrowBountyService_CompleteBounty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteBountyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EscrowBountyServiceServer).CompleteBounty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EscrowBountyService_CompleteBounty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EscrowBountyServiceServer).CompleteBounty(ctx, req.(*CompleteBountyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EscrowBountyService_SubmitBounty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitBountyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EscrowBountyServiceServer).SubmitBounty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EscrowBountyService_SubmitBounty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EscrowBountyServiceServer).SubmitBounty(ctx, req.(*SubmitBountyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EscrowBountyService_ApproveBounty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveBountyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EscrowBountyServiceServer).ApproveBounty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EscrowBountyService_ApproveBounty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EscrowBountyServiceServer).ApproveBounty(ctx, req.(*ApproveBountyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EscrowBountyService_RejectBounty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectBountyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EscrowBountyServiceServer).RejectBounty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EscrowBountyService_RejectBounty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EscrowBountyServiceServer).RejectBounty(ctx, req.(*RejectBountyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EscrowBountyService_CancelBounty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelBountyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EscrowBountyServiceServer).CancelBounty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EscrowBountyService_CancelBounty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EscrowBountyServiceServer).CancelBounty(ctx, req.(*CancelBountyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EscrowBountyService_DeleteBounty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBountyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EscrowBountyServiceServer).DeleteBounty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EscrowBountyService_DeleteBounty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EscrowBountyServiceServer).DeleteBounty(ctx, req.(*DeleteBountyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EscrowBountyService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EscrowBountyServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EscrowBountyService_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EscrowBountyServiceServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EscrowBountyService_ListMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EscrowBountyServiceServer).ListMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EscrowBountyService_ListMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EscrowBountyServiceServer).ListMessages(ctx, req.(*ListMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EscrowBountyService_GetOrCreateConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrCreateConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EscrowBountyServiceServer).GetOrCreateConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EscrowBountyService_GetOrCreateConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EscrowBountyServiceServer).GetOrCreateConversation(ctx, req.(*GetOrCreateConversationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EscrowBountyService_ListConversations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConversationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EscrowBountyServiceServer).ListConversations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EscrowBountyService_ListConversations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EscrowBountyServiceServer).ListConversations(ctx, req.(*ListConversationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EscrowBountyService_ListPrivateMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPrivateMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EscrowBountyServiceServer).ListPrivateMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EscrowBountyService_ListPrivateMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EscrowBountyServiceServer).ListPrivateMessages(ctx, req.(*ListPrivateMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EscrowBountyService_DeleteConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EscrowBountyServiceServer).DeleteConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EscrowBountyService_DeleteConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EscrowBountyServiceServer).DeleteConversation(ctx, req.(*DeleteConversationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EscrowBountyService_MarkMessagesRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EscrowBountyServiceServer).MarkMessagesRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EscrowBountyService_MarkMessagesRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EscrowBountyServiceServer).MarkMessagesRead(ctx, req.(*MarkReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EscrowBountyService_GetUnreadCounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUnreadCountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EscrowBountyServiceServer).GetUnreadCounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EscrowBountyService_GetUnreadCounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EscrowBountyServiceServer).GetUnreadCounts(ctx, req.(*GetUnreadCountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EscrowBountyService_ListComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EscrowBountyServiceServer).ListComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EscrowBountyService_ListComments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EscrowBountyServiceServer).ListComments(ctx, req.(*ListCommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EscrowBountyService_CreateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EscrowBountyServiceServer).CreateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EscrowBountyService_CreateComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EscrowBountyServiceServer).CreateComment(ctx, req.(*CreateCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EscrowBountyService_DeleteComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EscrowBountyServiceServer).DeleteComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EscrowBountyService_DeleteComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EscrowBountyServiceServer).DeleteComment(ctx, req.(*DeleteCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EscrowBountyService_ListUserComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserCommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EscrowBountyServiceServer).ListUserComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EscrowBountyService_ListUserComments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EscrowBountyServiceServer).ListUserComments(ctx, req.(*ListUserCommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EscrowBountyService_CreateInvitation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInvitationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EscrowBountyServiceServer).CreateInvitation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EscrowBountyService_CreateInvitation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EscrowBountyServiceServer).CreateInvitation(ctx, req.(*CreateInvitationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EscrowBountyService_GetMyInvitations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyInvitationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EscrowBountyServiceServer).GetMyInvitations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EscrowBountyService_GetMyInvitations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EscrowBountyServiceServer).GetMyInvitations(ctx, req.(*GetMyInvitationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EscrowBountyService_RespondToInvitation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RespondToInvitationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EscrowBountyServiceServer).RespondToInvitation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EscrowBountyService_RespondToInvitation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EscrowBountyServiceServer).RespondToInvitation(ctx, req.(*RespondToInvitationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EscrowBountyService_GetMySentInvitations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMySentInvitationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EscrowBountyServiceServer).GetMySentInvitations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EscrowBountyService_GetMySentInvitations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EscrowBountyServiceServer).GetMySentInvitations(ctx, req.(*GetMySentInvitationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EscrowBountyService_GetMyApplications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyApplicationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EscrowBountyServiceServer).GetMyApplications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EscrowBountyService_GetMyApplications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EscrowBountyServiceServer).GetMyApplications(ctx, req.(*GetMyApplicationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EscrowBountyService_ServiceDesc is the grpc.ServiceDesc for EscrowBountyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EscrowBountyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.EscrowBountyService",
	HandlerType: (*EscrowBountyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBounty",
			Handler:    _EscrowBountyService_CreateBounty_Handler,
		},
		{
			MethodName: "ListBounties",
			Handler:    _EscrowBountyService_ListBounties_Handler,
		},
		{
			MethodName: "GetBounty",
			Handler:    _EscrowBountyService_GetBounty_Handler,
		},
		{
			MethodName: "AcceptBounty",
			Handler:    _EscrowBountyService_AcceptBounty_Handler,
		},
		{
			MethodName: "ConfirmHunter",
			Handler:    _EscrowBountyService_ConfirmHunter_Handler,
		},
		{
			MethodName: "CompleteBounty",
			Handler:    _EscrowBountyService_CompleteBounty_Handler,
		},
		{
			MethodName: "SubmitBounty",
			Handler:    _EscrowBountyService_SubmitBounty_Handler,
		},
		{
			MethodName: "ApproveBounty",
			Handler:    _EscrowBountyService_ApproveBounty_Handler,
		},
		{
			MethodName: "RejectBounty",
			Handler:    _EscrowBountyService_RejectBounty_Handler,
		},
		{
			MethodName: "CancelBounty",
			Handler:    _EscrowBountyService_CancelBounty_Handler,
		},
		{
			MethodName: "DeleteBounty",
			Handler:    _EscrowBountyService_DeleteBounty_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _EscrowBountyService_SendMessage_Handler,
		},
		{
			MethodName: "ListMessages",
			Handler:    _EscrowBountyService_ListMessages_Handler,
		},
		{
			MethodName: "GetOrCreateConversation",
			Handler:    _EscrowBountyService_GetOrCreateConversation_Handler,
		},
		{
			MethodName: "ListConversations",
			Handler:    _EscrowBountyService_ListConversations_Handler,
		},
		{
			MethodName: "ListPrivateMessages",
			Handler:    _EscrowBountyService_ListPrivateMessages_Handler,
		},
		{
			MethodName: "DeleteConversation",
			Handler:    _EscrowBountyService_DeleteConversation_Handler,
		},
		{
			MethodName: "MarkMessagesRead",
			Handler:    _EscrowBountyService_MarkMessagesRead_Handler,
		},
		{
			MethodName: "GetUnreadCounts",
			Handler:    _EscrowBountyService_GetUnreadCounts_Handler,
		},
		{
			MethodName: "ListComments",
			Handler:    _EscrowBountyService_ListComments_Handler,
		},
		{
			MethodName: "CreateComment",
			Handler:    _EscrowBountyService_CreateComment_Handler,
		},
		{
			MethodName: "DeleteComment",
			Handler:    _EscrowBountyService_DeleteComment_Handler,
		},
		{
			MethodName: "ListUserComments",
			Handler:    _EscrowBountyService_ListUserComments_Handler,
		},
		{
			MethodName: "CreateInvitation",
			Handler:    _EscrowBountyService_CreateInvitation_Handler,
		},
		{
			MethodName: "GetMyInvitations",
			Handler:    _EscrowBountyService_GetMyInvitations_Handler,
		},
		{
			MethodName: "RespondToInvitation",
			Handler:    _EscrowBountyService_RespondToInvitation_Handler,
		},
		{
			MethodName: "GetMySentInvitations",
			Handler:    _EscrowBountyService_GetMySentInvitations_Handler,
		},
		{
			MethodName: "GetMyApplications",
			Handler:    _EscrowBountyService_GetMyApplications_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
