// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: rpc_transfer_tx.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransferTxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromAccountId int64                  `protobuf:"varint,1,opt,name=from_account_id,json=fromAccountId,proto3" json:"from_account_id,omitempty"`
	ToAccountId   int64                  `protobuf:"varint,2,opt,name=to_account_id,json=toAccountId,proto3" json:"to_account_id,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	// 防止重放
	IdempotencyKey string `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	TradeType      string `protobuf:"bytes,5,opt,name=trade_type,json=tradeType,proto3" json:"trade_type,omitempty"`
	TradeId        int64  `protobuf:"varint,6,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	Description    string `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TransferTxRequest) Reset() {
	*x = TransferTxRequest{}
	mi := &file_rpc_transfer_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferTxRequest) ProtoMessage() {}

func (x *TransferTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_transfer_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferTxRequest.ProtoReflect.Descriptor instead.
func (*TransferTxRequest) Descriptor() ([]byte, []int) {
	return file_rpc_transfer_tx_proto_rawDescGZIP(), []int{0}
}

func (x *TransferTxRequest) GetFromAccountId() int64 {
	if x != nil {
		return x.FromAccountId
	}
	return 0
}

func (x *TransferTxRequest) GetToAccountId() int64 {
	if x != nil {
		return x.ToAccountId
	}
	return 0
}

func (x *TransferTxRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransferTxRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *TransferTxRequest) GetTradeType() string {
	if x != nil {
		return x.TradeType
	}
	return ""
}

func (x *TransferTxRequest) GetTradeId() int64 {
	if x != nil {
		return x.TradeId
	}
	return 0
}

func (x *TransferTxRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type TransferTxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    int64                  `protobuf:"varint,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	FromAccountId int64                  `protobuf:"varint,2,opt,name=from_account_id,json=fromAccountId,proto3" json:"from_account_id,omitempty"`
	ToAccountId   int64                  `protobuf:"varint,3,opt,name=to_account_id,json=toAccountId,proto3" json:"to_account_id,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// 返回转账后的最新余额
	FromAccountBalance int64 `protobuf:"varint,6,opt,name=from_account_balance,json=fromAccountBalance,proto3" json:"from_account_balance,omitempty"`
	ToAccountBalance   int64 `protobuf:"varint,7,opt,name=to_account_balance,json=toAccountBalance,proto3" json:"to_account_balance,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TransferTxResponse) Reset() {
	*x = TransferTxResponse{}
	mi := &file_rpc_transfer_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferTxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferTxResponse) ProtoMessage() {}

func (x *TransferTxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_transfer_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferTxResponse.ProtoReflect.Descriptor instead.
func (*TransferTxResponse) Descriptor() ([]byte, []int) {
	return file_rpc_transfer_tx_proto_rawDescGZIP(), []int{1}
}

func (x *TransferTxResponse) GetTransferId() int64 {
	if x != nil {
		return x.TransferId
	}
	return 0
}

func (x *TransferTxResponse) GetFromAccountId() int64 {
	if x != nil {
		return x.FromAccountId
	}
	return 0
}

func (x *TransferTxResponse) GetToAccountId() int64 {
	if x != nil {
		return x.ToAccountId
	}
	return 0
}

func (x *TransferTxResponse) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransferTxResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TransferTxResponse) GetFromAccountBalance() int64 {
	if x != nil {
		return x.FromAccountBalance
	}
	return 0
}

func (x *TransferTxResponse) GetToAccountBalance() int64 {
	if x != nil {
		return x.ToAccountBalance
	}
	return 0
}

var File_rpc_transfer_tx_proto protoreflect.FileDescriptor

const file_rpc_transfer_tx_proto_rawDesc = "" +
	"\n" +
	"\x15rpc_transfer_tx.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfc\x01\n" +
	"\x11TransferTxRequest\x12&\n" +
	"\x0ffrom_account_id\x18\x01 \x01(\x03R\rfromAccountId\x12\"\n" +
	"\rto_account_id\x18\x02 \x01(\x03R\vtoAccountId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\x12\x1d\n" +
	"\n" +
	"trade_type\x18\x05 \x01(\tR\ttradeType\x12\x19\n" +
	"\btrade_id\x18\x06 \x01(\x03R\atradeId\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\"\xb4\x02\n" +
	"\x12TransferTxResponse\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\x03R\n" +
	"transferId\x12&\n" +
	"\x0ffrom_account_id\x18\x02 \x01(\x03R\rfromAccountId\x12\"\n" +
	"\rto_account_id\x18\x03 \x01(\x03R\vtoAccountId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x120\n" +
	"\x14from_account_balance\x18\x06 \x01(\x03R\x12fromAccountBalance\x12,\n" +
	"\x12to_account_balance\x18\a \x01(\x03R\x10toAccountBalanceB\x0fZ\rsimplebank/pbb\x06proto3"

var (
	file_rpc_transfer_tx_proto_rawDescOnce sync.Once
	file_rpc_transfer_tx_proto_rawDescData []byte
)

func file_rpc_transfer_tx_proto_rawDescGZIP() []byte {
	file_rpc_transfer_tx_proto_rawDescOnce.Do(func() {
		file_rpc_transfer_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_transfer_tx_proto_rawDesc), len(file_rpc_transfer_tx_proto_rawDesc)))
	})
	return file_rpc_transfer_tx_proto_rawDescData
}

var file_rpc_transfer_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_transfer_tx_proto_goTypes = []any{
	(*TransferTxRequest)(nil),     // 0: pb.TransferTxRequest
	(*TransferTxResponse)(nil),    // 1: pb.TransferTxResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_rpc_transfer_tx_proto_depIdxs = []int32{
	2, // 0: pb.TransferTxResponse.created_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_transfer_tx_proto_init() }
func file_rpc_transfer_tx_proto_init() {
	if File_rpc_transfer_tx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_transfer_tx_proto_rawDesc), len(file_rpc_transfer_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_transfer_tx_proto_goTypes,
		DependencyIndexes: file_rpc_transfer_tx_proto_depIdxs,
		MessageInfos:      file_rpc_transfer_tx_proto_msgTypes,
	}.Build()
	File_rpc_transfer_tx_proto = out.File
	file_rpc_transfer_tx_proto_goTypes = nil
	file_rpc_transfer_tx_proto_depIdxs = nil
}
