// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: rpc_ledger.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LedgerEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId     int64                  `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	BountyId      int64                  `protobuf:"varint,3,opt,name=bounty_id,json=bountyId,proto3" json:"bounty_id,omitempty"`
	EventType     string                 `protobuf:"bytes,4,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Amount        int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Counterparty  string                 `protobuf:"bytes,6,opt,name=counterparty,proto3" json:"counterparty,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedgerEntry) Reset() {
	*x = LedgerEntry{}
	mi := &file_rpc_ledger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerEntry) ProtoMessage() {}

func (x *LedgerEntry) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_ledger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerEntry.ProtoReflect.Descriptor instead.
func (*LedgerEntry) Descriptor() ([]byte, []int) {
	return file_rpc_ledger_proto_rawDescGZIP(), []int{0}
}

func (x *LedgerEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LedgerEntry) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *LedgerEntry) GetBountyId() int64 {
	if x != nil {
		return x.BountyId
	}
	return 0
}

func (x *LedgerEntry) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *LedgerEntry) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *LedgerEntry) GetCounterparty() string {
	if x != nil {
		return x.Counterparty
	}
	return ""
}

func (x *LedgerEntry) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *LedgerEntry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateLedgerEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	BountyId      int64                  `protobuf:"varint,2,opt,name=bounty_id,json=bountyId,proto3" json:"bounty_id,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Counterparty  string                 `protobuf:"bytes,5,opt,name=counterparty,proto3" json:"counterparty,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLedgerEntryRequest) Reset() {
	*x = CreateLedgerEntryRequest{}
	mi := &file_rpc_ledger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLedgerEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLedgerEntryRequest) ProtoMessage() {}

func (x *CreateLedgerEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_ledger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLedgerEntryRequest.ProtoReflect.Descriptor instead.
func (*CreateLedgerEntryRequest) Descriptor() ([]byte, []int) {
	return file_rpc_ledger_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLedgerEntryRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *CreateLedgerEntryRequest) GetBountyId() int64 {
	if x != nil {
		return x.BountyId
	}
	return 0
}

func (x *CreateLedgerEntryRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *CreateLedgerEntryRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateLedgerEntryRequest) GetCounterparty() string {
	if x != nil {
		return x.Counterparty
	}
	return ""
}

func (x *CreateLedgerEntryRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateLedgerEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *LedgerEntry           `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLedgerEntryResponse) Reset() {
	*x = CreateLedgerEntryResponse{}
	mi := &file_rpc_ledger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLedgerEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLedgerEntryResponse) ProtoMessage() {}

func (x *CreateLedgerEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_ledger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLedgerEntryResponse.ProtoReflect.Descriptor instead.
func (*CreateLedgerEntryResponse) Descriptor() ([]byte, []int) {
	return file_rpc_ledger_proto_rawDescGZIP(), []int{2}
}

func (x *CreateLedgerEntryResponse) GetEntry() *LedgerEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type ListAccountLedgerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountLedgerRequest) Reset() {
	*x = ListAccountLedgerRequest{}
	mi := &file_rpc_ledger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountLedgerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountLedgerRequest) ProtoMessage() {}

func (x *ListAccountLedgerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_ledger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountLedgerRequest.ProtoReflect.Descriptor instead.
func (*ListAccountLedgerRequest) Descriptor() ([]byte, []int) {
	return file_rpc_ledger_proto_rawDescGZIP(), []int{3}
}

func (x *ListAccountLedgerRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *ListAccountLedgerRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAccountLedgerRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListAccountLedgerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LedgerEntries []*LedgerEntry         `protobuf:"bytes,1,rep,name=ledger_entries,json=ledgerEntries,proto3" json:"ledger_entries,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountLedgerResponse) Reset() {
	*x = ListAccountLedgerResponse{}
	mi := &file_rpc_ledger_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountLedgerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountLedgerResponse) ProtoMessage() {}

func (x *ListAccountLedgerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_ledger_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountLedgerResponse.ProtoReflect.Descriptor instead.
func (*ListAccountLedgerResponse) Descriptor() ([]byte, []int) {
	return file_rpc_ledger_proto_rawDescGZIP(), []int{4}
}

func (x *ListAccountLedgerResponse) GetLedgerEntries() []*LedgerEntry {
	if x != nil {
		return x.LedgerEntries
	}
	return nil
}

func (x *ListAccountLedgerResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListAccountLedgerResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAccountLedgerResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_rpc_ledger_proto protoreflect.FileDescriptor

const file_rpc_ledger_proto_rawDesc = "" +
	"\n" +
	"\x10rpc_ledger.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\"\x91\x02\n" +
	"\vLedgerEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x03R\taccountId\x12\x1b\n" +
	"\tbounty_id\x18\x03 \x01(\x03R\bbountyId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x04 \x01(\tR\teventType\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\x12\"\n" +
	"\fcounterparty\x18\x06 \x01(\tR\fcounterparty\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xd3\x01\n" +
	"\x18CreateLedgerEntryRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\x12\x1b\n" +
	"\tbounty_id\x18\x02 \x01(\x03R\bbountyId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\"\n" +
	"\fcounterparty\x18\x05 \x01(\tR\fcounterparty\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\"B\n" +
	"\x19CreateLedgerEntryResponse\x12%\n" +
	"\x05entry\x18\x01 \x01(\v2\x0f.pb.LedgerEntryR\x05entry\"j\n" +
	"\x18ListAccountLedgerRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\x9a\x01\n" +
	"\x19ListAccountLedgerResponse\x126\n" +
	"\x0eledger_entries\x18\x01 \x03(\v2\x0f.pb.LedgerEntryR\rledgerEntries\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSizeB\x0fZ\rsimplebank/pbb\x06proto3"

var (
	file_rpc_ledger_proto_rawDescOnce sync.Once
	file_rpc_ledger_proto_rawDescData []byte
)

func file_rpc_ledger_proto_rawDescGZIP() []byte {
	file_rpc_ledger_proto_rawDescOnce.Do(func() {
		file_rpc_ledger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_ledger_proto_rawDesc), len(file_rpc_ledger_proto_rawDesc)))
	})
	return file_rpc_ledger_proto_rawDescData
}

var file_rpc_ledger_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_rpc_ledger_proto_goTypes = []any{
	(*LedgerEntry)(nil),               // 0: pb.LedgerEntry
	(*CreateLedgerEntryRequest)(nil),  // 1: pb.CreateLedgerEntryRequest
	(*CreateLedgerEntryResponse)(nil), // 2: pb.CreateLedgerEntryResponse
	(*ListAccountLedgerRequest)(nil),  // 3: pb.ListAccountLedgerRequest
	(*ListAccountLedgerResponse)(nil), // 4: pb.ListAccountLedgerResponse
	(*timestamppb.Timestamp)(nil),     // 5: google.protobuf.Timestamp
}
var file_rpc_ledger_proto_depIdxs = []int32{
	5, // 0: pb.LedgerEntry.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: pb.CreateLedgerEntryResponse.entry:type_name -> pb.LedgerEntry
	0, // 2: pb.ListAccountLedgerResponse.ledger_entries:type_name -> pb.LedgerEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_rpc_ledger_proto_init() }
func file_rpc_ledger_proto_init() {
	if File_rpc_ledger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_ledger_proto_rawDesc), len(file_rpc_ledger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_ledger_proto_goTypes,
		DependencyIndexes: file_rpc_ledger_proto_depIdxs,
		MessageInfos:      file_rpc_ledger_proto_msgTypes,
	}.Build()
	File_rpc_ledger_proto = out.File
	file_rpc_ledger_proto_goTypes = nil
	file_rpc_ledger_proto_depIdxs = nil
}
