// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: application.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 申请接单相关请求/响应
type AcceptBountyRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BountyId        int64                  `protobuf:"varint,1,opt,name=bounty_id,json=bountyId,proto3" json:"bounty_id,omitempty"`
	HunterAccountId int64                  `protobuf:"varint,2,opt,name=hunter_account_id,json=hunterAccountId,proto3" json:"hunter_account_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AcceptBountyRequest) Reset() {
	*x = AcceptBountyRequest{}
	mi := &file_application_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptBountyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptBountyRequest) ProtoMessage() {}

func (x *AcceptBountyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_application_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptBountyRequest.ProtoReflect.Descriptor instead.
func (*AcceptBountyRequest) Descriptor() ([]byte, []int) {
	return file_application_proto_rawDescGZIP(), []int{0}
}

func (x *AcceptBountyRequest) GetBountyId() int64 {
	if x != nil {
		return x.BountyId
	}
	return 0
}

func (x *AcceptBountyRequest) GetHunterAccountId() int64 {
	if x != nil {
		return x.HunterAccountId
	}
	return 0
}

type AcceptBountyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Application   *BountyApplication     `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptBountyResponse) Reset() {
	*x = AcceptBountyResponse{}
	mi := &file_application_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptBountyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptBountyResponse) ProtoMessage() {}

func (x *AcceptBountyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_application_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptBountyResponse.ProtoReflect.Descriptor instead.
func (*AcceptBountyResponse) Descriptor() ([]byte, []int) {
	return file_application_proto_rawDescGZIP(), []int{1}
}

func (x *AcceptBountyResponse) GetApplication() *BountyApplication {
	if x != nil {
		return x.Application
	}
	return nil
}

// 猎人查看自己发出的申请
type GetMyApplicationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // 可选：APPLIED | CONFIRMED | REJECTED
	PageId        int32                  `protobuf:"varint,2,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyApplicationsRequest) Reset() {
	*x = GetMyApplicationsRequest{}
	mi := &file_application_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyApplicationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyApplicationsRequest) ProtoMessage() {}

func (x *GetMyApplicationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_application_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyApplicationsRequest.ProtoReflect.Descriptor instead.
func (*GetMyApplicationsRequest) Descriptor() ([]byte, []int) {
	return file_application_proto_rawDescGZIP(), []int{2}
}

func (x *GetMyApplicationsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetMyApplicationsRequest) GetPageId() int32 {
	if x != nil {
		return x.PageId
	}
	return 0
}

func (x *GetMyApplicationsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetMyApplicationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Applications  []*BountyApplication   `protobuf:"bytes,1,rep,name=applications,proto3" json:"applications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyApplicationsResponse) Reset() {
	*x = GetMyApplicationsResponse{}
	mi := &file_application_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyApplicationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyApplicationsResponse) ProtoMessage() {}

func (x *GetMyApplicationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_application_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyApplicationsResponse.ProtoReflect.Descriptor instead.
func (*GetMyApplicationsResponse) Descriptor() ([]byte, []int) {
	return file_application_proto_rawDescGZIP(), []int{3}
}

func (x *GetMyApplicationsResponse) GetApplications() []*BountyApplication {
	if x != nil {
		return x.Applications
	}
	return nil
}

var File_application_proto protoreflect.FileDescriptor

const file_application_proto_rawDesc = "" +
	"\n" +
	"\x11application.proto\x12\x02pb\x1a\fcommon.proto\"^\n" +
	"\x13AcceptBountyRequest\x12\x1b\n" +
	"\tbounty_id\x18\x01 \x01(\x03R\bbountyId\x12*\n" +
	"\x11hunter_account_id\x18\x02 \x01(\x03R\x0fhunterAccountId\"O\n" +
	"\x14AcceptBountyResponse\x127\n" +
	"\vapplication\x18\x01 \x01(\v2\x15.pb.BountyApplicationR\vapplication\"h\n" +
	"\x18GetMyApplicationsRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x17\n" +
	"\apage_id\x18\x02 \x01(\x05R\x06pageId\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"V\n" +
	"\x19GetMyApplicationsResponse\x129\n" +
	"\fapplications\x18\x01 \x03(\v2\x15.pb.BountyApplicationR\fapplicationsB+Z)github.com/grayfalcon666/escrow-bounty/pbb\x06proto3"

var (
	file_application_proto_rawDescOnce sync.Once
	file_application_proto_rawDescData []byte
)

func file_application_proto_rawDescGZIP() []byte {
	file_application_proto_rawDescOnce.Do(func() {
		file_application_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_application_proto_rawDesc), len(file_application_proto_rawDesc)))
	})
	return file_application_proto_rawDescData
}

var file_application_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_application_proto_goTypes = []any{
	(*AcceptBountyRequest)(nil),       // 0: pb.AcceptBountyRequest
	(*AcceptBountyResponse)(nil),      // 1: pb.AcceptBountyResponse
	(*GetMyApplicationsRequest)(nil),  // 2: pb.GetMyApplicationsRequest
	(*GetMyApplicationsResponse)(nil), // 3: pb.GetMyApplicationsResponse
	(*BountyApplication)(nil),         // 4: pb.BountyApplication
}
var file_application_proto_depIdxs = []int32{
	4, // 0: pb.AcceptBountyResponse.application:type_name -> pb.BountyApplication
	4, // 1: pb.GetMyApplicationsResponse.applications:type_name -> pb.BountyApplication
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_application_proto_init() }
func file_application_proto_init() {
	if File_application_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_application_proto_rawDesc), len(file_application_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_application_proto_goTypes,
		DependencyIndexes: file_application_proto_depIdxs,
		MessageInfos:      file_application_proto_msgTypes,
	}.Build()
	File_application_proto = out.File
	file_application_proto_goTypes = nil
	file_application_proto_depIdxs = nil
}
