// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: confirmation.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 雇主选定猎人请求
type ConfirmHunterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BountyId      int64                  `protobuf:"varint,1,opt,name=bounty_id,json=bountyId,proto3" json:"bounty_id,omitempty"`
	ApplicationId int64                  `protobuf:"varint,2,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"` // 选中的那个申请记录 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmHunterRequest) Reset() {
	*x = ConfirmHunterRequest{}
	mi := &file_confirmation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmHunterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmHunterRequest) ProtoMessage() {}

func (x *ConfirmHunterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_confirmation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmHunterRequest.ProtoReflect.Descriptor instead.
func (*ConfirmHunterRequest) Descriptor() ([]byte, []int) {
	return file_confirmation_proto_rawDescGZIP(), []int{0}
}

func (x *ConfirmHunterRequest) GetBountyId() int64 {
	if x != nil {
		return x.BountyId
	}
	return 0
}

func (x *ConfirmHunterRequest) GetApplicationId() int64 {
	if x != nil {
		return x.ApplicationId
	}
	return 0
}

type ConfirmHunterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bounty        *Bounty                `protobuf:"bytes,1,opt,name=bounty,proto3" json:"bounty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmHunterResponse) Reset() {
	*x = ConfirmHunterResponse{}
	mi := &file_confirmation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmHunterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmHunterResponse) ProtoMessage() {}

func (x *ConfirmHunterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_confirmation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmHunterResponse.ProtoReflect.Descriptor instead.
func (*ConfirmHunterResponse) Descriptor() ([]byte, []int) {
	return file_confirmation_proto_rawDescGZIP(), []int{1}
}

func (x *ConfirmHunterResponse) GetBounty() *Bounty {
	if x != nil {
		return x.Bounty
	}
	return nil
}

// 雇主确认验收并打款请求
type CompleteBountyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BountyId      int64                  `protobuf:"varint,1,opt,name=bounty_id,json=bountyId,proto3" json:"bounty_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteBountyRequest) Reset() {
	*x = CompleteBountyRequest{}
	mi := &file_confirmation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteBountyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteBountyRequest) ProtoMessage() {}

func (x *CompleteBountyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_confirmation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteBountyRequest.ProtoReflect.Descriptor instead.
func (*CompleteBountyRequest) Descriptor() ([]byte, []int) {
	return file_confirmation_proto_rawDescGZIP(), []int{2}
}

func (x *CompleteBountyRequest) GetBountyId() int64 {
	if x != nil {
		return x.BountyId
	}
	return 0
}

type CompleteBountyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bounty        *Bounty                `protobuf:"bytes,1,opt,name=bounty,proto3" json:"bounty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteBountyResponse) Reset() {
	*x = CompleteBountyResponse{}
	mi := &file_confirmation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteBountyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteBountyResponse) ProtoMessage() {}

func (x *CompleteBountyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_confirmation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteBountyResponse.ProtoReflect.Descriptor instead.
func (*CompleteBountyResponse) Descriptor() ([]byte, []int) {
	return file_confirmation_proto_rawDescGZIP(), []int{3}
}

func (x *CompleteBountyResponse) GetBounty() *Bounty {
	if x != nil {
		return x.Bounty
	}
	return nil
}

// 雇主取消悬赏的请求和响应
type CancelBountyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BountyId      int64                  `protobuf:"varint,1,opt,name=bounty_id,json=bountyId,proto3" json:"bounty_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBountyRequest) Reset() {
	*x = CancelBountyRequest{}
	mi := &file_confirmation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBountyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBountyRequest) ProtoMessage() {}

func (x *CancelBountyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_confirmation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBountyRequest.ProtoReflect.Descriptor instead.
func (*CancelBountyRequest) Descriptor() ([]byte, []int) {
	return file_confirmation_proto_rawDescGZIP(), []int{4}
}

func (x *CancelBountyRequest) GetBountyId() int64 {
	if x != nil {
		return x.BountyId
	}
	return 0
}

type CancelBountyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bounty        *Bounty                `protobuf:"bytes,1,opt,name=bounty,proto3" json:"bounty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBountyResponse) Reset() {
	*x = CancelBountyResponse{}
	mi := &file_confirmation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBountyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBountyResponse) ProtoMessage() {}

func (x *CancelBountyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_confirmation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBountyResponse.ProtoReflect.Descriptor instead.
func (*CancelBountyResponse) Descriptor() ([]byte, []int) {
	return file_confirmation_proto_rawDescGZIP(), []int{5}
}

func (x *CancelBountyResponse) GetBounty() *Bounty {
	if x != nil {
		return x.Bounty
	}
	return nil
}

var File_confirmation_proto protoreflect.FileDescriptor

const file_confirmation_proto_rawDesc = "" +
	"\n" +
	"\x12confirmation.proto\x12\x02pb\x1a\fcommon.proto\"Z\n" +
	"\x14ConfirmHunterRequest\x12\x1b\n" +
	"\tbounty_id\x18\x01 \x01(\x03R\bbountyId\x12%\n" +
	"\x0eapplication_id\x18\x02 \x01(\x03R\rapplicationId\";\n" +
	"\x15ConfirmHunterResponse\x12\"\n" +
	"\x06bounty\x18\x01 \x01(\v2\n" +
	".pb.BountyR\x06bounty\"4\n" +
	"\x15CompleteBountyRequest\x12\x1b\n" +
	"\tbounty_id\x18\x01 \x01(\x03R\bbountyId\"<\n" +
	"\x16CompleteBountyResponse\x12\"\n" +
	"\x06bounty\x18\x01 \x01(\v2\n" +
	".pb.BountyR\x06bounty\"2\n" +
	"\x13CancelBountyRequest\x12\x1b\n" +
	"\tbounty_id\x18\x01 \x01(\x03R\bbountyId\":\n" +
	"\x14CancelBountyResponse\x12\"\n" +
	"\x06bounty\x18\x01 \x01(\v2\n" +
	".pb.BountyR\x06bountyB+Z)github.com/grayfalcon666/escrow-bounty/pbb\x06proto3"

var (
	file_confirmation_proto_rawDescOnce sync.Once
	file_confirmation_proto_rawDescData []byte
)

func file_confirmation_proto_rawDescGZIP() []byte {
	file_confirmation_proto_rawDescOnce.Do(func() {
		file_confirmation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_confirmation_proto_rawDesc), len(file_confirmation_proto_rawDesc)))
	})
	return file_confirmation_proto_rawDescData
}

var file_confirmation_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_confirmation_proto_goTypes = []any{
	(*ConfirmHunterRequest)(nil),   // 0: pb.ConfirmHunterRequest
	(*ConfirmHunterResponse)(nil),  // 1: pb.ConfirmHunterResponse
	(*CompleteBountyRequest)(nil),  // 2: pb.CompleteBountyRequest
	(*CompleteBountyResponse)(nil), // 3: pb.CompleteBountyResponse
	(*CancelBountyRequest)(nil),    // 4: pb.CancelBountyRequest
	(*CancelBountyResponse)(nil),   // 5: pb.CancelBountyResponse
	(*Bounty)(nil),                 // 6: pb.Bounty
}
var file_confirmation_proto_depIdxs = []int32{
	6, // 0: pb.ConfirmHunterResponse.bounty:type_name -> pb.Bounty
	6, // 1: pb.CompleteBountyResponse.bounty:type_name -> pb.Bounty
	6, // 2: pb.CancelBountyResponse.bounty:type_name -> pb.Bounty
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_confirmation_proto_init() }
func file_confirmation_proto_init() {
	if File_confirmation_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_confirmation_proto_rawDesc), len(file_confirmation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_confirmation_proto_goTypes,
		DependencyIndexes: file_confirmation_proto_depIdxs,
		MessageInfos:      file_confirmation_proto_msgTypes,
	}.Build()
	File_confirmation_proto = out.File
	file_confirmation_proto_goTypes = nil
	file_confirmation_proto_depIdxs = nil
}
