// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: payment.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 充值请求与响应
type CreatePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        int64                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	AccountId     int64                  `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentRequest) Reset() {
	*x = CreatePaymentRequest{}
	mi := &file_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRequest) ProtoMessage() {}

func (x *CreatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePaymentRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreatePaymentRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

type CreatePaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PayUrl        string                 `protobuf:"bytes,1,opt,name=pay_url,json=payUrl,proto3" json:"pay_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentResponse) Reset() {
	*x = CreatePaymentResponse{}
	mi := &file_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentResponse) ProtoMessage() {}

func (x *CreatePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentResponse.ProtoReflect.Descriptor instead.
func (*CreatePaymentResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePaymentResponse) GetPayUrl() string {
	if x != nil {
		return x.PayUrl
	}
	return ""
}

// 提现请求与响应
type CreateWithdrawalRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AccountId      int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount         int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	AlipayAccount  string                 `protobuf:"bytes,3,opt,name=alipay_account,json=alipayAccount,proto3" json:"alipay_account,omitempty"`
	AlipayRealName string                 `protobuf:"bytes,4,opt,name=alipay_real_name,json=alipayRealName,proto3" json:"alipay_real_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateWithdrawalRequest) Reset() {
	*x = CreateWithdrawalRequest{}
	mi := &file_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWithdrawalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWithdrawalRequest) ProtoMessage() {}

func (x *CreateWithdrawalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWithdrawalRequest.ProtoReflect.Descriptor instead.
func (*CreateWithdrawalRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{2}
}

func (x *CreateWithdrawalRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *CreateWithdrawalRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateWithdrawalRequest) GetAlipayAccount() string {
	if x != nil {
		return x.AlipayAccount
	}
	return ""
}

func (x *CreateWithdrawalRequest) GetAlipayRealName() string {
	if x != nil {
		return x.AlipayRealName
	}
	return ""
}

type CreateWithdrawalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	OutBizNo      string                 `protobuf:"bytes,2,opt,name=out_biz_no,json=outBizNo,proto3" json:"out_biz_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWithdrawalResponse) Reset() {
	*x = CreateWithdrawalResponse{}
	mi := &file_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWithdrawalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWithdrawalResponse) ProtoMessage() {}

func (x *CreateWithdrawalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWithdrawalResponse.ProtoReflect.Descriptor instead.
func (*CreateWithdrawalResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{3}
}

func (x *CreateWithdrawalResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateWithdrawalResponse) GetOutBizNo() string {
	if x != nil {
		return x.OutBizNo
	}
	return ""
}

var File_payment_proto protoreflect.FileDescriptor

const file_payment_proto_rawDesc = "" +
	"\n" +
	"\rpayment.proto\x12\x02pb\x1a\x1cgoogle/api/annotations.proto\"M\n" +
	"\x14CreatePaymentRequest\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x03R\x06amount\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x03R\taccountId\"0\n" +
	"\x15CreatePaymentResponse\x12\x17\n" +
	"\apay_url\x18\x01 \x01(\tR\x06payUrl\"\xa1\x01\n" +
	"\x17CreateWithdrawalRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12%\n" +
	"\x0ealipay_account\x18\x03 \x01(\tR\ralipayAccount\x12(\n" +
	"\x10alipay_real_name\x18\x04 \x01(\tR\x0ealipayRealName\"R\n" +
	"\x18CreateWithdrawalResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1c\n" +
	"\n" +
	"out_biz_no\x18\x02 \x01(\tR\boutBizNo2\xe8\x01\n" +
	"\x0ePaymentService\x12d\n" +
	"\rCreatePayment\x12\x18.pb.CreatePaymentRequest\x1a\x19.pb.CreatePaymentResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/payments/create\x12p\n" +
	"\x10CreateWithdrawal\x12\x1b.pb.CreateWithdrawalRequest\x1a\x1c.pb.CreateWithdrawalResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/withdrawals/createB-Z+github.com/grayfalcon666/payment-service/pbb\x06proto3"

var (
	file_payment_proto_rawDescOnce sync.Once
	file_payment_proto_rawDescData []byte
)

func file_payment_proto_rawDescGZIP() []byte {
	file_payment_proto_rawDescOnce.Do(func() {
		file_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)))
	})
	return file_payment_proto_rawDescData
}

var file_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_payment_proto_goTypes = []any{
	(*CreatePaymentRequest)(nil),     // 0: pb.CreatePaymentRequest
	(*CreatePaymentResponse)(nil),    // 1: pb.CreatePaymentResponse
	(*CreateWithdrawalRequest)(nil),  // 2: pb.CreateWithdrawalRequest
	(*CreateWithdrawalResponse)(nil), // 3: pb.CreateWithdrawalResponse
}
var file_payment_proto_depIdxs = []int32{
	0, // 0: pb.PaymentService.CreatePayment:input_type -> pb.CreatePaymentRequest
	2, // 1: pb.PaymentService.CreateWithdrawal:input_type -> pb.CreateWithdrawalRequest
	1, // 2: pb.PaymentService.CreatePayment:output_type -> pb.CreatePaymentResponse
	3, // 3: pb.PaymentService.CreateWithdrawal:output_type -> pb.CreateWithdrawalResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_payment_proto_init() }
func file_payment_proto_init() {
	if File_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_proto_goTypes,
		DependencyIndexes: file_payment_proto_depIdxs,
		MessageInfos:      file_payment_proto_msgTypes,
	}.Build()
	File_payment_proto = out.File
	file_payment_proto_goTypes = nil
	file_payment_proto_depIdxs = nil
}
