// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: service.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\x02pb\x1a\x1cgoogle/api/annotations.proto\x1a\rprofile.proto\x1a\freview.proto2\xaa\b\n" +
	"\x0eProfileService\x12\\\n" +
	"\n" +
	"GetProfile\x12\x15.pb.GetProfileRequest\x1a\x16.pb.GetProfileResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/profiles/{username}\x12]\n" +
	"\rCreateProfile\x12\x18.pb.CreateProfileRequest\x1a\x19.pb.CreateProfileResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/profiles\x12h\n" +
	"\rUpdateProfile\x12\x18.pb.UpdateProfileRequest\x1a\x19.pb.UpdateProfileResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\x1a\x17/v1/profiles/{username}\x12\x88\x01\n" +
	"\x13RefreshProfileStats\x12\x1e.pb.RefreshProfileStatsRequest\x1a\x1f.pb.RefreshProfileStatsResponse\"0\x82\xd3\xe4\x93\x02*:\x01*\"%/v1/admin/profiles/{username}/refresh\x12Y\n" +
	"\fCreateReview\x12\x17.pb.CreateReviewRequest\x1a\x18.pb.CreateReviewResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/reviews\x12a\n" +
	"\n" +
	"GetReviews\x12\x15.pb.GetReviewsRequest\x1a\x16.pb.GetReviewsResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v1/users/{username}/reviews\x12X\n" +
	"\vSearchUsers\x12\x16.pb.SearchUsersRequest\x1a\x17.pb.SearchUsersResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/users/search\x12\x85\x01\n" +
	"\x11InitializeProfile\x12\x1c.pb.InitializeProfileRequest\x1a\x1d.pb.InitializeProfileResponse\"3\x82\xd3\xe4\x93\x02-:\x01*\"(/v1/admin/profiles/{username}/initialize\x12d\n" +
	"\n" +
	"UpdateRole\x12\x15.pb.UpdateRoleRequest\x1a\x16.pb.UpdateRoleResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\x1a\x1c/v1/profiles/{username}/role\x12`\n" +
	"\rSearchHunters\x12\x18.pb.SearchHuntersRequest\x1a\x19.pb.SearchHuntersResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/hunters/searchB2Z0github.com/grayfalcon666/user-profile-service/pbb\x06proto3"

var file_service_proto_goTypes = []any{
	(*GetProfileRequest)(nil),           // 0: pb.GetProfileRequest
	(*CreateProfileRequest)(nil),        // 1: pb.CreateProfileRequest
	(*UpdateProfileRequest)(nil),        // 2: pb.UpdateProfileRequest
	(*RefreshProfileStatsRequest)(nil),  // 3: pb.RefreshProfileStatsRequest
	(*CreateReviewRequest)(nil),         // 4: pb.CreateReviewRequest
	(*GetReviewsRequest)(nil),           // 5: pb.GetReviewsRequest
	(*SearchUsersRequest)(nil),          // 6: pb.SearchUsersRequest
	(*InitializeProfileRequest)(nil),    // 7: pb.InitializeProfileRequest
	(*UpdateRoleRequest)(nil),           // 8: pb.UpdateRoleRequest
	(*SearchHuntersRequest)(nil),        // 9: pb.SearchHuntersRequest
	(*GetProfileResponse)(nil),          // 10: pb.GetProfileResponse
	(*CreateProfileResponse)(nil),       // 11: pb.CreateProfileResponse
	(*UpdateProfileResponse)(nil),       // 12: pb.UpdateProfileResponse
	(*RefreshProfileStatsResponse)(nil), // 13: pb.RefreshProfileStatsResponse
	(*CreateReviewResponse)(nil),        // 14: pb.CreateReviewResponse
	(*GetReviewsResponse)(nil),          // 15: pb.GetReviewsResponse
	(*SearchUsersResponse)(nil),         // 16: pb.SearchUsersResponse
	(*InitializeProfileResponse)(nil),   // 17: pb.InitializeProfileResponse
	(*UpdateRoleResponse)(nil),          // 18: pb.UpdateRoleResponse
	(*SearchHuntersResponse)(nil),       // 19: pb.SearchHuntersResponse
}
var file_service_proto_depIdxs = []int32{
	0,  // 0: pb.ProfileService.GetProfile:input_type -> pb.GetProfileRequest
	1,  // 1: pb.ProfileService.CreateProfile:input_type -> pb.CreateProfileRequest
	2,  // 2: pb.ProfileService.UpdateProfile:input_type -> pb.UpdateProfileRequest
	3,  // 3: pb.ProfileService.RefreshProfileStats:input_type -> pb.RefreshProfileStatsRequest
	4,  // 4: pb.ProfileService.CreateReview:input_type -> pb.CreateReviewRequest
	5,  // 5: pb.ProfileService.GetReviews:input_type -> pb.GetReviewsRequest
	6,  // 6: pb.ProfileService.SearchUsers:input_type -> pb.SearchUsersRequest
	7,  // 7: pb.ProfileService.InitializeProfile:input_type -> pb.InitializeProfileRequest
	8,  // 8: pb.ProfileService.UpdateRole:input_type -> pb.UpdateRoleRequest
	9,  // 9: pb.ProfileService.SearchHunters:input_type -> pb.SearchHuntersRequest
	10, // 10: pb.ProfileService.GetProfile:output_type -> pb.GetProfileResponse
	11, // 11: pb.ProfileService.CreateProfile:output_type -> pb.CreateProfileResponse
	12, // 12: pb.ProfileService.UpdateProfile:output_type -> pb.UpdateProfileResponse
	13, // 13: pb.ProfileService.RefreshProfileStats:output_type -> pb.RefreshProfileStatsResponse
	14, // 14: pb.ProfileService.CreateReview:output_type -> pb.CreateReviewResponse
	15, // 15: pb.ProfileService.GetReviews:output_type -> pb.GetReviewsResponse
	16, // 16: pb.ProfileService.SearchUsers:output_type -> pb.SearchUsersResponse
	17, // 17: pb.ProfileService.InitializeProfile:output_type -> pb.InitializeProfileResponse
	18, // 18: pb.ProfileService.UpdateRole:output_type -> pb.UpdateRoleResponse
	19, // 19: pb.ProfileService.SearchHunters:output_type -> pb.SearchHuntersResponse
	10, // [10:20] is the sub-list for method output_type
	0,  // [0:10] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_profile_proto_init()
	file_review_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
