// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: service.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\x02pb\x1a\x1cgoogle/api/annotations.proto\x1a\fbounty.proto\x1a\x11application.proto\x1a\x12confirmation.proto\x1a\n" +
	"chat.proto2\xff\x18\n" +
	"\x13EscrowBountyService\x12Z\n" +
	"\fCreateBounty\x12\x17.pb.CreateBountyRequest\x1a\x18.pb.CreateBountyResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/bounties\x12W\n" +
	"\fListBounties\x12\x17.pb.ListBountiesRequest\x1a\x18.pb.ListBountiesResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/bounties\x12S\n" +
	"\tGetBounty\x12\x14.pb.GetBountyRequest\x1a\x15.pb.GetBountyResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/bounties/{id}\x12m\n" +
	"\fAcceptBounty\x12\x17.pb.AcceptBountyRequest\x1a\x18.pb.AcceptBountyResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/v1/bounties/{bounty_id}/accept\x12q\n" +
	"\rConfirmHunter\x12\x18.pb.ConfirmHunterRequest\x1a\x19.pb.ConfirmHunterResponse\"+\x82\xd3\xe4\x93\x02%:\x01*\" /v1/bounties/{bounty_id}/confirm\x12u\n" +
	"\x0eCompleteBounty\x12\x19.pb.CompleteBountyRequest\x1a\x1a.pb.CompleteBountyResponse\",\x82\xd3\xe4\x93\x02&:\x01*\"!/v1/bounties/{bounty_id}/complete\x12m\n" +
	"\fSubmitBounty\x12\x17.pb.SubmitBountyRequest\x1a\x18.pb.SubmitBountyResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/v1/bounties/{bounty_id}/submit\x12q\n" +
	"\rApproveBounty\x12\x18.pb.ApproveBountyRequest\x1a\x19.pb.ApproveBountyResponse\"+\x82\xd3\xe4\x93\x02%:\x01*\" /v1/bounties/{bounty_id}/approve\x12m\n" +
	"\fRejectBounty\x12\x17.pb.RejectBountyRequest\x1a\x18.pb.RejectBountyResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/v1/bounties/{bounty_id}/reject\x12m\n" +
	"\fCancelBounty\x12\x17.pb.CancelBountyRequest\x1a\x18.pb.CancelBountyResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/v1/bounties/{bounty_id}/cancel\x12c\n" +
	"\fDeleteBounty\x12\x17.pb.DeleteBountyRequest\x1a\x18.pb.DeleteBountyResponse\" \x82\xd3\xe4\x93\x02\x1a*\x18/v1/bounties/{bounty_id}\x12l\n" +
	"\vSendMessage\x12\x16.pb.SendMessageRequest\x1a\x17.pb.SendMessageResponse\",\x82\xd3\xe4\x93\x02&:\x01*\"!/v1/bounties/{bounty_id}/messages\x12l\n" +
	"\fListMessages\x12\x17.pb.ListMessagesRequest\x1a\x18.pb.ListMessagesResponse\")\x82\xd3\xe4\x93\x02#\x12!/v1/bounties/{bounty_id}/messages\x12\x80\x01\n" +
	"\x17GetOrCreateConversation\x12\".pb.GetOrCreateConversationRequest\x1a#.pb.GetOrCreateConversationResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/conversations\x12k\n" +
	"\x11ListConversations\x12\x1c.pb.ListConversationsRequest\x1a\x1d.pb.ListConversationsResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/conversations\x12\x8c\x01\n" +
	"\x13ListPrivateMessages\x12\x1e.pb.ListPrivateMessagesRequest\x1a\x1f.pb.ListPrivateMessagesResponse\"4\x82\xd3\xe4\x93\x02.\x12,/v1/conversations/{conversation_id}/messages\x12\x80\x01\n" +
	"\x12DeleteConversation\x12\x1d.pb.DeleteConversationRequest\x1a\x1e.pb.DeleteConversationResponse\"+\x82\xd3\xe4\x93\x02%*#/v1/conversations/{conversation_id}\x12o\n" +
	"\x10MarkMessagesRead\x12\x13.pb.MarkReadRequest\x1a\x14.pb.MarkReadResponse\"0\x82\xd3\xe4\x93\x02*\"(/v1/conversations/{conversation_id}/read\x12l\n" +
	"\x0fGetUnreadCounts\x12\x1a.pb.GetUnreadCountsRequest\x1a\x1b.pb.GetUnreadCountsResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/conversations/unread\x12l\n" +
	"\fListComments\x12\x17.pb.ListCommentsRequest\x1a\x18.pb.ListCommentsResponse\")\x82\xd3\xe4\x93\x02#\x12!/v1/bounties/{bounty_id}/comments\x12r\n" +
	"\rCreateComment\x12\x18.pb.CreateCommentRequest\x1a\x19.pb.CreateCommentResponse\",\x82\xd3\xe4\x93\x02&:\x01*\"!/v1/bounties/{bounty_id}/comments\x12g\n" +
	"\rDeleteComment\x12\x18.pb.DeleteCommentRequest\x1a\x19.pb.DeleteCommentResponse\"!\x82\xd3\xe4\x93\x02\x1b*\x19/v1/comments/{comment_id}\x12c\n" +
	"\x10ListUserComments\x12\x1b.pb.ListUserCommentsRequest\x1a\x1c.pb.ListUserCommentsResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/comments\x12~\n" +
	"\x10CreateInvitation\x12\x1b.pb.CreateInvitationRequest\x1a\x1c.pb.CreateInvitationResponse\"/\x82\xd3\xe4\x93\x02):\x01*\"$/v1/bounties/{bounty_id}/invitations\x12o\n" +
	"\x10GetMyInvitations\x12\x1b.pb.GetMyInvitationsRequest\x1a\x1c.pb.GetMyInvitationsResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/invitations/received\x12\x8a\x01\n" +
	"\x13RespondToInvitation\x12\x1e.pb.RespondToInvitationRequest\x1a\x1f.pb.RespondToInvitationResponse\"2\x82\xd3\xe4\x93\x02,:\x01*\"'/v1/invitations/{invitation_id}/respond\x12w\n" +
	"\x14GetMySentInvitations\x12\x1f.pb.GetMySentInvitationsRequest\x1a .pb.GetMySentInvitationsResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/invitations/sent\x12|\n" +
	"\x11GetMyApplications\x12\x1c.pb.GetMyApplicationsRequest\x1a\x1d.pb.GetMyApplicationsResponse\"*\x82\xd3\xe4\x93\x02$\x12\"/v1/bounties/applications/receivedB+Z)github.com/grayfalcon666/escrow-bounty/pbb\x06proto3"

var file_service_proto_goTypes = []any{
	(*CreateBountyRequest)(nil),             // 0: pb.CreateBountyRequest
	(*ListBountiesRequest)(nil),             // 1: pb.ListBountiesRequest
	(*GetBountyRequest)(nil),                // 2: pb.GetBountyRequest
	(*AcceptBountyRequest)(nil),             // 3: pb.AcceptBountyRequest
	(*ConfirmHunterRequest)(nil),            // 4: pb.ConfirmHunterRequest
	(*CompleteBountyRequest)(nil),           // 5: pb.CompleteBountyRequest
	(*SubmitBountyRequest)(nil),             // 6: pb.SubmitBountyRequest
	(*ApproveBountyRequest)(nil),            // 7: pb.ApproveBountyRequest
	(*RejectBountyRequest)(nil),             // 8: pb.RejectBountyRequest
	(*CancelBountyRequest)(nil),             // 9: pb.CancelBountyRequest
	(*DeleteBountyRequest)(nil),             // 10: pb.DeleteBountyRequest
	(*SendMessageRequest)(nil),              // 11: pb.SendMessageRequest
	(*ListMessagesRequest)(nil),             // 12: pb.ListMessagesRequest
	(*GetOrCreateConversationRequest)(nil),  // 13: pb.GetOrCreateConversationRequest
	(*ListConversationsRequest)(nil),        // 14: pb.ListConversationsRequest
	(*ListPrivateMessagesRequest)(nil),      // 15: pb.ListPrivateMessagesRequest
	(*DeleteConversationRequest)(nil),       // 16: pb.DeleteConversationRequest
	(*MarkReadRequest)(nil),                 // 17: pb.MarkReadRequest
	(*GetUnreadCountsRequest)(nil),          // 18: pb.GetUnreadCountsRequest
	(*ListCommentsRequest)(nil),             // 19: pb.ListCommentsRequest
	(*CreateCommentRequest)(nil),            // 20: pb.CreateCommentRequest
	(*DeleteCommentRequest)(nil),            // 21: pb.DeleteCommentRequest
	(*ListUserCommentsRequest)(nil),         // 22: pb.ListUserCommentsRequest
	(*CreateInvitationRequest)(nil),         // 23: pb.CreateInvitationRequest
	(*GetMyInvitationsRequest)(nil),         // 24: pb.GetMyInvitationsRequest
	(*RespondToInvitationRequest)(nil),      // 25: pb.RespondToInvitationRequest
	(*GetMySentInvitationsRequest)(nil),     // 26: pb.GetMySentInvitationsRequest
	(*GetMyApplicationsRequest)(nil),        // 27: pb.GetMyApplicationsRequest
	(*CreateBountyResponse)(nil),            // 28: pb.CreateBountyResponse
	(*ListBountiesResponse)(nil),            // 29: pb.ListBountiesResponse
	(*GetBountyResponse)(nil),               // 30: pb.GetBountyResponse
	(*AcceptBountyResponse)(nil),            // 31: pb.AcceptBountyResponse
	(*ConfirmHunterResponse)(nil),           // 32: pb.ConfirmHunterResponse
	(*CompleteBountyResponse)(nil),          // 33: pb.CompleteBountyResponse
	(*SubmitBountyResponse)(nil),            // 34: pb.SubmitBountyResponse
	(*ApproveBountyResponse)(nil),           // 35: pb.ApproveBountyResponse
	(*RejectBountyResponse)(nil),            // 36: pb.RejectBountyResponse
	(*CancelBountyResponse)(nil),            // 37: pb.CancelBountyResponse
	(*DeleteBountyResponse)(nil),            // 38: pb.DeleteBountyResponse
	(*SendMessageResponse)(nil),             // 39: pb.SendMessageResponse
	(*ListMessagesResponse)(nil),            // 40: pb.ListMessagesResponse
	(*GetOrCreateConversationResponse)(nil), // 41: pb.GetOrCreateConversationResponse
	(*ListConversationsResponse)(nil),       // 42: pb.ListConversationsResponse
	(*ListPrivateMessagesResponse)(nil),     // 43: pb.ListPrivateMessagesResponse
	(*DeleteConversationResponse)(nil),      // 44: pb.DeleteConversationResponse
	(*MarkReadResponse)(nil),                // 45: pb.MarkReadResponse
	(*GetUnreadCountsResponse)(nil),         // 46: pb.GetUnreadCountsResponse
	(*ListCommentsResponse)(nil),            // 47: pb.ListCommentsResponse
	(*CreateCommentResponse)(nil),           // 48: pb.CreateCommentResponse
	(*DeleteCommentResponse)(nil),           // 49: pb.DeleteCommentResponse
	(*ListUserCommentsResponse)(nil),        // 50: pb.ListUserCommentsResponse
	(*CreateInvitationResponse)(nil),        // 51: pb.CreateInvitationResponse
	(*GetMyInvitationsResponse)(nil),        // 52: pb.GetMyInvitationsResponse
	(*RespondToInvitationResponse)(nil),     // 53: pb.RespondToInvitationResponse
	(*GetMySentInvitationsResponse)(nil),    // 54: pb.GetMySentInvitationsResponse
	(*GetMyApplicationsResponse)(nil),       // 55: pb.GetMyApplicationsResponse
}
var file_service_proto_depIdxs = []int32{
	0,  // 0: pb.EscrowBountyService.CreateBounty:input_type -> pb.CreateBountyRequest
	1,  // 1: pb.EscrowBountyService.ListBounties:input_type -> pb.ListBountiesRequest
	2,  // 2: pb.EscrowBountyService.GetBounty:input_type -> pb.GetBountyRequest
	3,  // 3: pb.EscrowBountyService.AcceptBounty:input_type -> pb.AcceptBountyRequest
	4,  // 4: pb.EscrowBountyService.ConfirmHunter:input_type -> pb.ConfirmHunterRequest
	5,  // 5: pb.EscrowBountyService.CompleteBounty:input_type -> pb.CompleteBountyRequest
	6,  // 6: pb.EscrowBountyService.SubmitBounty:input_type -> pb.SubmitBountyRequest
	7,  // 7: pb.EscrowBountyService.ApproveBounty:input_type -> pb.ApproveBountyRequest
	8,  // 8: pb.EscrowBountyService.RejectBounty:input_type -> pb.RejectBountyRequest
	9,  // 9: pb.EscrowBountyService.CancelBounty:input_type -> pb.CancelBountyRequest
	10, // 10: pb.EscrowBountyService.DeleteBounty:input_type -> pb.DeleteBountyRequest
	11, // 11: pb.EscrowBountyService.SendMessage:input_type -> pb.SendMessageRequest
	12, // 12: pb.EscrowBountyService.ListMessages:input_type -> pb.ListMessagesRequest
	13, // 13: pb.EscrowBountyService.GetOrCreateConversation:input_type -> pb.GetOrCreateConversationRequest
	14, // 14: pb.EscrowBountyService.ListConversations:input_type -> pb.ListConversationsRequest
	15, // 15: pb.EscrowBountyService.ListPrivateMessages:input_type -> pb.ListPrivateMessagesRequest
	16, // 16: pb.EscrowBountyService.DeleteConversation:input_type -> pb.DeleteConversationRequest
	17, // 17: pb.EscrowBountyService.MarkMessagesRead:input_type -> pb.MarkReadRequest
	18, // 18: pb.EscrowBountyService.GetUnreadCounts:input_type -> pb.GetUnreadCountsRequest
	19, // 19: pb.EscrowBountyService.ListComments:input_type -> pb.ListCommentsRequest
	20, // 20: pb.EscrowBountyService.CreateComment:input_type -> pb.CreateCommentRequest
	21, // 21: pb.EscrowBountyService.DeleteComment:input_type -> pb.DeleteCommentRequest
	22, // 22: pb.EscrowBountyService.ListUserComments:input_type -> pb.ListUserCommentsRequest
	23, // 23: pb.EscrowBountyService.CreateInvitation:input_type -> pb.CreateInvitationRequest
	24, // 24: pb.EscrowBountyService.GetMyInvitations:input_type -> pb.GetMyInvitationsRequest
	25, // 25: pb.EscrowBountyService.RespondToInvitation:input_type -> pb.RespondToInvitationRequest
	26, // 26: pb.EscrowBountyService.GetMySentInvitations:input_type -> pb.GetMySentInvitationsRequest
	27, // 27: pb.EscrowBountyService.GetMyApplications:input_type -> pb.GetMyApplicationsRequest
	28, // 28: pb.EscrowBountyService.CreateBounty:output_type -> pb.CreateBountyResponse
	29, // 29: pb.EscrowBountyService.ListBounties:output_type -> pb.ListBountiesResponse
	30, // 30: pb.EscrowBountyService.GetBounty:output_type -> pb.GetBountyResponse
	31, // 31: pb.EscrowBountyService.AcceptBounty:output_type -> pb.AcceptBountyResponse
	32, // 32: pb.EscrowBountyService.ConfirmHunter:output_type -> pb.ConfirmHunterResponse
	33, // 33: pb.EscrowBountyService.CompleteBounty:output_type -> pb.CompleteBountyResponse
	34, // 34: pb.EscrowBountyService.SubmitBounty:output_type -> pb.SubmitBountyResponse
	35, // 35: pb.EscrowBountyService.ApproveBounty:output_type -> pb.ApproveBountyResponse
	36, // 36: pb.EscrowBountyService.RejectBounty:output_type -> pb.RejectBountyResponse
	37, // 37: pb.EscrowBountyService.CancelBounty:output_type -> pb.CancelBountyResponse
	38, // 38: pb.EscrowBountyService.DeleteBounty:output_type -> pb.DeleteBountyResponse
	39, // 39: pb.EscrowBountyService.SendMessage:output_type -> pb.SendMessageResponse
	40, // 40: pb.EscrowBountyService.ListMessages:output_type -> pb.ListMessagesResponse
	41, // 41: pb.EscrowBountyService.GetOrCreateConversation:output_type -> pb.GetOrCreateConversationResponse
	42, // 42: pb.EscrowBountyService.ListConversations:output_type -> pb.ListConversationsResponse
	43, // 43: pb.EscrowBountyService.ListPrivateMessages:output_type -> pb.ListPrivateMessagesResponse
	44, // 44: pb.EscrowBountyService.DeleteConversation:output_type -> pb.DeleteConversationResponse
	45, // 45: pb.EscrowBountyService.MarkMessagesRead:output_type -> pb.MarkReadResponse
	46, // 46: pb.EscrowBountyService.GetUnreadCounts:output_type -> pb.GetUnreadCountsResponse
	47, // 47: pb.EscrowBountyService.ListComments:output_type -> pb.ListCommentsResponse
	48, // 48: pb.EscrowBountyService.CreateComment:output_type -> pb.CreateCommentResponse
	49, // 49: pb.EscrowBountyService.DeleteComment:output_type -> pb.DeleteCommentResponse
	50, // 50: pb.EscrowBountyService.ListUserComments:output_type -> pb.ListUserCommentsResponse
	51, // 51: pb.EscrowBountyService.CreateInvitation:output_type -> pb.CreateInvitationResponse
	52, // 52: pb.EscrowBountyService.GetMyInvitations:output_type -> pb.GetMyInvitationsResponse
	53, // 53: pb.EscrowBountyService.RespondToInvitation:output_type -> pb.RespondToInvitationResponse
	54, // 54: pb.EscrowBountyService.GetMySentInvitations:output_type -> pb.GetMySentInvitationsResponse
	55, // 55: pb.EscrowBountyService.GetMyApplications:output_type -> pb.GetMyApplicationsResponse
	28, // [28:56] is the sub-list for method output_type
	0,  // [0:28] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_bounty_proto_init()
	file_application_proto_init()
	file_confirmation_proto_init()
	file_chat_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
