// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: user_events.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 用户创建事件
type UserCreatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FullName      string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // 幂等键
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCreatedEvent) Reset() {
	*x = UserCreatedEvent{}
	mi := &file_user_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCreatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCreatedEvent) ProtoMessage() {}

func (x *UserCreatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_user_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCreatedEvent.ProtoReflect.Descriptor instead.
func (*UserCreatedEvent) Descriptor() ([]byte, []int) {
	return file_user_events_proto_rawDescGZIP(), []int{0}
}

func (x *UserCreatedEvent) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserCreatedEvent) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserCreatedEvent) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *UserCreatedEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *UserCreatedEvent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// 用户资料创建事件
type ProfileCreatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileCreatedEvent) Reset() {
	*x = ProfileCreatedEvent{}
	mi := &file_user_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileCreatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileCreatedEvent) ProtoMessage() {}

func (x *ProfileCreatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_user_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileCreatedEvent.ProtoReflect.Descriptor instead.
func (*ProfileCreatedEvent) Descriptor() ([]byte, []int) {
	return file_user_events_proto_rawDescGZIP(), []int{1}
}

func (x *ProfileCreatedEvent) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ProfileCreatedEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ProfileCreatedEvent) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProfileCreatedEvent) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// 账户创建事件
type AccountCreatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	AccountId     int64                  `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountCreatedEvent) Reset() {
	*x = AccountCreatedEvent{}
	mi := &file_user_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountCreatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountCreatedEvent) ProtoMessage() {}

func (x *AccountCreatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_user_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountCreatedEvent.ProtoReflect.Descriptor instead.
func (*AccountCreatedEvent) Descriptor() ([]byte, []int) {
	return file_user_events_proto_rawDescGZIP(), []int{2}
}

func (x *AccountCreatedEvent) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AccountCreatedEvent) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *AccountCreatedEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AccountCreatedEvent) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AccountCreatedEvent) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// 用户初始化完成事件
type UserInitializationCompletedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // INITIALIZED, FAILED, PARTIALLY_INITIALIZED
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInitializationCompletedEvent) Reset() {
	*x = UserInitializationCompletedEvent{}
	mi := &file_user_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInitializationCompletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInitializationCompletedEvent) ProtoMessage() {}

func (x *UserInitializationCompletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_user_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInitializationCompletedEvent.ProtoReflect.Descriptor instead.
func (*UserInitializationCompletedEvent) Descriptor() ([]byte, []int) {
	return file_user_events_proto_rawDescGZIP(), []int{3}
}

func (x *UserInitializationCompletedEvent) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserInitializationCompletedEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *UserInitializationCompletedEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_user_events_proto protoreflect.FileDescriptor

const file_user_events_proto_rawDesc = "" +
	"\n" +
	"\x11user_events.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbb\x01\n" +
	"\x10UserCreatedEvent\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x8f\x01\n" +
	"\x13ProfileCreatedEvent\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"\xae\x01\n" +
	"\x13AccountCreatedEvent\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x03R\taccountId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"u\n" +
	" UserInitializationCompletedEvent\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06statusB2Z0github.com/grayfalcon666/user-profile-service/pbb\x06proto3"

var (
	file_user_events_proto_rawDescOnce sync.Once
	file_user_events_proto_rawDescData []byte
)

func file_user_events_proto_rawDescGZIP() []byte {
	file_user_events_proto_rawDescOnce.Do(func() {
		file_user_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_events_proto_rawDesc), len(file_user_events_proto_rawDesc)))
	})
	return file_user_events_proto_rawDescData
}

var file_user_events_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_user_events_proto_goTypes = []any{
	(*UserCreatedEvent)(nil),                 // 0: pb.UserCreatedEvent
	(*ProfileCreatedEvent)(nil),              // 1: pb.ProfileCreatedEvent
	(*AccountCreatedEvent)(nil),              // 2: pb.AccountCreatedEvent
	(*UserInitializationCompletedEvent)(nil), // 3: pb.UserInitializationCompletedEvent
	(*timestamppb.Timestamp)(nil),            // 4: google.protobuf.Timestamp
}
var file_user_events_proto_depIdxs = []int32{
	4, // 0: pb.UserCreatedEvent.created_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_user_events_proto_init() }
func file_user_events_proto_init() {
	if File_user_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_events_proto_rawDesc), len(file_user_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_events_proto_goTypes,
		DependencyIndexes: file_user_events_proto_depIdxs,
		MessageInfos:      file_user_events_proto_msgTypes,
	}.Build()
	File_user_events_proto = out.File
	file_user_events_proto_goTypes = nil
	file_user_events_proto_depIdxs = nil
}
