// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/grayfalcon666/escrow-bounty/db (interfaces: Store,BankClient)
//
// Generated by this command:
//
//	mockgen -package mockdb -destination db/mock/store.go github.com/grayfalcon666/escrow-bounty/db Store,BankClient
//

// Package mockdb is a generated GoMock package.
package mockdb

import (
	context "context"
	reflect "reflect"

	db "github.com/grayfalcon666/escrow-bounty/db"
	models "github.com/grayfalcon666/escrow-bounty/models"
	pb "github.com/grayfalcon666/escrow-bounty/simplebankpb"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// AcceptBounty mocks base method.
func (m *MockStore) AcceptBounty(ctx context.Context, bountyID, hunter_account_id int64, hunterUsername string) (*models.BountyApplication, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptBounty", ctx, bountyID, hunter_account_id, hunterUsername)
	ret0, _ := ret[0].(*models.BountyApplication)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AcceptBounty indicates an expected call of AcceptBounty.
func (mr *MockStoreMockRecorder) AcceptBounty(ctx, bountyID, hunter_account_id, hunterUsername any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptBounty", reflect.TypeOf((*MockStore)(nil).AcceptBounty), ctx, bountyID, hunter_account_id, hunterUsername)
}

// ApproveBounty mocks base method.
func (m *MockStore) ApproveBounty(ctx context.Context, bountyID int64, employerUsername string, bankClient db.BankClient) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApproveBounty", ctx, bountyID, employerUsername, bankClient)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApproveBounty indicates an expected call of ApproveBounty.
func (mr *MockStoreMockRecorder) ApproveBounty(ctx, bountyID, employerUsername, bankClient any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApproveBounty", reflect.TypeOf((*MockStore)(nil).ApproveBounty), ctx, bountyID, employerUsername, bankClient)
}

// CancelBounty mocks base method.
func (m *MockStore) CancelBounty(ctx context.Context, bountyID int64, employerUsername string, bankClient db.BankClient) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelBounty", ctx, bountyID, employerUsername, bankClient)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelBounty indicates an expected call of CancelBounty.
func (mr *MockStoreMockRecorder) CancelBounty(ctx, bountyID, employerUsername, bankClient any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelBounty", reflect.TypeOf((*MockStore)(nil).CancelBounty), ctx, bountyID, employerUsername, bankClient)
}

// CompleteBounty mocks base method.
func (m *MockStore) CompleteBounty(ctx context.Context, bountyID int64, employerUsername string, bankClient db.BankClient) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteBounty", ctx, bountyID, employerUsername, bankClient)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteBounty indicates an expected call of CompleteBounty.
func (mr *MockStoreMockRecorder) CompleteBounty(ctx, bountyID, employerUsername, bankClient any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteBounty", reflect.TypeOf((*MockStore)(nil).CompleteBounty), ctx, bountyID, employerUsername, bankClient)
}

// ConfirmHunter mocks base method.
func (m *MockStore) ConfirmHunter(ctx context.Context, bountyID, applicationID int64, employerUsername string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmHunter", ctx, bountyID, applicationID, employerUsername)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfirmHunter indicates an expected call of ConfirmHunter.
func (mr *MockStoreMockRecorder) ConfirmHunter(ctx, bountyID, applicationID, employerUsername any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmHunter", reflect.TypeOf((*MockStore)(nil).ConfirmHunter), ctx, bountyID, applicationID, employerUsername)
}

// CreateApplication mocks base method.
func (m *MockStore) CreateApplication(ctx context.Context, app *models.BountyApplication) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateApplication", ctx, app)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateApplication indicates an expected call of CreateApplication.
func (mr *MockStoreMockRecorder) CreateApplication(ctx, app any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateApplication", reflect.TypeOf((*MockStore)(nil).CreateApplication), ctx, app)
}

// CreateBounty mocks base method.
func (m *MockStore) CreateBounty(ctx context.Context, bounty *models.Bounty) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBounty", ctx, bounty)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBounty indicates an expected call of CreateBounty.
func (mr *MockStoreMockRecorder) CreateBounty(ctx, bounty any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBounty", reflect.TypeOf((*MockStore)(nil).CreateBounty), ctx, bounty)
}

// CreateComment mocks base method.
func (m *MockStore) CreateComment(ctx context.Context, bountyID int64, parentID *int64, authorUsername, content string) (*models.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateComment", ctx, bountyID, parentID, authorUsername, content)
	ret0, _ := ret[0].(*models.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateComment indicates an expected call of CreateComment.
func (mr *MockStoreMockRecorder) CreateComment(ctx, bountyID, parentID, authorUsername, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateComment", reflect.TypeOf((*MockStore)(nil).CreateComment), ctx, bountyID, parentID, authorUsername, content)
}

// CreateInvitation mocks base method.
func (m *MockStore) CreateInvitation(ctx context.Context, inv *models.Invitation) (*models.Invitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInvitation", ctx, inv)
	ret0, _ := ret[0].(*models.Invitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInvitation indicates an expected call of CreateInvitation.
func (mr *MockStoreMockRecorder) CreateInvitation(ctx, inv any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInvitation", reflect.TypeOf((*MockStore)(nil).CreateInvitation), ctx, inv)
}

// CreateMessage mocks base method.
func (m *MockStore) CreateMessage(ctx context.Context, chatID int64, senderUsername, content string) (*models.ChatMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMessage", ctx, chatID, senderUsername, content)
	ret0, _ := ret[0].(*models.ChatMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMessage indicates an expected call of CreateMessage.
func (mr *MockStoreMockRecorder) CreateMessage(ctx, chatID, senderUsername, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMessage", reflect.TypeOf((*MockStore)(nil).CreateMessage), ctx, chatID, senderUsername, content)
}

// CreateMessageV2 mocks base method.
func (m *MockStore) CreateMessageV2(ctx context.Context, msgType string, convID, bountyChatID *int64, senderUsername, content string) (*models.AllMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMessageV2", ctx, msgType, convID, bountyChatID, senderUsername, content)
	ret0, _ := ret[0].(*models.AllMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMessageV2 indicates an expected call of CreateMessageV2.
func (mr *MockStoreMockRecorder) CreateMessageV2(ctx, msgType, convID, bountyChatID, senderUsername, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMessageV2", reflect.TypeOf((*MockStore)(nil).CreateMessageV2), ctx, msgType, convID, bountyChatID, senderUsername, content)
}

// DeleteBounty mocks base method.
func (m *MockStore) DeleteBounty(ctx context.Context, bountyID int64, employerUsername string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBounty", ctx, bountyID, employerUsername)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBounty indicates an expected call of DeleteBounty.
func (mr *MockStoreMockRecorder) DeleteBounty(ctx, bountyID, employerUsername any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBounty", reflect.TypeOf((*MockStore)(nil).DeleteBounty), ctx, bountyID, employerUsername)
}

// DeleteComment mocks base method.
func (m *MockStore) DeleteComment(ctx context.Context, commentID int64, username string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteComment", ctx, commentID, username)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteComment indicates an expected call of DeleteComment.
func (mr *MockStoreMockRecorder) DeleteComment(ctx, commentID, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteComment", reflect.TypeOf((*MockStore)(nil).DeleteComment), ctx, commentID, username)
}

// DeleteInvitation mocks base method.
func (m *MockStore) DeleteInvitation(ctx context.Context, id int64, posterUsername string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInvitation", ctx, id, posterUsername)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteInvitation indicates an expected call of DeleteInvitation.
func (mr *MockStoreMockRecorder) DeleteInvitation(ctx, id, posterUsername any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInvitation", reflect.TypeOf((*MockStore)(nil).DeleteInvitation), ctx, id, posterUsername)
}

// DeletePrivateConversation mocks base method.
func (m *MockStore) DeletePrivateConversation(ctx context.Context, convID int64, username string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePrivateConversation", ctx, convID, username)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePrivateConversation indicates an expected call of DeletePrivateConversation.
func (mr *MockStoreMockRecorder) DeletePrivateConversation(ctx, convID, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePrivateConversation", reflect.TypeOf((*MockStore)(nil).DeletePrivateConversation), ctx, convID, username)
}

// ExpireBounty mocks base method.
func (m *MockStore) ExpireBounty(ctx context.Context, bountyID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExpireBounty", ctx, bountyID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExpireBounty indicates an expected call of ExpireBounty.
func (mr *MockStoreMockRecorder) ExpireBounty(ctx, bountyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExpireBounty", reflect.TypeOf((*MockStore)(nil).ExpireBounty), ctx, bountyID)
}

// GetBountyByID mocks base method.
func (m *MockStore) GetBountyByID(ctx context.Context, id int64) (*models.Bounty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBountyByID", ctx, id)
	ret0, _ := ret[0].(*models.Bounty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBountyByID indicates an expected call of GetBountyByID.
func (mr *MockStoreMockRecorder) GetBountyByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBountyByID", reflect.TypeOf((*MockStore)(nil).GetBountyByID), ctx, id)
}

// GetInvitationByID mocks base method.
func (m *MockStore) GetInvitationByID(ctx context.Context, id int64) (*models.Invitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInvitationByID", ctx, id)
	ret0, _ := ret[0].(*models.Invitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInvitationByID indicates an expected call of GetInvitationByID.
func (mr *MockStoreMockRecorder) GetInvitationByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInvitationByID", reflect.TypeOf((*MockStore)(nil).GetInvitationByID), ctx, id)
}

// GetOrCreateChat mocks base method.
func (m *MockStore) GetOrCreateChat(ctx context.Context, bountyID int64) (*models.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreateChat", ctx, bountyID)
	ret0, _ := ret[0].(*models.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrCreateChat indicates an expected call of GetOrCreateChat.
func (mr *MockStoreMockRecorder) GetOrCreateChat(ctx, bountyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreateChat", reflect.TypeOf((*MockStore)(nil).GetOrCreateChat), ctx, bountyID)
}

// GetOrCreatePrivateConversation mocks base method.
func (m *MockStore) GetOrCreatePrivateConversation(ctx context.Context, user1, user2 string) (*models.PrivateConversation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreatePrivateConversation", ctx, user1, user2)
	ret0, _ := ret[0].(*models.PrivateConversation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrCreatePrivateConversation indicates an expected call of GetOrCreatePrivateConversation.
func (mr *MockStoreMockRecorder) GetOrCreatePrivateConversation(ctx, user1, user2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreatePrivateConversation", reflect.TypeOf((*MockStore)(nil).GetOrCreatePrivateConversation), ctx, user1, user2)
}

// GetPendingFulfillmentOutbox mocks base method.
func (m *MockStore) GetPendingFulfillmentOutbox(ctx context.Context, limit int) ([]models.FulfillmentOutbox, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingFulfillmentOutbox", ctx, limit)
	ret0, _ := ret[0].([]models.FulfillmentOutbox)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingFulfillmentOutbox indicates an expected call of GetPendingFulfillmentOutbox.
func (mr *MockStoreMockRecorder) GetPendingFulfillmentOutbox(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingFulfillmentOutbox", reflect.TypeOf((*MockStore)(nil).GetPendingFulfillmentOutbox), ctx, limit)
}

// GetPendingOutboxEntries mocks base method.
func (m *MockStore) GetPendingOutboxEntries(ctx context.Context, limit int) ([]models.ProfileUpdateOutbox, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingOutboxEntries", ctx, limit)
	ret0, _ := ret[0].([]models.ProfileUpdateOutbox)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingOutboxEntries indicates an expected call of GetPendingOutboxEntries.
func (mr *MockStoreMockRecorder) GetPendingOutboxEntries(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingOutboxEntries", reflect.TypeOf((*MockStore)(nil).GetPendingOutboxEntries), ctx, limit)
}

// GetUnreadCounts mocks base method.
func (m *MockStore) GetUnreadCounts(ctx context.Context, username string) (map[int64]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnreadCounts", ctx, username)
	ret0, _ := ret[0].(map[int64]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnreadCounts indicates an expected call of GetUnreadCounts.
func (mr *MockStoreMockRecorder) GetUnreadCounts(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnreadCounts", reflect.TypeOf((*MockStore)(nil).GetUnreadCounts), ctx, username)
}

// ListApplicationsByHunter mocks base method.
func (m *MockStore) ListApplicationsByHunter(ctx context.Context, hunterUsername string, status models.ApplicationStatus, limit, offset int) ([]models.BountyApplication, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListApplicationsByHunter", ctx, hunterUsername, status, limit, offset)
	ret0, _ := ret[0].([]models.BountyApplication)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListApplicationsByHunter indicates an expected call of ListApplicationsByHunter.
func (mr *MockStoreMockRecorder) ListApplicationsByHunter(ctx, hunterUsername, status, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListApplicationsByHunter", reflect.TypeOf((*MockStore)(nil).ListApplicationsByHunter), ctx, hunterUsername, status, limit, offset)
}

// ListBounties mocks base method.
func (m *MockStore) ListBounties(ctx context.Context, status models.BountyStatus, limit, offset int) ([]models.Bounty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBounties", ctx, status, limit, offset)
	ret0, _ := ret[0].([]models.Bounty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBounties indicates an expected call of ListBounties.
func (mr *MockStoreMockRecorder) ListBounties(ctx, status, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBounties", reflect.TypeOf((*MockStore)(nil).ListBounties), ctx, status, limit, offset)
}

// ListBountyMessagesV2 mocks base method.
func (m *MockStore) ListBountyMessagesV2(ctx context.Context, bountyChatID int64, limit, offset int) ([]models.AllMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBountyMessagesV2", ctx, bountyChatID, limit, offset)
	ret0, _ := ret[0].([]models.AllMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBountyMessagesV2 indicates an expected call of ListBountyMessagesV2.
func (mr *MockStoreMockRecorder) ListBountyMessagesV2(ctx, bountyChatID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBountyMessagesV2", reflect.TypeOf((*MockStore)(nil).ListBountyMessagesV2), ctx, bountyChatID, limit, offset)
}

// ListComments mocks base method.
func (m *MockStore) ListComments(ctx context.Context, bountyID int64) ([]models.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListComments", ctx, bountyID)
	ret0, _ := ret[0].([]models.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListComments indicates an expected call of ListComments.
func (mr *MockStoreMockRecorder) ListComments(ctx, bountyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListComments", reflect.TypeOf((*MockStore)(nil).ListComments), ctx, bountyID)
}

// ListCommentsByUsername mocks base method.
func (m *MockStore) ListCommentsByUsername(ctx context.Context, username string, limit, offset int) ([]models.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCommentsByUsername", ctx, username, limit, offset)
	ret0, _ := ret[0].([]models.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCommentsByUsername indicates an expected call of ListCommentsByUsername.
func (mr *MockStoreMockRecorder) ListCommentsByUsername(ctx, username, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCommentsByUsername", reflect.TypeOf((*MockStore)(nil).ListCommentsByUsername), ctx, username, limit, offset)
}

// ListExpiredBounties mocks base method.
func (m *MockStore) ListExpiredBounties(ctx context.Context, limit int) ([]models.Bounty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListExpiredBounties", ctx, limit)
	ret0, _ := ret[0].([]models.Bounty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListExpiredBounties indicates an expected call of ListExpiredBounties.
func (mr *MockStoreMockRecorder) ListExpiredBounties(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExpiredBounties", reflect.TypeOf((*MockStore)(nil).ListExpiredBounties), ctx, limit)
}

// ListInvitationsByHunter mocks base method.
func (m *MockStore) ListInvitationsByHunter(ctx context.Context, hunterUsername string, status models.InvitationStatus, limit, offset int) ([]models.Invitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInvitationsByHunter", ctx, hunterUsername, status, limit, offset)
	ret0, _ := ret[0].([]models.Invitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInvitationsByHunter indicates an expected call of ListInvitationsByHunter.
func (mr *MockStoreMockRecorder) ListInvitationsByHunter(ctx, hunterUsername, status, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInvitationsByHunter", reflect.TypeOf((*MockStore)(nil).ListInvitationsByHunter), ctx, hunterUsername, status, limit, offset)
}

// ListInvitationsByPoster mocks base method.
func (m *MockStore) ListInvitationsByPoster(ctx context.Context, posterUsername string, bountyID *int64, status models.InvitationStatus, limit, offset int) ([]models.Invitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInvitationsByPoster", ctx, posterUsername, bountyID, status, limit, offset)
	ret0, _ := ret[0].([]models.Invitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInvitationsByPoster indicates an expected call of ListInvitationsByPoster.
func (mr *MockStoreMockRecorder) ListInvitationsByPoster(ctx, posterUsername, bountyID, status, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInvitationsByPoster", reflect.TypeOf((*MockStore)(nil).ListInvitationsByPoster), ctx, posterUsername, bountyID, status, limit, offset)
}

// ListMessages mocks base method.
func (m *MockStore) ListMessages(ctx context.Context, bountyID int64) ([]models.ChatMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMessages", ctx, bountyID)
	ret0, _ := ret[0].([]models.ChatMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMessages indicates an expected call of ListMessages.
func (mr *MockStoreMockRecorder) ListMessages(ctx, bountyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMessages", reflect.TypeOf((*MockStore)(nil).ListMessages), ctx, bountyID)
}

// ListMessagesV2 mocks base method.
func (m *MockStore) ListMessagesV2(ctx context.Context, convID int64, limit, offset int) ([]models.AllMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMessagesV2", ctx, convID, limit, offset)
	ret0, _ := ret[0].([]models.AllMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMessagesV2 indicates an expected call of ListMessagesV2.
func (mr *MockStoreMockRecorder) ListMessagesV2(ctx, convID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMessagesV2", reflect.TypeOf((*MockStore)(nil).ListMessagesV2), ctx, convID, limit, offset)
}

// ListPrivateConversations mocks base method.
func (m *MockStore) ListPrivateConversations(ctx context.Context, username string) ([]models.PrivateConversation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPrivateConversations", ctx, username)
	ret0, _ := ret[0].([]models.PrivateConversation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPrivateConversations indicates an expected call of ListPrivateConversations.
func (mr *MockStoreMockRecorder) ListPrivateConversations(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPrivateConversations", reflect.TypeOf((*MockStore)(nil).ListPrivateConversations), ctx, username)
}

// MarkFulfillmentOutboxCompleted mocks base method.
func (m *MockStore) MarkFulfillmentOutboxCompleted(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkFulfillmentOutboxCompleted", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkFulfillmentOutboxCompleted indicates an expected call of MarkFulfillmentOutboxCompleted.
func (mr *MockStoreMockRecorder) MarkFulfillmentOutboxCompleted(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkFulfillmentOutboxCompleted", reflect.TypeOf((*MockStore)(nil).MarkFulfillmentOutboxCompleted), ctx, id)
}

// MarkFulfillmentOutboxFailed mocks base method.
func (m *MockStore) MarkFulfillmentOutboxFailed(ctx context.Context, id int64, errMsg string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkFulfillmentOutboxFailed", ctx, id, errMsg)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkFulfillmentOutboxFailed indicates an expected call of MarkFulfillmentOutboxFailed.
func (mr *MockStoreMockRecorder) MarkFulfillmentOutboxFailed(ctx, id, errMsg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkFulfillmentOutboxFailed", reflect.TypeOf((*MockStore)(nil).MarkFulfillmentOutboxFailed), ctx, id, errMsg)
}

// MarkMessagesRead mocks base method.
func (m *MockStore) MarkMessagesRead(ctx context.Context, convID int64, readerUsername string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkMessagesRead", ctx, convID, readerUsername)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkMessagesRead indicates an expected call of MarkMessagesRead.
func (mr *MockStoreMockRecorder) MarkMessagesRead(ctx, convID, readerUsername any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkMessagesRead", reflect.TypeOf((*MockStore)(nil).MarkMessagesRead), ctx, convID, readerUsername)
}

// MarkOutboxCompleted mocks base method.
func (m *MockStore) MarkOutboxCompleted(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkOutboxCompleted", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkOutboxCompleted indicates an expected call of MarkOutboxCompleted.
func (mr *MockStoreMockRecorder) MarkOutboxCompleted(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkOutboxCompleted", reflect.TypeOf((*MockStore)(nil).MarkOutboxCompleted), ctx, id)
}

// MarkOutboxFailed mocks base method.
func (m *MockStore) MarkOutboxFailed(ctx context.Context, id int64, errMsg string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkOutboxFailed", ctx, id, errMsg)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkOutboxFailed indicates an expected call of MarkOutboxFailed.
func (mr *MockStoreMockRecorder) MarkOutboxFailed(ctx, id, errMsg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkOutboxFailed", reflect.TypeOf((*MockStore)(nil).MarkOutboxFailed), ctx, id, errMsg)
}

// PublishBounty mocks base method.
func (m *MockStore) PublishBounty(ctx context.Context, bounty *models.Bounty, bankClient db.BankClient, employerAccountID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishBounty", ctx, bounty, bankClient, employerAccountID)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishBounty indicates an expected call of PublishBounty.
func (mr *MockStoreMockRecorder) PublishBounty(ctx, bounty, bankClient, employerAccountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishBounty", reflect.TypeOf((*MockStore)(nil).PublishBounty), ctx, bounty, bankClient, employerAccountID)
}

// PublishFulfillmentRecalc mocks base method.
func (m *MockStore) PublishFulfillmentRecalc(ctx context.Context, username, role string, bountyID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishFulfillmentRecalc", ctx, username, role, bountyID)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishFulfillmentRecalc indicates an expected call of PublishFulfillmentRecalc.
func (mr *MockStoreMockRecorder) PublishFulfillmentRecalc(ctx, username, role, bountyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishFulfillmentRecalc", reflect.TypeOf((*MockStore)(nil).PublishFulfillmentRecalc), ctx, username, role, bountyID)
}

// PublishProfileUpdate mocks base method.
func (m *MockStore) PublishProfileUpdate(ctx context.Context, outbox *models.ProfileUpdateOutbox) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishProfileUpdate", ctx, outbox)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishProfileUpdate indicates an expected call of PublishProfileUpdate.
func (mr *MockStoreMockRecorder) PublishProfileUpdate(ctx, outbox any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishProfileUpdate", reflect.TypeOf((*MockStore)(nil).PublishProfileUpdate), ctx, outbox)
}

// ReSubmitBounty mocks base method.
func (m *MockStore) ReSubmitBounty(ctx context.Context, bountyID int64, hunterUsername, submissionText string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReSubmitBounty", ctx, bountyID, hunterUsername, submissionText)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReSubmitBounty indicates an expected call of ReSubmitBounty.
func (mr *MockStoreMockRecorder) ReSubmitBounty(ctx, bountyID, hunterUsername, submissionText any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReSubmitBounty", reflect.TypeOf((*MockStore)(nil).ReSubmitBounty), ctx, bountyID, hunterUsername, submissionText)
}

// RejectBounty mocks base method.
func (m *MockStore) RejectBounty(ctx context.Context, bountyID int64, employerUsername string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RejectBounty", ctx, bountyID, employerUsername)
	ret0, _ := ret[0].(error)
	return ret0
}

// RejectBounty indicates an expected call of RejectBounty.
func (mr *MockStoreMockRecorder) RejectBounty(ctx, bountyID, employerUsername any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RejectBounty", reflect.TypeOf((*MockStore)(nil).RejectBounty), ctx, bountyID, employerUsername)
}

// SubmitBounty mocks base method.
func (m *MockStore) SubmitBounty(ctx context.Context, bountyID int64, hunterUsername, submissionText string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitBounty", ctx, bountyID, hunterUsername, submissionText)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubmitBounty indicates an expected call of SubmitBounty.
func (mr *MockStoreMockRecorder) SubmitBounty(ctx, bountyID, hunterUsername, submissionText any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitBounty", reflect.TypeOf((*MockStore)(nil).SubmitBounty), ctx, bountyID, hunterUsername, submissionText)
}

// UpdateApplicationStatus mocks base method.
func (m *MockStore) UpdateApplicationStatus(ctx context.Context, applicationID int64, status models.ApplicationStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateApplicationStatus", ctx, applicationID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateApplicationStatus indicates an expected call of UpdateApplicationStatus.
func (mr *MockStoreMockRecorder) UpdateApplicationStatus(ctx, applicationID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateApplicationStatus", reflect.TypeOf((*MockStore)(nil).UpdateApplicationStatus), ctx, applicationID, status)
}

// UpdateBountyStatus mocks base method.
func (m *MockStore) UpdateBountyStatus(ctx context.Context, id int64, status models.BountyStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBountyStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBountyStatus indicates an expected call of UpdateBountyStatus.
func (mr *MockStoreMockRecorder) UpdateBountyStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBountyStatus", reflect.TypeOf((*MockStore)(nil).UpdateBountyStatus), ctx, id, status)
}

// UpdateInvitationStatus mocks base method.
func (m *MockStore) UpdateInvitationStatus(ctx context.Context, id int64, status models.InvitationStatus) (*models.Invitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInvitationStatus", ctx, id, status)
	ret0, _ := ret[0].(*models.Invitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateInvitationStatus indicates an expected call of UpdateInvitationStatus.
func (mr *MockStoreMockRecorder) UpdateInvitationStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInvitationStatus", reflect.TypeOf((*MockStore)(nil).UpdateInvitationStatus), ctx, id, status)
}

// WriteTaskRecords mocks base method.
func (m *MockStore) WriteTaskRecords(ctx context.Context, bounty *models.Bounty, hunterUsername string, outcome models.TaskRecordOutcome, outcomeDetail string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteTaskRecords", ctx, bounty, hunterUsername, outcome, outcomeDetail)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteTaskRecords indicates an expected call of WriteTaskRecords.
func (mr *MockStoreMockRecorder) WriteTaskRecords(ctx, bounty, hunterUsername, outcome, outcomeDetail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteTaskRecords", reflect.TypeOf((*MockStore)(nil).WriteTaskRecords), ctx, bounty, hunterUsername, outcome, outcomeDetail)
}

// MockBankClient is a mock of BankClient interface.
type MockBankClient struct {
	ctrl     *gomock.Controller
	recorder *MockBankClientMockRecorder
	isgomock struct{}
}

// MockBankClientMockRecorder is the mock recorder for MockBankClient.
type MockBankClientMockRecorder struct {
	mock *MockBankClient
}

// NewMockBankClient creates a new mock instance.
func NewMockBankClient(ctrl *gomock.Controller) *MockBankClient {
	mock := &MockBankClient{ctrl: ctrl}
	mock.recorder = &MockBankClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBankClient) EXPECT() *MockBankClientMockRecorder {
	return m.recorder
}

// BountyPayout mocks base method.
func (m *MockBankClient) BountyPayout(ctx context.Context, employerAccountID, hunterAccountID, amount, bountyID int64, description, idempotencyKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BountyPayout", ctx, employerAccountID, hunterAccountID, amount, bountyID, description, idempotencyKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// BountyPayout indicates an expected call of BountyPayout.
func (mr *MockBankClientMockRecorder) BountyPayout(ctx, employerAccountID, hunterAccountID, amount, bountyID, description, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BountyPayout", reflect.TypeOf((*MockBankClient)(nil).BountyPayout), ctx, employerAccountID, hunterAccountID, amount, bountyID, description, idempotencyKey)
}

// Freeze mocks base method.
func (m *MockBankClient) Freeze(ctx context.Context, employerAccountID, amount, bountyID int64, description, idempotencyKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Freeze", ctx, employerAccountID, amount, bountyID, description, idempotencyKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// Freeze indicates an expected call of Freeze.
func (mr *MockBankClientMockRecorder) Freeze(ctx, employerAccountID, amount, bountyID, description, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Freeze", reflect.TypeOf((*MockBankClient)(nil).Freeze), ctx, employerAccountID, amount, bountyID, description, idempotencyKey)
}

// ListAccounts mocks base method.
func (m *MockBankClient) ListAccounts(ctx context.Context) ([]*pb.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAccounts", ctx)
	ret0, _ := ret[0].([]*pb.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAccounts indicates an expected call of ListAccounts.
func (mr *MockBankClientMockRecorder) ListAccounts(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAccounts", reflect.TypeOf((*MockBankClient)(nil).ListAccounts), ctx)
}

// Transfer mocks base method.
func (m *MockBankClient) Transfer(ctx context.Context, fromAccount, toAccount, amount int64, idempotencyKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transfer", ctx, fromAccount, toAccount, amount, idempotencyKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// Transfer indicates an expected call of Transfer.
func (mr *MockBankClientMockRecorder) Transfer(ctx, fromAccount, toAccount, amount, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transfer", reflect.TypeOf((*MockBankClient)(nil).Transfer), ctx, fromAccount, toAccount, amount, idempotencyKey)
}

// Unfreeze mocks base method.
func (m *MockBankClient) Unfreeze(ctx context.Context, employerAccountID, amount, bountyID int64, description, idempotencyKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unfreeze", ctx, employerAccountID, amount, bountyID, description, idempotencyKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unfreeze indicates an expected call of Unfreeze.
func (mr *MockBankClientMockRecorder) Unfreeze(ctx, employerAccountID, amount, bountyID, description, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unfreeze", reflect.TypeOf((*MockBankClient)(nil).Unfreeze), ctx, employerAccountID, amount, bountyID, description, idempotencyKey)
}

// VerifyAccountOwner mocks base method.
func (m *MockBankClient) VerifyAccountOwner(ctx context.Context, accountID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyAccountOwner", ctx, accountID)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyAccountOwner indicates an expected call of VerifyAccountOwner.
func (mr *MockBankClientMockRecorder) VerifyAccountOwner(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyAccountOwner", reflect.TypeOf((*MockBankClient)(nil).VerifyAccountOwner), ctx, accountID)
}
